SELECT DIS.*
FROM DISTANCE_RC_OTM DIS; 

SELECT DIS.*
FROM DISTANCE_RC_OTM DIS INNER JOIN
REGION_DETAIL REG ON DIS.DEST_OTM_LOCATION_GID = REG.LOCATION_GID INNER JOIN
REGION_DETAIL REG2 ON DIS.DEST_OTM_LOCATION_GID = REG2.LOCATION_GID
WHERE ID = 1;

SELECT *
FROM DISTANCE_RC_OTM DIS INNER JOIN
(SELECT X_LANE_GID, X_LANE_XID, SOURCE_REGION_GID, DEST_REGION_GID 
FROM X_LANES
WHERE X_LANE_XID LIKE '%|%|%') X ON DIS.DEST_OTM_LOCATION_GID = X.LOCATION_GID;

SELECT X_LANE_GID, X_LANE_XID, SOURCE_REGION_GID, DEST_REGION_GID 
FROM X_LANES
WHERE X_LANE_XID LIKE '%|%|%';



SELECT X_LANE_GID, X_LANE_XID, SOURCE_REGION_GID, DEST_REGION_GID 
FROM X_LANES X INNER JOIN
REGION_DETAIL REG ON DIS.DEST_OTM_LOCATION_GID = X.LOCATION_GID
WHERE X_LANE_XID LIKE '%|%|%';

SELECT *
FROM DISTANCE_BY_LOCATION_LOCATION;

SELECT *
FROM DISTANCE_RC_OTM
WHERE DEST_OTM_LAT IS NULL OR DEST_OTM_LON IS NULL;

SELECT ROUND(DESTINATION_LATITUDE, 5)DESTINATION_LATITUDE, DEST_OTM_LAT, ROUND(DESTINATION_LONGITUD, 5) DESTINATION_LONGITUD, DEST_OTM_LON
FROM DISTANCE_RC_OTM
WHERE DEST_OTM_LAT != ROUND(DESTINATION_LATITUDE, 5) OR DEST_OTM_LON != ROUND(DESTINATION_LONGITUD, 5);