ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';



SELECT * FROM MANAGER_LAYOUT 
where MANAGER_LAYOUT_GID  like '%ORDER_RELEASE%';

--Finder Set (Screen Set)
SELECT * 
FROM FINDER_SET@OTMRO.NIAGARAWATER.COM
WHERE FINDER_SET_GID  = 'NBL/MX.ORDER_RELEASE_CUSTOMER_LOGISTICS_MX';
--'%ORDER_RELEASE_CSR1_NBL%';



SELECT * FROM GL_USER@OTMRO.NIAGARAWATER.COM
WHERE DOMAIN_NAME = 'NBL/MX'
AND GL_USER_GID LIKE '%AROUGERIO%';



update shipment_remark set remark_text = (
    SELECT TO_CHAR ( UTC.GET_LOCAL_DATE (S.APPOINTMENT_DELIVERY, s.location_gid),'YYYY-MM-DD HH24:MI') || '---' || l.location_xid || ', ' || l.city || ', ' || l.province_code || ', ' || l.postal_code 
    FROM shipment_stop s, location l 
    WHERE s.shipment_gid = $gid 
    AND s.stop_num != 1 
    AND s.location_gid = l.location_gid
    
    
    ) 
    where shipment_gid=$gid and remark_qual_gid like 'NBL.DELIVERY_STOP_%';
    
    
    SELECT S.APPOINTMENT_DELIVERY || '---' || l.location_xid || ', ' || l.city || ', ' || l.province_code || ', ' || l.postal_code 
    FROM shipment_stop@OTMRO.NIAGARAWATER.COM s, location@OTMRO.NIAGARAWATER.COM l 
    WHERE s.shipment_gid IN ('NBL/MX.MX23041874' ,'NBL/MX.MX23046082')
    AND s.stop_num != 1 
    AND s.location_gid = l.location_gid;
    
    
    INSERT INTO shipment_remark (shipment_gid, remark_sequence, remark_qual_gid, remark_text, domain_name) 
    SELECT DISTINCT s.shipment_gid, 09905+s.stop_num, 'NBL.DELIVERY_STOP_' ||s.stop_num, TO_CHAR(UTC.GET_LOCAL_DATE(S.APPOINTMENT_DELIVERY, s.location_gid), 'YYYY-MM-DD HH24:MI')||'---'||l.location_xid||', ' ||l.city||', '||l.province_code||', '||l.postal_code, s.domain_name FROM shipment_stop s, location l WHERE s.shipment_gid = $gid AND s.stop_num != 1 AND s.location_gid = l.location_gid;
    
    
    
    
    Select 1 
    from shipment@OTMRO.NIAGARAWATER.COM s , location_profile_detail@OTMRO.NIAGARAWATER.COM lpd 
    where shipment_gid IN ('NBL/MX.MX23041874' ,'NBL/MX.MX23046082') 
    and (s.dest_location_gid =lpd.location_gid or s.source_location_gid=lpd.location_gid) 
    and lpd.location_profile_gid ='NBL.LOCATION_ELIGIBLE_FOR_FK_APPOINTMENTS' 
    and s.source_location_gid like 'NBL.ORG%' 
    and s.dest_location_gid LIKE 'NBL.ORG%';
    
    
    
    select shipment_gid 
    from shipment@OTMRO.NIAGARAWATER.COM
    where source_location_gid like '%ORG%' 
    and dest_location_gid like '%ORG%' 
    and shipment_gid IN ('NBL/MX.MX23041874' ,'NBL/MX.MX23046082') ;
    
    
    
    
    --INSERT INTO shipment_remark (shipment_gid, remark_sequence, remark_qual_gid, remark_text, domain_name) 
    
    SELECT DISTINCT s.shipment_gid, s.stop_num, 'NBL.DELIVERY_STOP_' || s.stop_num, TO_CHAR ( glogowner.UTC.GET_LOCAL_DATE (S.APPOINTMENT_DELIVERY, s.location_gid),'YYYY-MM-DD HH24:MI')||'---'||l.location_xid||', ' ||l.city||', '||l.province_code||', '||l.postal_code, s.domain_name 
    FROM shipment_stop@OTMRO.NIAGARAWATER.COM s, location@OTMRO.NIAGARAWATER.COM l 
    WHERE s.shipment_gid IN ('NBL/MX.MX23041874' ,'NBL/MX.MX23046082')  
    AND s.stop_num != 1 
    AND s.location_gid = l.location_gid;
    
    
    
    
    
select o.order_release_gid AS "PK", 
orr.order_release_refnum_value AS "Customer PO", 
o.early_delivery_date AS "Early Delivery Date",
o.source_location_gid AS "Source Location ID" , 
o.dest_location_gid AS "Destination Location ID",
it.DESCRIPTION AS "Item",
SUM(orl.ITEM_PACKAGE_COUNT) AS "Count",
o.ATTRIBUTE2 AS "Pending Reason",
o.insert_date AS "Insert Time"
from ORDER_RELEASE@OTMRO.NIAGARAWATER.COM o , ORDER_RELEASE_REFNUM@OTMRO.NIAGARAWATER.COM orr , LOCATION@OTMRO.NIAGARAWATER.COM ls, ORDER_RELEASE_LINE@OTMRO.NIAGARAWATER.COM orl, ITEM@OTMRO.NIAGARAWATER.COM it, PACKAGED_ITEM@OTMRO.NIAGARAWATER.COM pi 
where (o.insert_date between (sysdate + (-182.16666666666666)) and (sysdate + (0.3333333333333333)))
and (o.domain_name='NBL/MX') 
and (o.late_delivery_date between trunc(TO_DATE('2023-08-28 08:00:00','YYYY-MM-DD HH24:MI:SS'),'MI') and trunc(TO_DATE('2023-09-01 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'MI')+0.99999) 
and (o.user_defined2_icon_gid is null) 
and (o.source_location_gid=ls.location_gid) 
and (ls.location_xid like 'ORG-2024-98884%')
and o.order_release_gid = orr.order_release_gid 
and orr.order_release_refnum_qual_gid = 'CUST_PO'
and o.ORDER_RELEASE_GID = orl.ORDER_RELEASE_GID
and pi.PACKAGED_ITEM_GID = orl.PACKAGED_ITEM_GID 
and pi.ITEM_GID = it.ITEM_GID  
--and o.order_release_xid = '32669269'
group by o.order_release_gid, orr.order_release_refnum_value, o.early_delivery_date, o.source_location_gid, o.dest_location_gid, o.ATTRIBUTE2, o.insert_date, it.DESCRIPTION
ORDER BY o.order_release_gid;






SELECT sysdate, (sysdate + (-30)), 
(sysdate + (182/*0.3333333333333333*/)),
TO_CHAR(ADD_MONTHS(TO_DATE(sysdate, 'YYYYMM'), -1), 'YYYYMM')
FROM DUAL;



select o.order_release_gid AS "PK", 
orr.order_release_refnum_value AS "Customer PO", 
o.early_delivery_date AS "Early Delivery Date",
o.source_location_gid AS "Source Location ID" , 
o.dest_location_gid AS "Destination Location ID",
it.DESCRIPTION AS "Item",
SUM(orl.ITEM_PACKAGE_COUNT) AS "Count",
o.ATTRIBUTE2 AS "Pending Reason",
o.insert_date AS "Insert Time"
from ORDER_RELEASE@OTMRO.NIAGARAWATER.COM o , ORDER_RELEASE_REFNUM@OTMRO.NIAGARAWATER.COM orr , LOCATION@OTMRO.NIAGARAWATER.COM ls, ORDER_RELEASE_LINE@OTMRO.NIAGARAWATER.COM orl, ITEM@OTMRO.NIAGARAWATER.COM it, PACKAGED_ITEM@OTMRO.NIAGARAWATER.COM pi
where (o.late_delivery_date between (sysdate + (-30)) and (sysdate + (182/*0.3333333333333333*/)))
and (o.domain_name='NBL/MX') 
--and (o.late_delivery_date between trunc(TO_DATE('2023-07-01 08:00:00','YYYY-MM-DD HH24:MI:SS'),'MI') and trunc(TO_DATE('2023-07-31 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'MI')+0.99999) 
and (o.user_defined2_icon_gid is null) --	Ship Confirmed
and (o.source_location_gid=ls.location_gid) 
and (ls.location_xid IN ('ORG-2024-98884','ORG-1894-94008','ORG-3767-152492','ORG-4729-194868','ORG-4769-195887'))
and o.order_release_gid = orr.order_release_gid 
and orr.order_release_refnum_qual_gid = 'CUST_PO'
and o.ORDER_RELEASE_GID = orl.ORDER_RELEASE_GID
and pi.PACKAGED_ITEM_GID = orl.PACKAGED_ITEM_GID 
and pi.ITEM_GID = it.ITEM_GID  
and o.ORDER_RELEASE_TYPE_GID in ('SALES_ORDER','NBL.TRANSFER_FG', 'NBL.TRANSFER_RM')
--and o.order_release_xid = '32669269'
group by o.order_release_gid, orr.order_release_refnum_value, o.early_delivery_date, o.source_location_gid, o.dest_location_gid, o.ATTRIBUTE2, o.insert_date, it.DESCRIPTION
ORDER BY o.order_release_gid;


----------

select o.order_release_gid AS "PK", 
orr.order_release_refnum_value AS "Customer PO", 
o.early_delivery_date AS "Early Delivery Date",
o.source_location_gid AS "Source Location ID" , 
o.dest_location_gid AS "Destination Location ID",
it.ITEM_NAME AS "Item Name",
it.DESCRIPTION AS "Item",
SUM(orl.ITEM_PACKAGE_COUNT) AS "Count",
o.ATTRIBUTE2 AS "Pending Reason",
o.insert_date AS "Insert Time",

sh.SHIPMENT_GID AS "PK_SHIPMENT",
SR.SHIPMENT_REFNUM_VALUE AS "Delivery Number", 
SRK.REMARK_TEXT AS "Pickup Appointment"

from ORDER_RELEASE@OTMRO.NIAGARAWATER.COM o INNER JOIN
ORDER_RELEASE_REFNUM@OTMRO.NIAGARAWATER.COM orr ON o.order_release_gid = orr.order_release_gid INNER JOiN
LOCATION@OTMRO.NIAGARAWATER.COM ls ON o.source_location_gid=ls.location_gid INNER JOIN
ORDER_RELEASE_LINE@OTMRO.NIAGARAWATER.COM orl ON o.ORDER_RELEASE_GID = orl.ORDER_RELEASE_GID INNER JOIN
PACKAGED_ITEM@OTMRO.NIAGARAWATER.COM pi ON pi.PACKAGED_ITEM_GID = orl.PACKAGED_ITEM_GID INNER JOIN
ITEM@OTMRO.NIAGARAWATER.COM it ON pi.ITEM_GID = it.ITEM_GID LEFT JOIN

ORDER_MOVEMENT@OTMRO.NIAGARAWATER.COM OM ON O.order_release_gid = OM.order_release_gid LEFT JOIN
SHIPMENT@OTMRO.NIAGARAWATER.COM sh ON OM.shipment_gid = sh.shipment_gid LEFT JOIN
SHIPMENT_TYPE@OTMRO.NIAGARAWATER.COM stp ON sh.shipment_type_gid=stp.shipment_type_gid and stp.shipment_type_xid!='NON FREIGHT RELATED CHARGE' LEFT JOIN
SHIPMENT_REFNUM@OTMRO.NIAGARAWATER.COM sr ON sh.shipment_gid = sr.shipment_gid and sr.shipment_refnum_qual_gid = 'NBL.OR_GROUP' LEFT JOIN
SHIPMENT_REMARK@OTMRO.NIAGARAWATER.COM srk ON sh.shipment_gid = srk.shipment_gid and srk.remark_qual_gid = 'NBL.PU_APPOINTMENT'

--where (o.late_delivery_date between (sysdate + (-30)) and (sysdate + (182/*0.3333333333333333*/)))
where (o.late_delivery_date between to_date(trunc(add_months(sysdate,-1),'MM')) and (sysdate + (182/*0.3333333333333333*/)))
and (o.domain_name='NBL/MX') 
--and (o.late_delivery_date between trunc(TO_DATE('2023-07-01 08:00:00','YYYY-MM-DD HH24:MI:SS'),'MI') and trunc(TO_DATE('2023-07-31 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'MI')+0.99999) 
and (o.user_defined2_icon_gid is null) --	Ship Confirmed
and (ls.location_xid IN ('ORG-2024-98884','ORG-1894-94008','ORG-3767-152492','ORG-4729-194868','ORG-4769-195887'))
and orr.order_release_refnum_qual_gid = 'CUST_PO'
and o.ORDER_RELEASE_TYPE_GID in ('SALES_ORDER','NBL.TRANSFER_FG', 'NBL.TRANSFER_RM')
--and o.order_release_xid = '32669269'
group by o.order_release_gid, orr.order_release_refnum_value, o.early_delivery_date, o.source_location_gid, o.dest_location_gid, o.ATTRIBUTE2, o.insert_date, it.ITEM_NAME, it.DESCRIPTION, sh.SHIPMENT_XID, sh.SHIPMENT_GID, SR.SHIPMENT_REFNUM_VALUE, SRK.REMARK_TEXT
ORDER BY o.order_release_gid;


---------



select o.order_release_gid AS "PK", 
orr.order_release_refnum_value AS "Customer PO", 
o.early_delivery_date AS "Early Delivery Date",
o.source_location_gid AS "Source Location ID" , 
o.dest_location_gid AS "Destination Location ID",
it.ITEM_NAME AS "Item Name",
it.DESCRIPTION AS "Item",
SUM(orl.ITEM_PACKAGE_COUNT) AS "Count",
o.ATTRIBUTE2 AS "Pending Reason",
o.insert_date AS "Insert Time",

sh.SHIPMENT_GID AS "PK_SHIPMENT",
SR.SHIPMENT_REFNUM_VALUE AS "Delivery Number", 
SRK.REMARK_TEXT AS "Pickup Appointment",
ors.STATUS_VALUE_GID  AS "Planning",
sh.UPDATE_USER AS "Shipment Update USer",
MIN(o.INSERT_DATE) OVER (PARTITION BY orr.order_release_refnum_value) AS "Original Date"


from ORDER_RELEASE@OTMRO.NIAGARAWATER.COM o INNER JOIN
ORDER_RELEASE_REFNUM@OTMRO.NIAGARAWATER.COM orr ON o.order_release_gid = orr.order_release_gid AND orr.ORDER_RELEASE_REFNUM_QUAL_GID = 'CUST_PO' INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM ls ON o.source_location_gid=ls.location_gid INNER JOIN
ORDER_RELEASE_LINE@OTMRO.NIAGARAWATER.COM orl ON o.ORDER_RELEASE_GID = orl.ORDER_RELEASE_GID INNER JOIN
PACKAGED_ITEM@OTMRO.NIAGARAWATER.COM pi ON pi.PACKAGED_ITEM_GID = orl.PACKAGED_ITEM_GID INNER JOIN
ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM ors ON o.order_release_gid = ors.order_release_gid AND ors.STATUS_TYPE_GID = 'NBL/MX.PLANNING' INNER JOIN
ITEM@OTMRO.NIAGARAWATER.COM it ON pi.ITEM_GID = it.ITEM_GID LEFT JOIN

ORDER_MOVEMENT@OTMRO.NIAGARAWATER.COM OM ON O.order_release_gid = OM.order_release_gid LEFT JOIN
SHIPMENT@OTMRO.NIAGARAWATER.COM sh ON OM.shipment_gid = sh.shipment_gid LEFT JOIN
SHIPMENT_TYPE@OTMRO.NIAGARAWATER.COM stp ON sh.shipment_type_gid=stp.shipment_type_gid and stp.shipment_type_xid!='NON FREIGHT RELATED CHARGE' LEFT JOIN
SHIPMENT_REFNUM@OTMRO.NIAGARAWATER.COM sr ON sh.shipment_gid = sr.shipment_gid and sr.shipment_refnum_qual_gid = 'NBL.OR_GROUP' LEFT JOIN
SHIPMENT_REMARK@OTMRO.NIAGARAWATER.COM srk ON sh.shipment_gid = srk.shipment_gid and srk.remark_qual_gid = 'NBL.PU_APPOINTMENT'


where (o.late_delivery_date between to_date(trunc(add_months(sysdate,-2),'MM')) and (sysdate + 1/*(0.3333333333333333)*/))
--(o.insert_date between to_date(trunc(add_months(sysdate,-1),'MM')) and (sysdate + (0.3333333333333333)))
and (o.domain_name='NBL/MX') 
--and (o.late_delivery_date between trunc(TO_DATE('2023-07-01 08:00:00','YYYY-MM-DD HH24:MI:SS'),'MI') and trunc(TO_DATE('2023-07-31 08:00:00','YYYY-MM-DD HH24:MI:SS'), 'MI')+0.99999) 
and (o.user_defined2_icon_gid is null) --	Ship Confirmed
and (ls.location_xid IN ('ORG-2024-98884','ORG-1894-94008','ORG-3767-152492','ORG-4729-194868','ORG-4769-195887'))
--and orr.order_release_refnum_qual_gid = 'CUST_PO'
and o.ORDER_RELEASE_TYPE_GID in ('SALES_ORDER','NBL.TRANSFER_FG')

--and o.order_release_xid IN ('34574523','34574524')
--and orr.ORDER_RELEASE_REFNUM_VALUE = '2351013576'
--and orr.ORDER_RELEASE_REFNUM_VALUE = '7180153357'

group by o.order_release_gid, orr.order_release_refnum_value, o.early_delivery_date, o.source_location_gid, o.dest_location_gid, o.ATTRIBUTE2, o.insert_date, it.ITEM_NAME,it.DESCRIPTION, sh.SHIPMENT_XID, sh.SHIPMENT_GID, SR.SHIPMENT_REFNUM_VALUE, SRK.REMARK_TEXT, ors.STATUS_VALUE_GID,
sh.UPDATE_USER
ORDER BY o.order_release_gid;


------Primera Fecha de insersion


SELECT ORF.ORDER_RELEASE_REFNUM_VALUE AS CUST_PO, ORF.ORDER_RELEASE_GID AS DELIVERY, ORF.INSERT_DATE, MIN(ORF.INSERT_DATE) OVER () AS ORIGINAL_DATE
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM O INNER JOIN
ORDER_RELEASE_REFNUM@OTMRO.NIAGARAWATER.COM ORF ON O.ORDER_RELEASE_GID = ORF.ORDER_RELEASE_GID AND ORF.ORDER_RELEASE_REFNUM_QUAL_GID = 'CUST_PO'
WHERE ORF.ORDER_RELEASE_REFNUM_VALUE = '2351013576'
ORDER BY O.ORDER_RELEASE_GID;

--WHERE O.ORDER_RELEASE_GID IN ('NBL/MX.34546148','NBL/MX.34578065','NBL/MX.34578064','NBL/MX.34578058')
--WHERE ORDER_RELEASE_GID IN ('NBL/MX.34569394','NBL/MX.34579833','NBL/MX.34579834','NBL/MX.34579835')
--WHERE ORDER_RELEASE_GID IN ('NBL/MX.34569361','NBL/MX.34728190','NBL/MX.34728191','NBL/MX.34728189')

----Regions--------------------------------------------------------------------------

SELECT L.LOCATION_XID
FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM R INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM L ON L.LOCATION_GID = R.LOCATION_GID
WHERE R.REGION_GID IN ('NBL/MX.MTY LOGISTIK COAHUILA',
'NBL/MX.SUPERMERCA_COAHUILA_CO_MEX',
'NBL/MX.GRUPO_TREVINO_SALTILLO_COAHUILA_MEX')
GROUP BY L.LOCATION_XID
ORDER BY L.LOCATION_XID;

--




('NBL/MX.MTY CAVAZOS CHIHUAHUA',
'NBL/MX.MTY REAL CHIHUAHUA',
'NBL/MX.FEMSA MTY CHIHUAHUA',
'NBL/MX.MTY FACI CHIHUAHUA',
'NBL/MX.FEMSA MTY CHIHUAHUA',
'NBL/MX.MTY FLETES CHIHUAHUA',
'NBL/MX.FEMSA MTY CHIHUAHUA',
'NBL/MX.MTY JULIAN CHIHUAHUA',
'NBL/MX.MTY TMTY CHIHUAHUA',
'NBL/MX.MTY NAFERMEX CHIHUAHUA',
'NBL/MX.MTY NUEVOMEX CHIHUAHUA',
'NBL/MX.FEMSA MTY CHIHUAHUA',
'NBL/MX.MTY READY SOL CHIHUAHUA',
'NBL/MX.MTY TERRAMEX CHIHUAHUA',
'NBL/MX.MTY TEVIAN CHIHUAHUA',
'NBL/MX.MXC 3GUERRAS CHIHUAHUA',
'NBL/MX.MTY TRU CHIHUAHUA',
'NBL/MX.MTY TUMSA CHIHUAHUA')

('NBL/MX.MTY CASTORES CULIACAN',
'NBL/MX.MTY DELREAL CULIACAN',
'NBL/MX.FEMSA MTY CULIACAN',
'NBL/MX.MTY FBR CULIACAN',
'NBL/MX.FEMSA MTY CULIACAN',
'NBL/MX.MTY GASTELUM CULIACAN',
'NBL/MX.MTY GRS CULIACAN',
'NBL/MX.MTY JMB CULIACAN',
'NBL/MX.MTY LOGISTORAGE CULIACAN',
'NBL/MX.MTY NUEVOMEX CULIACAN',
--'NBL/MX.MTY P&P CULIACAN',
'NBL/MX.MTY PROT CULIACAN',
'NBL/MX.MTY SOLBE CULIACAN',
'NBL/MX.MTY TAMEZ CULIACAN',
'NBL/MX.MTY TEVIAN CULIACAN',
'NBL/MX.MTY TMS CULIACAN',
'NBL/MX.MTY TRATE CULIACAN',
'NBL/MX.MTY 3GUERRAS CULIACAN','NBL/MX.MTY CULIACAN','NBL/MX.MTY ESJ MERGE CULIACAN',
'NBL/MX.MTY FEMSA MERGE CULIACAN')

('NBL/MX.ESJ MTY LOCAL',
'NBL/MX.MTY FEMSA LOCAL',
'NBL/MX.MTY GASTELUM LOCAL',
'NBL/MX.KARESAN MTY LOCAL',
'NBL/MX.MTY READY SOL LOCAL')

('NBL/MX.ESJ MTY LOCAL',
'NBL/MX.MTY FEMSA LOCAL',
'NBL/MX.MTY GASTELUM LOCAL',
'NBL/MX.KARESAN MTY LOCAL',
'NBL/MX.MTY READY SOL LOCAL')

('NBL/MX.MXC CASTORES VERACRUZ',
'NBL/MX.MXC ELOLA VERACRUZ',
'NBL/MX.MXC FEMSA VERACRUZ',
'NBL/MX.MXC SUPERTRACK VERACRUZ',
'NBL/MX.MXC TMX VERACRUZ',
'NBL/MX.MXC 3GUERRAS VERACRUZ',
'NBL/MX.MXC TUMSA VERACRUZ')

('NBL/MX.MXC ANDRADE PUEBLA',
'NBL/MX.MXC CASTORES PUEBLA',
'NBL/MX.MXC DANIEL PUEBLA',
'NBL/MX.MXC FEMSA PUEBLA',
'NBL/MX.MXC NIETO PUEBLA',
'NBL/MX.MXC SUPERTRACK PUEBLA',
'NBL/MX.MXC TEM PUEBLA',
'NBL/MX.MXC TMS PUEBLA',
'NBL/MX.MXC 3GUERRAS PUEBLA',
'NBL/MX.MXC TUMSA PUEBLA')

('NBL/MX.TUMSA MXC MERIDA',
'NBL/MX.MXC 3GUERRAS MERIDA',
'NBL/MX.MXC SUPERTRACK MERIDA',
'NBL/MX.MXC JJGC MERIDA',
'NBL/MX.MXC FEMSA MERIDA',
'NBL/MX.MXC CASTORES MERIDA')

('NBL/MX.MXC DANIEL VILLAHERMOSA',
'NBL/MX.MXC JJGC VILLAHERMOSA',
'NBL/MX.MXC TMS VILLAHERMOSA',
'NBL/MX.MXC TYAASA VILLAHERMOSA')

('NBL/MX.MXC CASTORES CANCUN',
'NBL/MX.MXC FEMSA CANCUN',
'NBL/MX.MXC JJGC CANCUN',
'NBL/MX.MXC LOGISTIK CANCUN',
'NBL/MX.MXC SUPERTRACK CANCUN',
'NBL/MX.MXC 3GUERRAS CANCUN',
'NBL/MX.MXC TUMSA CANCUN')

SELECT INSERT_USER,INSERT_DATE,UPDATE_USER,UPDATE_DATE,POSTAL_CODE
FROM LOCATION@OTMRO.NIAGARAWATER.COM
WHERE LOCATION_XID = 'ORG-4729-194868';

SELECT * FROM ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM
WHERE ORDER_RELEASE_GID = 'NBL/MX.34945970'; 

SELECT * FROM ORDER_RELEASE_STATUS_HISTORY@OTMRO.NIAGARAWATER.COM
WHERE ORDER_RELEASE_GID LIKE 'NBL/MX%'; 

SELECT * FROM ACCESSORIAL_COST@OTMRO.NIAGARAWATER.COM
WHERE ACCESSORIAL_COST_XID = 'FSC_EC_010223';

SELECT * FROM ACCESSORIAL_COST@OTMRO.NIAGARAWATER.COM
WHERE LOW_VALUE1 LIKE 'NBL.PADD5_WEST_COAST';
AND ACCESSORIAL_COST_GID = 'NBL.FSC_NIAGARA';

SELECT AC.*
FROM RATE_OFFERING_ACCESSORIAL@OTMRO.NIAGARAWATER.COM RO INNER JOIN
ACCESSORIAL_COST@OTMRO.NIAGARAWATER.COM AC ON RO.ACCESSORIAL_COST_GID = AC.ACCESSORIAL_COST_GID
WHERE RATE_OFFERING_GID = 'NBL.TRANSPLACE_TRANSFER'
AND ACCESSORIAL_CODE_GID = 'NBL.FSC_NIAGARA'
AND LOW_VALUE1 LIKE 'NBL.PADD5_WEST_COAST'
AND EXPIRATION_DATE IS NULL;



SELECT R.REGION_GID, L.LOCATION_XID
FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM R INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM L ON R.LOCATION_GID = L.LOCATION_GID
WHERE R.REGION_GID = 'NBL/MX.MXC 3GUERRAS COLIMA';

SELECT R.REGION_GID, L.LOCATION_XID
FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM R INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM L ON R.LOCATION_GID = L.LOCATION_GID
WHERE R.REGION_GID LIKE 'NBL/MX.3TJ%CABOS'
ORDER BY REGION_GID, L.LOCATION_XID;

NBL/MX.3TJ TRESGUERRAS TIJUANA

/*
'NBL/MX.MXC TMS CULIACAN'
'NBL/MX.MXC FEMSA MOCHIS'
'NBL/MX.MTY FEMSA CD OBREGON'
'NBL/MX.MXC FEMSA HERMOSILLO'
'NBL/MX.MTY TMS VALLARTA'
'NBL/MX.MXC 3GUERRAS COLIMA'
*/

SELECT * FROM LANE@OTMRO.NIAGARAWATER.COM L INNER JOIN
RATE_GEO@OTMRO.NIAGARAWATER.COM RG ON L.X_LANE_GID = RG.X_LANE_GID
WHERE L.DOMAIN_NAME = 'NBL/MX'
AND RG.IS_ACTIVE = 'Y';


select LOCATION_GID, LOCATION_NAME, POSTAL_CODE, UPDATE_DATE
from LOCATION@OTMRO.NIAGARAWATER.COM
WHERE COUNTRY_CODE3_GID = 'MEX'
GROUP BY LOCATION_GID, LOCATION_NAME  , POSTAL_CODE , UPDATE_DATE
HAVING length(POSTAL_CODE) < 5;

----Rates

SELECT RG.RATE_SERVICE_GID, RG.X_LANE_GID
FROM RATE_OFFERING@OTMRO.NIAGARAWATER.COM RO INNER JOIN
RATE_GEO@OTMRO.NIAGARAWATER.COM RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
RATE_GEO_COST_GROUP@OTMRO.NIAGARAWATER.COM RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST@OTMRO.NIAGARAWATER.COM RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID INNER JOIN
X_LANE@OTMRO.NIAGARAWATER.COM XL ON XL.X_LANE_GID = RG.X_LANE_GID
WHERE RG.IS_ACTIVE = 'Y'
AND RO.DOMAIN_NAME = 'NBL/MX'
ORDER BY RO.RATE_OFFERING_XID, SERV.SERVPROV_XID, LOC.LOCATION_NAME, RG.RATE_GEO_XID, RG.X_LANE_GID, XL.SOURCE_REGION_GID;


SELECT RO.RATE_OFFERING_XID, RG.RATE_GEO_XID, RG.RATE_SERVICE_GID, RG.X_LANE_GID, RTRIM(TO_CHAR(RGC.CHARGE_AMOUNT, '999,999,999.99')) CHARGE_AMOUNT
FROM SHIPMENT SH INNER JOIN
RATE_OFFERING@OTMRO.NIAGARAWATER.COM RO ON SH.RATE_OFFERING_GID  = RO.RATE_OFFERING_GID INNER JOIN
RATE_GEO@OTMRO.NIAGARAWATER.COM RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
RATE_GEO_COST_GROUP@OTMRO.NIAGARAWATER.COM RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST@OTMRO.NIAGARAWATER.COM RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID INNER JOIN
X_LANE@OTMRO.NIAGARAWATER.COM XL ON XL.X_LANE_GID = RG.X_LANE_GID
WHERE RG.IS_ACTIVE = 'Y'
AND RO.DOMAIN_NAME = 'NBL/MX'
ORDER BY RO.RATE_OFFERING_XID, RG.RATE_GEO_XID, RG.X_LANE_GID, XL.SOURCE_REGION_GID;


ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';


--SELECT SUM(X_LANE_GID) LANES, SUM(RATE_GEO_XID) RATES 
--FROM (
    SELECT SH.SHIPMENT_GID --COUNT(RG.RATE_GEO_XID) RATE_GEO_XID, COUNT(XL.X_LANE_GID) X_LANE_GID
    FROM SHIPMENT SH INNER JOIN
    SHIPMENT_STATUS  SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID INNER JOIN
    RATE_OFFERING RO ON SH.RATE_OFFERING_GID  = RO.RATE_OFFERING_GID INNER JOIN
    RATE_GEO RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
    X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID
    WHERE SH.DOMAIN_NAME = 'NBL/MX'
    AND STATUS_VALUE_GID  = 'NBL.ENROUTE_ENROUTE'
    AND STATUS_TYPE_GID  = 'NBL.ENROUTE'
    AND TRUNC (SH.INSERT_DATE) BETWEEN '01/01/2023' AND '31/12/2023';
    
    
SELECT * FROM STATUS_VALUE 
WHERE OBJECT_TYPE = 'SHIPMENT';

----------Locations
SELECT L.LOCATION_GID, L.LOCATION_NAME, L.CITY, L.PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.ZONE1, L.ZONE2, L.ZONE3, L.ZONE4 
FROM LOCATION@OTMRO.NIAGARAWATER.COM L INNER JOIN
ORDER_RELEASE@OTMRO.NIAGARAWATER.COM ORE ON ORE.DEST_LOCATION_GID = L.LOCATION_GID 
WHERE L.PROVINCE_CODE = 'MH'
AND TRUNC (ORE.INSERT_DATE) BETWEEN '01/01/2022' AND '31/12/2023'
GROUP BY L.LOCATION_GID, L.LOCATION_NAME, L.CITY, L.PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.ZONE1, L.ZONE2, L.ZONE3, L.ZONE4 
ORDER BY CITY;



---Service Providers

SELECT SERV.SERVPROV_GID, CONT.EMAIL_ADDRESS, CONT.EXTERNAL_SYSTEM_GID, COMM.COM_METHOD_GID,
COMM.INSERT_USER INSERT_USER_COMM, 
TO_CHAR(COMM.INSERT_DATE, 'DD/MM/YY') INSERT_DATE_COMM,
COMM.UPDATE_USER UPDATE_USER_COMM,
TO_CHAR(COMM.UPDATE_DATE, 'DD/MM/YY') UPDATE_DATE_COMM,
CONT.INSERT_USER INSERT_USER_CONT, 
TO_CHAR(CONT.INSERT_DATE, 'DD/MM/YY') INSERT_DATE_CONT,
CONT.UPDATE_USER UPDATE_USER_CONT,
TO_CHAR(CONT.UPDATE_DATE, 'DD/MM/YY') UPDATE_DATE_CONT,
SERV.INSERT_USER INSERT_USER_SERV, 
TO_CHAR(SERV.INSERT_DATE, 'DD/MM/YY') INSERT_DATE_SERV,
SERV.UPDATE_USER UPDATE_USER_SERV,
TO_CHAR(SERV.UPDATE_DATE, 'DD/MM/YY') UPDATE_DATE_SERV
FROM SERVPROV@OTMRO.NIAGARAWATER.COM SERV INNER JOIN
CONTACT@OTMRO.NIAGARAWATER.COM CONT ON SERV.SERVPROV_GID = CONT.CONTACT_GID INNER JOIN
CONTACT_COM_METHOD@OTMRO.NIAGARAWATER.COM COMM ON COMM.CONTACT_GID = CONT.CONTACT_GID
WHERE SERV.SERVPROV_GID = 'NBL.CAR-2480207';



SELECT *
FROM CONTACT_COM_METHOD@OTMRO.NIAGARAWATER.COM
WHERE CONTACT_GID = 'NBL.CAR-2480207';

SELECT *
FROM SERVPROV@OTMRO.NIAGARAWATER.COM
WHERE SERVPROV_GID = 'NBL.CAR-2480207';





-------------------------------------ServProv Shot Clock

SELECT * FROM CONTACT_COM_METHOD@OTMRO.NIAGARAWATER.COM WHERE CALENDAR_GID LIKE '%NBL.%' AND CONTACT_GID NOT IN ('NBL.CAR-2480207');




SELECT SHIPMENT_GID, COUNT(INVOICE_GID)
FROM INVOICE_SHIPMENT@OTMRO.NIAGARAWATER.COM
WHERE TRUNC (INSERT_DATE) BETWEEN '01/06/2023' AND '31/12/2023'
GROUP BY SHIPMENT_GID, INVOICE_GID
HAVING COUNT(INVOICE_GID) > 1;

--------------------------------------------------------------------
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';
SELECT SUM(SHIPMENTS) SHIPMENTS
FROM (
    SELECT COUNT(SH.SHIPMENT_GID) SHIPMENTS
    FROM SHIPMENT@OTMRO.NIAGARAWATER.COM SH INNER JOIN
    SHIPMENT_STATUS@OTMRO.NIAGARAWATER.COM  SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID
    WHERE SH.DOMAIN_NAME = 'NBL'
    AND SS.STATUS_TYPE_GID  = 'NBL.PAYMENT'
    AND SS.STATUS_VALUE_GID  = 'NBL.PAYMENT_VOUCHERED'
    AND TRUNC (SH.INSERT_DATE) BETWEEN '01/01/2023' AND '31/12/2023'
    GROUP BY SH.SHIPMENT_GID
);

ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';
SELECT SUM(SHIPMENTS) SHIPMENTS
FROM (
    SELECT COUNT(SH.SHIPMENT_GID) SHIPMENTS
    FROM SHIPMENT SH INNER JOIN
    SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID
    WHERE SH.DOMAIN_NAME = 'NBL/MX'
    AND SS.STATUS_TYPE_GID  = 'NBL/MX.PAYMENT'
    AND SS.STATUS_VALUE_GID  = 'NBL/MX.PAYMENT_VOUCHERED'
    AND TRUNC (SH.INSERT_DATE) BETWEEN '01/01/2023' AND '31/12/2023'
    GROUP BY SH.SHIPMENT_GID
);
    
    SELECT * FROM STATUS_VALUE 
    WHERE OBJECT_TYPE = 'SHIPMENT';
    
    
SELECT * FROM FINDER_SET
WHERE FINDER_SET_XID = 'ORDER_RELEASE_CUSTOMER_LOGISTICS_SUPERVISOR_MX';



---------------------Saved Query Bulk Plan Chalco------------------------------

SELECT ORR.ORDER_RELEASE_GID, ORR.ORDER_RELEASE_XID, ORR.DOMAIN_NAME 
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM ORR INNER JOIN 
     ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID 
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW' 
AND ORR.DOMAIN_NAME = 'NBL/MX'
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15 
AND ORR.DEST_LOCATION_GID IN ( 
                                SELECT LOCATION_GID 
                                FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM 
                                WHERE REGION_GID IN ('NBL/MX.MXC CHALCO', 'NBL/MX.MXC CUAUTITLAN', 'NBL/MX.MXC CDMX ZONAMETRO') 
                            );


SELECT ORR.ORDER_RELEASE_GID  
FROM ORDER_RELEASE ORR INNER JOIN 
ORDER_RELEASE_STATUS ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID 
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_PLANNED - FAILED' 
AND ORR.DOMAIN_NAME = 'NBL/MX' 
AND TRUNC(ORR.EARLY_DELIVERY_DATE) BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE + 7) 
AND ORR.DEST_LOCATION_GID IN ( 
SELECT LOCATION_GID 
FROM REGION_DETAIL 
WHERE REGION_GID IN ('NBL/MX.MXC CHALCO', 'NBL/MX.MXC CUAUTITLAN', 'NBL/MX.MXC CDMX ZONAMETRO') 
);

--AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW' 

SELECT TRUNC(SYSDATE), TRUNC(SYSDATE + 7)  FROM DUAL;
SELECT DISTINCT ORDER_RELEASE_GID 
FROM ORDER_RELEASE_STATUS 
WHERE  STATUS_TYPE_GID = 'NBL.ORDER_SHIPMENT_STATUS' 
AND STATUS_VALUE_GID != 'NBL.SHIP_ON_HOLD' 
AND ORDER_RELEASE_GID = ?;


SELECT * 
FROM ORDER_RELEASE_STATUS 
WHERE  STATUS_TYPE_GID like '%PLANNING%'
AND ORDER_RELEASE_GID = 'NBL/MX.32669269';

SELECT * FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_GID = 'NBL/MX.34492529';


SELECT TO_CHAR(TO_DATE('04-AUG-23','DD-MON-YY'), 'DD/MM/YYYY') FROM dual;



-----------------Capacity Allocation------------------------
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

-- Chalco
SELECT *
FROM (
    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE@OTMRO.NIAGARAWATER.COM CU INNER JOIN
    CAPACITY_GROUP@OTMRO.NIAGARAWATER.COM CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV@OTMRO.NIAGARAWATER.COM SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC@OTMRO.NIAGARAWATER.COM SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION@OTMRO.NIAGARAWATER.COM L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID IN ('NBL/MX.MXC|MXC CHALCO'
)
    AND TRUNC(START_DATE) BETWEEN '02/02/2024' AND '08/02/2024'
    --AND USAGE > 0
    ORDER BY LIMIT DESC
)
PIVOT
(
    SUM (LIMIT) LIMIT, 
    SUM (USAGE) USAGE
    FOR CAPACITY_GROUP_XID IN ('ANDRADE_24' ANDRADE,'TEM_DEDICADOS_24' TEM_D,'CORONA_24' CORONA,'FEMSA_24' FEMSA)
)
ORDER BY x_lane_gid, START_DATE ASC;

-- Cuautitlan
SELECT *
FROM (
    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE@OTMRO.NIAGARAWATER.COM CU INNER JOIN
    CAPACITY_GROUP@OTMRO.NIAGARAWATER.COM CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV@OTMRO.NIAGARAWATER.COM SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC@OTMRO.NIAGARAWATER.COM SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION@OTMRO.NIAGARAWATER.COM L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID = 'NBL/MX.MXC|MXC CUAUTITLAN'
    AND TRUNC(START_DATE) BETWEEN '02/02/2024' AND '08/02/2024'
    --AND USAGE > 0
    ORDER BY LIMIT DESC
)
PIVOT
(
    SUM (LIMIT) LIMIT, 
    SUM (USAGE) USAGE
    FOR CAPACITY_GROUP_XID IN ('ANDRADE_24' ANDRADE,'TEM_DEDICADOS_24' TEM_D, 'CORONA_24' CORONA,'FEMSA_24' FEMSA, 'MEXAMERIK_24' MEXAMERIK, 'DANIEL_MARTINEZ_24' DANIELMARTINEZ)
)
ORDER BY START_DATE ASC;


-- CDMX
SELECT *
FROM (
    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE@OTMRO.NIAGARAWATER.COM CU INNER JOIN
    CAPACITY_GROUP@OTMRO.NIAGARAWATER.COM CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV@OTMRO.NIAGARAWATER.COM SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC@OTMRO.NIAGARAWATER.COM SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION@OTMRO.NIAGARAWATER.COM L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID = 'NBL/MX.MXC|MXC CDMX ZONAMETRO'
    AND TRUNC(START_DATE) BETWEEN '02/02/2024' AND '08/02/2024'
    --AND USAGE > 0
    ORDER BY LIMIT DESC
)
PIVOT
(
    SUM (LIMIT) LIMIT, 
    SUM (USAGE) USAGE
    FOR CAPACITY_GROUP_XID IN ('ANDRADE_24' ANDRADE,'TEM_DEDICADOS_24' TEM_D, 'MEXAMERIK_24' MEXAMERIK, 'DANIEL_MARTINEZ_24' DANIELMARTINEZ, 'TEM_24' TEM, 'ALMARAZ_24' ALMARAZ, 'TMS_DEDICADOS_24' TMS_D)
)
ORDER BY START_DATE ASC;


-----------------------------------Locations for Region---------------------------------------------

SELECT LOC.LOCATION_GID, LOC.LOCATION_NAME
FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM REG INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM LOC ON LOC.LOCATION_GID = REG.LOCATION_GID
WHERE REG.REGION_GID LIKE '%MTY%LOCAL%'
GROUP BY LOC.LOCATION_GID, LOC.LOCATION_NAME
ORDER BY LOC.LOCATION_GID;




----------------

--insert into shipment_remark (shipment_gid,remark_sequence,remark_qual_gid,remark_text,domain_name)

select distinct s.shipment_gid,09905 + s.stop_num,'NBL.DELIVERY_STOP_' || s.stop_num,to_char (utc.get_local_date@OTMRO.NIAGARAWATER.COM (sh.end_time, s.location_gid),'YYYY-MM-DD HH24:MI') || '---'|| l.location_xid|| ', '|| l.city|| ', '|| l.province_code|| ', '|| l.postal_code,s.domain_name 
from shipment_stop@OTMRO.NIAGARAWATER.COM s, location@OTMRO.NIAGARAWATER.COM l, shipment@OTMRO.NIAGARAWATER.COM sh 
where s.shipment_gid = 'NBL/MX.MX24010215'--$gid 
and s.stop_num != 1 
and sh.shipment_gid=s.shipment_gid 
and s.location_gid = l.location_gid;



--INSERT INTO shipment_remark (shipment_gid, remark_sequence, remark_qual_gid, remark_text, domain_name) 

SELECT DISTINCT s.shipment_gid, 09905+s.stop_num, 'NBL.DELIVERY_STOP_' ||s.stop_num, TO_CHAR(UTC.GET_LOCAL_DATE@OTMRO.NIAGARAWATER.COM(S.APPOINTMENT_DELIVERY, s.location_gid), 'YYYY-MM-DD HH24:MI')||'---'||l.location_xid||', ' ||l.city||', '||l.province_code||', '||l.postal_code, s.domain_name 
FROM shipment_stop@OTMRO.NIAGARAWATER.COM s, location@OTMRO.NIAGARAWATER.COM l 
WHERE s.shipment_gid = 'NBL/MX.MX24010215'--$gid 
AND s.stop_num != 1 
AND s.location_gid = l.location_gid;


--INSERT INTO SHIPMENT_STOP_REMARK(SHIPMENT_GID, STOP_NUM, REMARK_SEQUENCE,REMARK_QUAL_GID,REMARK_TEXT,DOMAIN_NAME) 

SELECT distinct SSD.SHIPMENT_GID,SSD.STOP_NUM,$SSTOPREMSEQ,'NBL.APPT_DATE_TYPE',SUBSTR ( ORL.user_defined1_icon_gid,INSTR (ORL.user_defined1_icon_gid, '.') + 1,50),SSD.DOMAIN_NAME FROM SHIPMENT_STOP_D SSD, S_SHIP_UNIT_LINE SSUL, ORDER_RELEASE ORL WHERE SSD.SHIPMENT_GID = $gid AND SSD.ACTIVITY = 'D' AND SSUL.S_SHIP_UNIT_GID = SSD.S_SHIP_UNIT_GID AND SSUL.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID AND SSUL.S_SHIP_UNIT_LINE_NO = 1;




--update shipment_remark set remark_text = (
SELECT * FROM (
SELECT TO_CHAR ( UTC.GET_LOCAL_DATE@OTMRO.NIAGARAWATER.COM (S.APPOINTMENT_DELIVERY, s.location_gid),'YYYY-MM-DD HH24:MI') || '---' || l.location_xid || ', ' || l.city || ', ' || l.province_code || ', ' || l.postal_code 
FROM shipment_stop@OTMRO.NIAGARAWATER.COM s, location@OTMRO.NIAGARAWATER.COM l 
WHERE s.shipment_gid = 'NBL/MX.MX24010215' --$gid 
AND s.stop_num != 1 
AND s.location_gid = l.location_gid
) where shipment_gid= 'NBL/MX.MX24010215' 
and remark_qual_gid like 'NBL.DELIVERY_STOP_%';



---------Query Tricia

SELECT DISTINCT sa.servprov_alias_qual_gid, 
S.SERVPROV_GID,L.LOCATION_NAME AS CARRIER_NAME,
S.SCAC_GID,
C.EMAIL_ADDRESS,
L.CITY,
L.PROVINCE,
L.POSTAL_CODE,
L.COUNTRY_CODE3_GID,
L.TIME_ZONE_GID,
L.LAT,
L.LON,
lr.location_refnum_VALUE as SPOTNOW_STATUS, 
sa.alias AS ACTIVE_SPOT_REGION,
lrr.location_refnum_VALUE as CAPACITYPLUS_STATUS
FROM servprov_alias  sa, servprov s,LOCATION l,contact c,LOCATION LL, location_refnum lr, location_refnum lrr
WHERE s.broadcast_spot_contact_gid = c.contact_gid
AND sa.servprov_gid = s.servprov_gid
AND l.location_gid = sa.servprov_gid
AND LR.LOCATION_GID = L.LOCATION_GID
AND LRR.LOCATION_GID = L.LOCATION_GID
AND s.is_accept_spot_bids = 'Y'
AND s.allow_spot_rating = 'Y'
AND s.allow_tender = 'Y'
AND lr.location_refnum_qual_gid = 'NBL.SPOTNOW_STATUS'
AND LRR.location_refnum_qual_gid = 'NBL.CAPACITYPLUS_STATUS'
AND s.servprov_gid = 'NBL.CAR-2230730'
AND sa.servprov_alias_qual_gid LIKE '%SPOT%'
AND sa.servprov_alias_qual_gid != (select REGION_GROUP_GID from REGION_GROUP RG WHERE sa.servprov_alias_qual_gid = RG.REGION_GROUP_GID ) ;




---------Rate Geo----

SELECT RG.* 
FROM LANE@OTMRO.NIAGARAWATER.COM L INNER JOIN
RATE_GEO@OTMRO.NIAGARAWATER.COM RG ON L.X_LANE_GID = RG.X_LANE_GID
WHERE RG.RATE_GEO_GID IN ('NBL/MX.FEMSA|MXC|MXC FEMSA CHALCO|22',
'NBL/MX.MEXAMERIK|MXC|MXC MEXAMERIK CHALCO|22',
'NBL/MX.ANDRADE|MXC|MXC ANDRADE CHALCO|22',
'NBL/MX.DANIEL_MARTINEZ|MXC|MXC DANIEL CHALCO|22',
'NBL/MX.TEM|MXC|MXC TEM CHALCO|22',
'NBL/MX.CORONA|MXC|MXC CORONA CHALCO|22',
'NBL/MX.TUMSA|MXC|MXC TUMSA CHALCO|22',
'NBL/MX.TMS|MXC|MXC TMS CHALCO|22',
'NBL/MX.SAMSUNG|MXC|MXC SAMSUNG CHALCO|22',
'NBL/MX.MONCADA|MXC|MXC MONCADA CHALCO|22',
'NBL/MX.MEGAREY|MXC|MXC MEGAREY CHALCO|22')
AND RG.IS_ACTIVE = 'Y';



RG.RATE_GEO_GID IN ('NBL/MX.FEMSA|MXC|MXC FEMSA CHALCO|22','NBL/MX.MEXAMERIK|MXC|MXC MEXAMERIK CHALCO|22','NBL/MX.ANDRADE|MXC|MXC ANDRADE CHALCO|22','NBL/MX.DANIEL_MARTINEZ|MXC|MXC DANIEL CHALCO|22','NBL/MX.TEM|MXC|MXC TEM CHALCO|22','NBL/MX.CORONA|MXC|MXC CORONA CHALCO|22','NBL/MX.TUMSA|MXC|MXC TUMSA CHALCO|22','NBL/MX.TMS|MXC|MXC TMS CHALCO|22','NBL/MX.SAMSUNG|MXC|MXC SAMSUNG CHALCO|22','NBL/MX.MONCADA|MXC|MXC MONCADA CHALCO|22','NBL/MX.MEGAREY|MXC|MXC MEGAREY CHALCO|22')

-----------
SELECT *--USER_DEFINED1_ICON_GID
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM
WHERE ORDER_RELEASE_GID = 'NBL/MX.32218571';
--AND USER_DEFINED1_ICON_GID = 'NBL.NBL_SCHEDULED_APPT';


SELECT ORR.ORDER_RELEASE_GID, ORR.USER_DEFINED1_ICON_GID, ORR.DELIVERY_IS_APPT
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM ORR INNER JOIN 
     ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID 
WHERE ORR.DOMAIN_NAME = 'NBL/MX' 
AND ORR.DELIVERY_IS_APPT  = 'Y' 
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE 
AND ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
--AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_UNSCHEDULED' 
AND ORR.USER_DEFINED1_ICON_GID = 'NBL.NBL_SCHEDULED_APPT' 
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15 
AND ORR.DEST_LOCATION_GID IN ( 
                              SELECT LOCATION_GID  
                              FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM 
                              WHERE REGION_GID IN ('NBL/MX.MXC CHALCO', 'NBL/MX.MXC CUAUTITLAN', 'NBL/MX.MXC CDMX ZONAMETRO') 
                         );
                         
                         
SELECT ORR.ORDER_RELEASE_GID, ORS.STATUS_VALUE_GID 
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM ORR INNER JOIN 
     ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID 
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
--AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_UNSCHEDULED' 
AND ORR.DOMAIN_NAME = 'NBL/MX' 
--AND ORR.DELIVERY_IS_APPT  = 'Y' 
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE 
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15 
AND ORR.USER_DEFINED1_ICON_GID = 'NBL.NBL_SCHEDULED_APPT' 
AND ORR.DEST_LOCATION_GID IN ( 
                              SELECT LOCATION_GID 
                              FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM 
                              WHERE REGION_GID IN ('NBL/MX.MXC CANCUN','NBL/MX.MXC VILLAHERMOSA', 
                              'NBL/MX.MXC MERIDA','NBL/MX.MXC PUEBLA','NBL/MX.MXC VERACRUZ')  
                         );
                         
                         
                         
SELECT * FROM OB_ORDER_BASE@OTMRO.NIAGARAWATER.COM
WHERE DOMAIN_NAME = 'NBL/MX'
ORDER BY INSERT_DATE DESC;


SELECT * FROM GL_USER@OTMRO.NIAGARAWATER.COM
WHERE GL_USER_GID LIKE '%FORZA%';


SELECT * FROM LOCATION@OTMRO.NIAGARAWATER.COM
WHERE LOCATION_GID = 'NBL.CUS-1034553-114383';

SELECT R.DEST_LOCATION_GID, L.LOCATION_NAME LOCATION_ORG, R.PLAN_TO_LOCATION_GID, L2.LOCATION_NAME LOCATION_SUBS
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM R INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM L ON L.LOCATION_GID = R.DEST_LOCATION_GID INNER JOIN
LOCATION@OTMRO.NIAGARAWATER.COM L2 ON L2.LOCATION_GID = R.PLAN_TO_LOCATION_GID
WHERE TRUNC(R.INSERT_DATE) BETWEEN '04/03/2024' AND '08/03/2024'
AND R.DOMAIN_NAME = 'NBL/MX'
AND R.PLAN_TO_LOCATION_GID IS NOT NULL
GROUP BY R.DEST_LOCATION_GID, L.LOCATION_NAME, R.PLAN_TO_LOCATION_GID, L2.LOCATION_NAME;



CUS-1034553-114383,CUS-1034553-114394,CUS-1034553-114392,CUS-1034553-114383,CUS-1034553-114394,CUS-1034553-114410



SELECT * 
FROM REGION@OTMRO.NIAGARAWATER.COM
WHERE REGION_GID IN ('NBL.3MX_SHIPPING_REGION',
'NBL.3TJ_SHIPPING_REGION',
'NBL/MX.3GD_SHIPPING_REGION',
'NBL.MTY_SHIPPING_REGION',
'NBL.MXC_SHIPPING_REGION')
ORDER BY REGION_XID;


('NBL.3MX_SHIPPING_REGION',
'NBL.3TJ_SHIPPING_REGION',
'NBL/MX.3GD_SHIPPING_REGION',
'NBL.MTY_SHIPPING_REGION',
'NBL.MXC_SHIPPING_REGION');






SELECT RGG.RATE_GEO_GID, RGA.ACCESSORIAL_CODE_GID 
FROM RATE_GEO@OTMRO.NIAGARAWATER.COM RGG INNER JOIN 
RATE_GEO_ACCESSORIAL@OTMRO.NIAGARAWATER.COM RGA ON RGG.RATE_GEO_GID = RGA.RATE_GEO_GID-- AND RGA.ACCESSORIAL_CODE_GID <> 'NBL.FLAT_RATE'
WHERE RGG.X_LANE_GID = 'NBL.PLA|KENTUCKY_W' 
AND RGG.IS_ACTIVE = 'Y'
ORDER BY RGG.RATE_GEO_GID;

AND RGA.ACCESSORIAL_CODE_GID NOT IN ('NBL.FLAT_RATE');



SELECT *
FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM
WHERE REGION_GID IN ('NBL/MX.MXC CDMX ZONAMETRO','NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN', 'NBL/MX.ESJ MTY LOCAL');



SELECT ORR.ORDER_RELEASE_GID 
FROM ORDER_RELEASE@OTMRO.NIAGARAWATER.COM ORR INNER JOIN 
     ORDER_RELEASE_STATUS@OTMRO.NIAGARAWATER.COM ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID 
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW' 
AND ORR.DOMAIN_NAME = 'NBL/MX' 
AND ORR.DELIVERY_IS_APPT  = 'Y' 
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE 
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15 
AND ORR.DEST_LOCATION_GID IN ( 
                              SELECT LOCATION_GID 
                              FROM REGION_DETAIL@OTMRO.NIAGARAWATER.COM 
                              WHERE REGION_GID IN ('NBL/MX.MTY NUEVO LEON','NBL/MX.MTY CULIACAN','NBL/MX.MTY CHIHUAHUA','NBL/MX.MTY COAHUILA')  
                         );
     ------------------------------------------------------------------
     
     
     ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS';

SELECT * 
FROM ORDER_RELEASE  
WHERE ORDER_RELEASE_XID IN ('35889732', '35889733', '35882169');


SELECT *
FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_GID  IN ('NBL/MX.35889765')--, 'NBL/MX.35889733', 'NBL/MX.35882169');

SELECT RATE_GEO_COST_GROUP_GID, CHARGE_AMOUNT, CHARGE_CURRENCY_GID
FROM RATE_GEO_COST
WHERE RATE_GEO_COST_GROUP_GID  LIKE '%DEDICADOS%24%';


SELECT * FROM REGION_DETAIL
WHERE DOMAIN_NAME ;





SELECT * FROM TENDER_COLLAB_SERVPROV  
WHERE DOMAIN_NAME = 'NBL/MX'
--AND SERVPROV_GID = 'NBL.CAR-2955550'
AND I_TRANSACTION_NO IN (572156356, 572983788);

SELECT * 
FROM SERVPROV_TENDER_REFNUM  
WHERE DOMAIN_NAME = 'NBL/MX'
--AND SERVPROV_GID = 'NBL.CAR-2955550'
AND I_TRANSACTION_NO IN (572156356, 572983788);
/*
	SERVPROV_TENDER_COMMENT
 	SERVPROV_TENDER_EQUIPMENT
 	SERVPROV_TENDER_REFNUM
    
  */  
    

    