SELECT * 
FROM BS_STATUS_GROUP SG INNER JOIN
BS_STATUS_GROUP_PROFILE_D SGPD ON SG.BS_STATUS_GROUP_GID  = SGPD.BS_STATUS_GROUP_GID INNER JOIN
BS_STATUS_GROUP_REASON_GROUP_P SGRGP ON SGRGP.BS_STATUS_GROUP_GID = SG.BS_STATUS_GROUP_GID 
--BS_STATUS_GROUP_GID 
WHERE BS_STATUS_GROUP_XID = 'ARRIVED';


SELECT * FROM BS_STATUS_CODE_PROFILE_D;


SELECT * FROM BS_REASON_GROUP_REASON_CODE_P;