SELECT SOURCE, ESTADO, HRS_TRANSITO
FROM RATE_SERVICE_T
--WHERE SOURCE = '3TJ'
ORDER BY SOURCE, ESTADO;

SELECT SOURCE, ESTADO, MIN(HRS_TRANSITO) HRS_TRANSITO
FROM (
        SELECT SOURCE, DESTINO, ESTADO, to_number(regexp_replace(HRS_TRANSITO, '[^[:digit:]]', '')) HRS_TRANSITO 
        FROM RATE_SERVICE_T
        --WHERE SOURCE = '3TJ'
        ORDER BY SOURCE, ESTADO
) T
GROUP BY SOURCE, ESTADO
;

select regexp_replace(column_name, '[^[:digit:]]', '')