SELECT SOURCE_LOCATION_XID, SOURCE_LATITUDE, SOURCE_LONGITUD, DESTINATION_LOCATION_XID, DESTINATION_LATITUDE, DESTINATION_LONGITUD, DESTINATION_LOCATION_NAME, DISTANCE_KM
FROM DISTANCE_BY_LOCATION_LOCATION
--GROUP BY SOURCE_LOCATION_XID, DESTINATION_LOCATION_XID, DISTANCE_KM
;


