--Ordenes 2025 de Walmart
SELECT L.LOCATION_NAME--COUNT(ORE.ORDER_RELEASE_GID) AS ORDERS
FROM ORDER_RELEASE ORE INNER JOIN 
LOCATION L ON ORE.DEST_LOCATION_GID = L.LOCATION_GID
WHERE ORE.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(ORE.INSERT_DATE, 'YYYY-MM-DD') >= '2025-01-01' 
AND ORE.RATE_OFFERING_GID = 'NBL/MX.BKHL'
AND L.LOCATION_NAME LIKE '%WALMART%'


SELECT ORE.ORDER_RELEASE_GID, ORE.INSERT_DATE
FROM ORDER_RELEASE ORE 
WHERE ORE.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(ORE.INSERT_DATE, 'YYYY-MM-DD') >= '2025-01-01' 
AND ORE.RATE_OFFERING_GID = 'NBL/MX.BKHL'
ORDER BY ORE.INSERT_DATE DESC
--AND L.LOCATION_NAME LIKE '%WALMART%'

/*
WALMART 376
SAMS 786
*/

--Ordenes dentro de las regiones con capacity/allocation en BulkPlan

SELECT ORE.ORDER_RELEASE_GID, ORE.INSERT_DATE--COUNT(ORE.ORDER_RELEASE_GID) AS ORDERS
FROM ORDER_RELEASE ORE INNER JOIN 
LOCATION L ON ORE.DEST_LOCATION_GID = L.LOCATION_GID
WHERE ORE.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(ORE.INSERT_DATE, 'YYYY-MM-DD') >= '2025-01-01' 
AND L.LOCATION_GID IN (
                        SELECT LOCATION_GID
                        FROM REGION_DETAIL
                        WHERE REGION_GID IN 
                        (
                            'NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|CULIACAN',
                            'NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|SALTILLO',
                            'NBL/MX.MTY|MONCLOVA','NBL/MX.MTY|TORREON',
                            'NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN', 
                            'NBL/MX.MXC CDMX ZONAMETRO','NBL/MX.MXC|CANCUN',
                            'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA',
                            'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|VERACRUZ'
                        )
)
AND BULK_PLAN_GID LIKE '%OR%NEW%'



--Ordenes no BKHL y no dentro de las regiones con capacity/allocation
SELECT ORE.ORDER_RELEASE_GID, ORE.INSERT_DATE--COUNT(ORE.ORDER_RELEASE_GID) AS ORDERS
FROM ORDER_RELEASE ORE INNER JOIN 
LOCATION L ON ORE.DEST_LOCATION_GID = L.LOCATION_GID
WHERE ORE.DOMAIN_NAME = 'NBL/MX'
AND ORE.RATE_OFFERING_GID <> 'NBL/MX.BKHL'
AND TO_CHAR(ORE.INSERT_DATE, 'YYYY-MM-DD') >= '2025-01-01' 
AND L.LOCATION_GID NOT IN (
                        SELECT LOCATION_GID
                        FROM REGION_DETAIL
                        WHERE REGION_GID IN 
                        (
                            'NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|CULIACAN',
                            'NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|SALTILLO',
                            'NBL/MX.MTY|MONCLOVA','NBL/MX.MTY|TORREON',
                            'NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN', 
                            'NBL/MX.MXC CDMX ZONAMETRO','NBL/MX.MXC|CANCUN',
                            'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA',
                            'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|VERACRUZ'
                        )
)


SELECT X_LANE_GID  
FROM RATE_GEO
WHERE RATE_GEO_GID LIKE '%|25'


SELECT X_LANE_GID  
FROM RATE_GEO
WHERE RATE_GEO_GID LIKE '%|25'
AND DOMAIN_NAME = 'NBL/MX'
AND X_LANE_GID LIKE '%|%|%'
AND X_LANE_GID NOT IN (
    SELECT X_LANE_GID 
FROM CAPACITY_COMMITMENT_ALLOC
WHERE CAPACITY_COMMITMENT_ALLOC_GID LIKE '%HIGH_25'
)
GROUP BY X_LANE_GID

SELECT X_LANE_GID 
FROM CAPACITY_COMMITMENT_ALLOC
WHERE CAPACITY_COMMITMENT_ALLOC_GID LIKE '%HIGH_25'




SELECT 
        --XL.SOURCE_REGION_GID,
        --RD.REGION_GID DEST_REGION_GID, 
        XL.X_LANE_GID,
        XL.SOURCE_REGION_GID,
        XL.DEST_REGION_GID,
        XL.DEST_LOCATION_GID,
        COUNT(S.SHIPMENT_GID) SHIPMENTS
FROM SHIPMENT S INNER JOIN
        RATE_GEO RG ON S.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
        RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID INNER JOIN
        RATE_GEO_COST_GROUP RGCG ON RGCG.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
        RATE_GEO_COST RGC ON RGC.RATE_GEO_COST_GROUP_GID = RGCG.RATE_GEO_COST_GROUP_GID INNER JOIN
        X_LANE XL ON RG.X_LANE_GID = XL.X_LANE_GID INNER JOIN
        LOCATION L ON L.LOCATION_GID = S.DEST_LOCATION_GID INNER JOIN
        REGION_DETAIL RD ON RD.LOCATION_GID = L.LOCATION_GID
WHERE TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01'
AND S.DOMAIN_NAME = 'NBL/MX'
AND XL.X_LANE_GID NOT IN (
                        SELECT X_LANE_GID 
                        FROM CAPACITY_COMMITMENT_ALLOC
                        WHERE CAPACITY_COMMITMENT_ALLOC_GID LIKE '%HIGH_25'
                    )
GROUP BY XL.X_LANE_GID, XL.SOURCE_REGION_GID, XL.DEST_REGION_GID, 
XL.DEST_LOCATION_GID
ORDER BY XL.X_LANE_GID
--XL.SOURCE_REGION_GID, RD.REGION_GID



SELECT L.LOCATION_GID, L.LOCATION_XID, L.LOCATION_NAME, 
L.CITY, L.PROVINCE_CODE, L.POSTAL_CODE, L.LAT, L.LON, RD.REGION_GID
FROM LOCATION L INNER JOIN
REGION_DETAIL RD ON L.LOCATION_GID = RD.LOCATION_GID
WHERE L.COUNTRY_CODE3_GID = 'MEX'
AND L.PROVINCE_CODE IN ('DF','EM','CX')





