SELECT 
    T.SERVPROV_GID, 
    T.LOCATION_REFNUM_VALUE AS CARNM, 
    SUBSTR(T.SERVPROV_GID, 9, LENGTH(T.SERVPROV_GID) - 4)
FROM (
        SELECT SV.SERVPROV_GID, LOF.LOCATION_REFNUM_VALUE  
        FROM SERVPROV SV INNER JOIN
        LOCATION LO ON SV.SERVPROV_GID = LO.LOCATION_GID LEFT JOIN
        LOCATION_REFNUM  LOF ON LO.LOCATION_GID = LOF.LOCATION_GID AND LOCATION_REFNUM_QUAL_GID  = 'CARNM'
        WHERE 1 = 1
        AND REGEXP_LIKE(SUBSTR(SV.SERVPROV_GID, 9, LENGTH(SV.SERVPROV_GID) - 4), '^[A-Za-z]+$')
) T
WHERE T.LOCATION_REFNUM_VALUE IS NULL

;