SELECT CAR_ID,
    RATE_OFFERING_ID,
    RATE_SERVICE_ID,
    MODE_RW,
    SCAC FROM PROV;

    SELECT CARRIER_ID,
    CURRENCY_CODE,
    MODE_OF_TRANSPORT,
    VENDOR_NAME,
    FREIGHT_CODE,
    SCAC_CODE,
    SERVICE_LEVEL,
    SHIP_METHOD_MEANING,
    ORGANIZATION_CODE 
    FROM EBS_CARRIERS_LEVELS;


    SELECT P.CAR_ID,
    P.RATE_OFFERING_ID,
    P.RATE_SERVICE_ID,
    ESL.CARRIER_ID,
    ESL.CURRENCY_CODE,
    ESL.MODE_OF_TRANSPORT,
    ESL.VENDOR_NAME,
    ESL.FREIGHT_CODE,
    ESL.SCAC_CODE,
    ESL.SERVICE_LEVEL,
    --ESL.SHIP_METHOD_MEANING,
    ESL.ORGANIZATION_CODE 
    FROM EBS_CARRIERS_LEVELS ESL INNER JOIN 
    PROV P ON ESL.SCAC_CODE = P.SCAC AND P.RATE_SERVICE_ID = ESL.SERVICE_LEVEL AND ESL.MODE_OF_TRANSPORT = P.MODE_RW
    --WHERE P.SCAC = 'SOLI'
    ORDER BY P.CAR_ID, P.RATE_OFFERING_ID, P.RATE_SERVICE_ID
    ;