ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

SELECT O.DEST_LOCATION_GID, L.LOCATION_NAME, LA.ADDRESS, L.CITY, PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.LAT, L.LON
FROM ORDER_RELEASE O INNER JOIN
LOCATION L ON O.DEST_LOCATION_GID = L.LOCATION_GID INNER JOIN
(
    SELECT LOCATION_GID, LISTAGG(ADDRESS_LINE, ' ' on overflow truncate) WITHIN GROUP (ORDER BY LINE_SEQUENCE) AS ADDRESS
    FROM LOCATION_ADDRESS
    GROUP BY LOCATION_GID
) LA ON LA.LOCATION_GID = L.LOCATION_GID 
WHERE (O.INSERT_DATE BETWEEN TO_DATE(TRUNC(add_months(sysdate,-18),'MM')) AND (sysdate))
AND O.SOURCE_LOCATION_GID IN ('NBL.ORG-2024-98884','NBL.ORG-1894-94008','NBL.ORG-3767-152492','NBL.ORG-4769-195887','NBL.ORG-4729-194868')
GROUP BY LA.LOCATION_GID, O.DEST_LOCATION_GID, L.LOCATION_NAME, LA.ADDRESS, L.CITY, PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.LAT, L.LON
ORDER BY O.DEST_LOCATION_GID;



SELECT LOCATION_GID, LISTAGG(ADDRESS_LINE, ' ' on overflow truncate) WITHIN GROUP (ORDER BY LINE_SEQUENCE) AS ADDRESS
FROM LOCATION_ADDRESS
WHERE LOCATION_GID = 'NBL.CUS-1034553-103009'
GROUP BY LOCATION_GID;