--Query para conocer las asignaciones


SELECT SHIPMENT_XID, SERVPROV_GID, RATE_OFFERING_GID, RATE_GEO_GID
FROM SHIPMENT S INNER JOIN
SHIPMENT_STOP SS ON S.SHIPMENT.GID = SS.SHIPMENT_GID
WHERE SHIPMENT_XID = 'MX51079539';

MX51079539

SELECT XL.SOURCE_REGION_GID, XL.DEST_REGION_GID, XL.DEST_LOCATION_GID, XL.X_LANE_XID, RG.RATE_OFFERING_GID, RG.RATE_GEO_XID, RGC.CHARGE_AMOUNT  
FROM RATE_GEO RG INNER JOIN
X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN
RATE_GEO_COST_GROUP RGCG ON RGCG.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RGC ON RGC.RATE_GEO_COST_GROUP_GID = RGCG.RATE_GEO_COST_GROUP_GID
WHERE RG.DOMAIN_NAME = 'NBL/MX'
AND RG.IS_ACTIVE  = 'Y'
AND REGEXP_LIKE(XL.X_LANE_XID, '^[[:digit:]]+$') 
ORDER BY XL.X_LANE_XID;



SELECT RG.RATE_GEO_XID || ','
FROM RATE_GEO RG INNER JOIN
X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN
RATE_GEO_COST_GROUP RGCG ON RGCG.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RGC ON RGC.RATE_GEO_COST_GROUP_GID = RGCG.RATE_GEO_COST_GROUP_GID
WHERE RG.DOMAIN_NAME = 'NBL/MX'
AND RG.IS_ACTIVE  = 'Y'
AND REGEXP_LIKE(XL.X_LANE_XID, '^[[:digit:]]+$') 
GROUP BY RG.RATE_GEO_XID
ORDER BY RG.RATE_GEO_XID 