RefNum


PLANNING
PLANNING_EXECUTED - FINAL

Early 
Late


SELECT ORE.ORDER_RELEASE_GID, ORE.EARLY_DELIVERY_DATE, ORE.LATE_DELIVERY_DATE, TO_DATE(ORN.ORDER_RELEASE_REFNUM_VALUE, 'DD-MON-YYYY') AS ORIGINAL_REQUEST_DATE,
ORN.ORDER_RELEASE_REFNUM_QUAL_GID, ORS.STATUS_TYPE_GID, ORS.STATUS_VALUE_GID
FROM ORDER_RELEASE ORE INNER JOIN
ORDER_RELEASE_REFNUM ORN ON ORE.ORDER_RELEASE_GID = ORN.ORDER_RELEASE_GID AND ORN.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' INNER JOIN
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID  = 'NBL/MX.PLANNING' AND ORS.STATUS_VALUE_GID  = 'NBL/MX.PLANNING_EXECUTED - FINAL'
WHERE ORE.INSERT_DATE BETWEEN TO_DATE('2025-02-01', 'YYYY-MM-DD') AND TO_DATE('2025-02-04', 'YYYY-MM-DD') 
AND ORE.DOMAIN_NAME = 'NBL/MX'


SELECT ORE.ORDER_RELEASE_GID, ORE.EARLY_DELIVERY_DATE, ORE.LATE_DELIVERY_DATE, TO_DATE(ORN.ORDER_RELEASE_REFNUM_VALUE, 'DD-MON-YYYY') AS ORIGINAL_REQUEST_DATE, 
ORN.ORDER_RELEASE_REFNUM_QUAL_GID, ORS.STATUS_TYPE_GID, ORS.STATUS_VALUE_GID 
FROM ORDER_RELEASE ORE INNER JOIN 
ORDER_RELEASE_REFNUM ORN ON ORE.ORDER_RELEASE_GID = ORN.ORDER_RELEASE_GID AND ORN.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' INNER JOIN 
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID  = 'NBL/MX.PLANNING' AND ORS.STATUS_VALUE_GID  = 'NBL/MX.PLANNING_EXECUTED - FINAL' 
WHERE ORE.INSERT_DATE BETWEEN TO_DATE('2025-01-01', 'YYYY-MM-DD') AND TO_DATE('2025-06-30', 'YYYY-MM-DD')  
AND ORE.DOMAIN_NAME = 'NBL/MX' 
AND ORE.DEST_LOCATION_GID LIKE 'NBL.CUS%'
ORDER BY ORE.ORDER_RELEASE_GID ASC 



SELECT ORE.ORDER_RELEASE_GID, ORE.EARLY_DELIVERY_DATE, ORE.LATE_DELIVERY_DATE, TO_DATE(ORN.ORDER_RELEASE_REFNUM_VALUE, 'DD-MON-YYYY') AS ORIGINAL_REQUEST_DATE, 
ORN.ORDER_RELEASE_REFNUM_QUAL_GID, ORS.STATUS_TYPE_GID, ORS.STATUS_VALUE_GID 
FROM ORDER_RELEASE ORE INNER JOIN 
ORDER_RELEASE_REFNUM ORN ON ORE.ORDER_RELEASE_GID = ORN.ORDER_RELEASE_GID AND ORN.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' INNER JOIN 
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID  = 'NBL/MX.PLANNING' AND ORS.STATUS_VALUE_GID  = 'NBL/MX.PLANNING_EXECUTED - FINAL' 
WHERE ORE.INSERT_DATE BETWEEN TO_DATE('2025-07-01', 'YYYY-MM-DD') AND TO_DATE('2025-12-31', 'YYYY-MM-DD')  
AND ORE.DOMAIN_NAME = 'NBL/MX' 
AND ORE.DEST_LOCATION_GID LIKE 'NBL.CUS%'
ORDER BY ORE.ORDER_RELEASE_GID ASC 



SELECT COUNT(*) AS TOTAL_RECORDS 
FROM (  
    SELECT ORE.ORDER_RELEASE_GID 
    FROM ORDER_RELEASE ORE INNER JOIN 
    ORDER_RELEASE_REFNUM ORN ON ORE.ORDER_RELEASE_GID = ORN.ORDER_RELEASE_GID AND ORN.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' INNER JOIN 
    ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID  = 'NBL/MX.PLANNING' AND ORS.STATUS_VALUE_GID  = 'NBL/MX.PLANNING_EXECUTED - FINAL' 
    WHERE ORE.INSERT_DATE BETWEEN TO_DATE('2025-01-01', 'YYYY-MM-DD') AND TO_DATE('2025-01-31', 'YYYY-MM-DD')  
    AND ORE.DOMAIN_NAME = 'NBL/MX' 
    AND ORE.DEST_LOCATION_GID LIKE 'NBL.CUS%'
    AND TO_CHAR(ORE.EARLY_DELIVERY_DATE, 'YYYYMMDD') <> TO_CHAR( TO_DATE(ORN.ORDER_RELEASE_REFNUM_VALUE, 'DD-MON-YYYY'), 'YYYYMMDD')
) T 