/*
Audit Trail Tables:
DATA_INFO
DATA_INFO_DETAIL
AUDIT_DATA_INFO
AUDIT_TRAIL
*/

SELECT ORE.ORDER_RELEASE_GID, ORE.SOURCE_LOCATION_GID, 
    ORE.DEST_LOCATION_GID, AUT.AUDIT_TRAIL_GID, 
    ADI.DATA_INFO_SEQ, ORE.INSERT_DATE, 
    ORE.EARLY_DELIVERY_DATE, ORE.LATE_DELIVERY_DATE, 
    AUT.AUDIT_TIME, AUT.GL_USER_GID, 
    AUT.APP_ACTION_GID, DI.TABLE_NAME, 
    DI.ACTION, DI.PK_VALUE, 
    DID.COLUMN_NAME, DID.BEFORE_VALUE, 
    DID.AFTER_VALUE
FROM ORDER_RELEASE ORE INNER JOIN
AUDIT_TRAIL AUT ON ORE.ORDER_RELEASE_GID = AUT.OBJECT_GID INNER JOIN
AUDIT_DATA_INFO ADI ON AUT.AUDIT_TRAIL_GID = ADI.AUDIT_TRAIL_GID INNER JOIN
DATA_INFO  DI ON ADI.DATA_INFO_SEQ = DI.DATA_INFO_SEQ INNER JOIN
DATA_INFO_DETAIL DID ON DI.DATA_INFO_SEQ = DID.DATA_INFO_SEQ
WHERE 1 = 1 
--AND ORE.ORDER_RELEASE_GID = 'NBL/MX.41046979'
AND ORE.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(ORE.INSERT_DATE ,'YYYY-MM-DD') BETWEEN  '2026-02-08' AND '2026-02-14'
ORDER BY ORE.ORDER_RELEASE_GID, AUT.AUDIT_TIME ASC
;

/*
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' 
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_EXECUTED - FINAL' INNER JOIN
*/


--Insert time (que seria cuando viajo d Fusion a OTM no?), 
--Erly delivery y Late delivery


SELECT ST.SHIPMENT_GID FROM 
SHIPMENT SH , SHIPMENT_STATUS ST 
WHERE ST.STATUS_VALUE_GID = 'NBL.SECURE RESOURCES_TENDERED' 
AND SH.RATE_OFFERING_GID LIKE '%CPU%' 
AND SH.PERSPECTIVE = 'B' 
AND SH.SHIPMENT_TYPE_GID != 'NBL.NON FREIGHT RELATED CHARGE'
AND SH.SHIPMENT_GID = ST.SHIPMENT_GID 
AND SH.RATE_GEO_GID NOT LIKE 'NBL.CPU_CCNA_%'