SELECT DISTINCT 
    --ITM.I_TRANSMISSION_NO,
    SUBSTR(ITN.OBJECT_GID, 5, 3) AS ORG_CODE,
    SUBSTR(ITN.OBJECT_GID, 9, LENGTH(ITN.OBJECT_GID)-8) AS ITEM_CODE,
    ITN.OBJECT_GID,
    ITM.STATUS,
    ITM.CREATE_DATE
FROM I_TRANSACTION ITN INNER JOIN 
I_TRANSMISSION ITM ON ITN.I_TRANSMISSION_NO = ITM.I_TRANSMISSION_NO 
WHERE 1 = 1
AND ITM.IS_INBOUND='Y' 
AND ITN.ELEMENT_NAME ='ItemMaster' 
--AND ITM.I_TRANSMISSION_NO = 63980309
AND ITM.STATUS = 'ERROR'
AND SUBSTR(ITN.OBJECT_GID, 5, 3) IN ('3SV','3TJ','3MX','3GD','3EM','3MZ','MTY','MXC','GDL') 
AND ITM.INSERT_DATE BETWEEN TO_DATE('2025-12-25','YYYY-MM-DD') AND TO_DATE('2026-01-25','YYYY-MM-DD')



--AND ITM.INSERT_DATE > SYSDATE-1/24  

--AND ITN.TRANSACTION_CODE != 'D'