SELECT *
FROM MA_PROV_STATE;

SELECT *
FROM MA_FUSION_PROV_STATE;

SELECT STF.ESTADO, ST.STATE_PROV, STF.C2D
FROM MA_FUSION_PROV_STATE STF LEFT JOIN 
MA_PROV_STATE ST ON STF.C2D = ST.STATE_PROV;

SELECT STF.ESTADO, ST.STATE_PROV, STF.C3D
FROM MA_FUSION_PROV_STATE STF LEFT JOIN 
MA_PROV_STATE ST ON STF.C3D = ST.STATE_PROV;

SELECT STF.ESTADO, ST.STATE_PROV, STF.C2D
FROM MA_PROV_STATE ST LEFT JOIN 
MA_FUSION_PROV_STATE STF  ON STF.C2D = ST.STATE_PROV;