-------------------Original-------------------
INSERT INTO SHIPMENT_REFNUM (SHIPMENT_GID, SHIPMENT_REFNUM_QUAL_GID, SHIPMENT_REFNUM_VALUE, DOMAIN_NAME)
    (SELECT SHIPMENT_GID, REFNUM, LISTAGG(CLAVE_CODIGO_SAT,'|'), DOMAIN_NAME
    FROM (
        SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
        FROM (
            SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM,
            CASE
            WHEN SUBSTR(ORL.PACKAGED_ITEM_GID, INSTR(ORL.PACKAGED_ITEM_GID, '-')+1) IN ('8741403','8742281','8741453','8741625', '8735963') THEN '50202300'
            ELSE '50202301'
            END CLAVE_CODIGO_SAT,
            SH.DOMAIN_NAME
            FROM SHIPMENT SH INNER JOIN
            ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN
            ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
            WHERE SH.SHIPMENT_GID = $gid
        ) T
        GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
    )
    GROUP BY SHIPMENT_GID, REFNUM, DOMAIN_NAME
)

------------SELECT Nuevo-------------------
SELECT SHIPMENT_GID, REFNUM, LISTAGG(CLAVE_CODIGO_SAT,'|'), DOMAIN_NAME
FROM (
        SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
        FROM (
            SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM,
            CASE
            WHEN SUBSTR(ORL.PACKAGED_ITEM_GID, INSTR(ORL.PACKAGED_ITEM_GID, '-')+1) LIKE 'BUR%' THEN '50202300'
            ELSE '50202301'
            END CLAVE_CODIGO_SAT,
            SH.DOMAIN_NAME
            FROM SHIPMENT SH INNER JOIN
            ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN
            ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
            WHERE SH.SHIPMENT_GID = 'NBL/MX.MX5001007551'
        ) T
        GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
    )
GROUP BY SHIPMENT_GID, REFNUM, DOMAIN_NAME