SELECT * 
FROM RATE_OFFERING_ACCESSORIAL
WHERE DOMAIN_NAME = 'NBL/MX'

SELECT R.* 
FROM (
        SELECT RO.RATE_OFFERING_GID
        FROM SHIPMENT S INNER JOIN
                RATE_OFFERING RO ON S.RATE_OFFERING_GID = RO.RATE_OFFERING_GID
        WHERE TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01'
        AND S.DOMAIN_NAME = 'NBL/MX'
        GROUP BY RO.RATE_OFFERING_GID
) T INNER JOIN
RATE_OFFERING_ACCESSORIAL R ON T.RATE_OFFERING_GID = R.RATE_OFFERING_GID
ORDER BY R.RATE_OFFERING_GID


SELECT R.* FROM (SELECT RO.RATE_OFFERING_GID FROM SHIPMENT S INNER JOIN RATE_OFFERING RO ON S.RATE_OFFERING_GID = RO.RATE_OFFERING_GID WHERE TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01' AND S.DOMAIN_NAME = 'NBL/MX' GROUP BY RO.RATE_OFFERING_GID) T INNER JOIN RATE_OFFERING_ACCESSORIAL R ON T.RATE_OFFERING_GID = R.RATE_OFFERING_GID ORDER BY R.RATE_OFFERING_GID
