SELECT *
FROM OTM_CARRIERS_NEW CN LEFT JOIN
(
    SELECT SUBSTR(NEW_ID, 5, LENGTH(NEW_ID)-4) AS NEW_ID, OLD_ID
    FROM OTM_CARRIERS_OLD_NEW
) CON ON CN.SERVPROV = CON.NEW_ID
WHERE TARIFA_ACTIVA = 'Y'
ORDER BY CN.SERVPROV
;



SELECT *
FROM OTM_CARRIERS_NEW
WHERE SERVPROV LIKE '%FLETE%';

SELECT SUBSTR(NEW_ID, 5, LENGTH(NEW_ID)-4) AS NEW_ID, OLD_ID
FROM OTM_CARRIERS_OLD_NEW
WHERE NEW_ID LIKE '%FLETE%';



SELECT *
FROM OTM_CARRIERS CA LEFT JOIN
(
    SELECT SUBSTR(OLD_ID, 5, LENGTH(OLD_ID)-4) AS OLD_ID, NEW_ID
    FROM OTM_CARRIERS_OLD_NEW
) CON ON CA.SERVPROV = CON.OLD_ID
WHERE TARIFA_ACTIVA = 'N'
ORDER BY CA.SERVPROV
;