SELECT DISTINCT SOURCE
FROM NBL_AP_INVOICES_INTERFACE
--WHERE CURRENCY_CODE = 'MXN'
--WHERE INVOICE_NUMBER LIKE '%5530%'
;

SELECT * 
FROM NBL_AP_HDR_PEGASO_STG
--WHERE CURRENCY_CODE = 'MXN'
WHERE INVOICE_NUM LIKE '%5530%'
;


SELECT * 
FROM NBL_FRT_VOUCHER_AP_INV_IB_STG
WHERE BUSINESS_UNIT = 'Embotelladora Niagara de Mexico BU'
AND PROCESS_STATUS = 'E'
ORDER BY INVOICE_DATE DESC
;

