SELECT PARAMETER_VALUE FROM REPORT_LOG_PARAMETER WHERE PARAMETER_NAME ='P_SERVPROV' and FILE_NAME = $GID


select DISTINCT(I.SERVPROV_GID)  
from invoice i , invoice_status iss    
where i.invoice_gid = iss.invoice_gid    
AND iss.STATUS_VALUE_GID = 'NBL/MX.MATCH_FAILED'    
AND I.INSERT_DATE BETWEEN TO_DATE(TO_CHAR(SYSDATE,'DDMMYYYY') || '000000','DDMMYYYYHH24MISS')     
AND TO_DATE(TO_CHAR(SYSDATE,'DDMMYYYY') || '235959','DDMMYYYYHH24MISS')                      




select DISTINCT(I.SERVPROV_GID) 
from invoice i , invoice_status iss 
where i.invoice_gid = iss.invoice_gid 
AND iss.STATUS_VALUE_GID = 'NBL/MX.MATCH_FAILED' 
AND I.INSERT_DATE BETWEEN TO_DATE(TO_CHAR(SYSDATE,'DDMMYYYY') ||'000000','DDMMYYYYHH24MISS')  
AND TO_DATE(TO_CHAR(SYSDATE,'DDMMYYYY') ||'235959','DDMMYYYYHH24MISS') 


--GET_SERVPROV_FROM REPORT
SELECT PARAMETER_VALUE FROM REPORT_LOG_PARAMETER WHERE PARAMETER_NAME ='P_SERVPROV' and FILE_NAME = $GID

--GET_ADDITIONAL_CONTACT_FROM_REPORT
SELECT DISTINCT(C.CONTACT_GID) 
FROM REPORT_LOG_PARAMETER RLP,SERVPROV SP,CONTACT C 
WHERE SP.SERVPROV_GID IN(SELECT PARAMETER_VALUE 
                        FROM REPORT_LOG_PARAMETER
                        WHERE PARAMETER_NAME ='P_SERVPROV' 
                        and FILE_NAME = $GID) 
AND SP.SERVPROV_GID = C.LOCATION_GID 
AND C.IS_PRIMARY_CONTACT = 'N'


--AROUGERIO como contacto adicional
SERVPROV_GID
NBL.CAR-3771504
NBL.CAR-4744463
NBL.CAR-4795172