SELECT * 
FROM X_LANE
WHERE X_LANE_XID IN ('SAN|3MZ_SHIPPING_REGION',
'DAL|3MZ_SHIPPING_REGION',
'RIA|3MX_SHIPPING_REGION',
'PHI|3MX_SHIPPING_REGION',
'N10|3MX_SHIPPING_REGION',
'RIA|3TJ_SHIPPING_REGION',
'PHI|3TJ_SHIPPING_REGION',
'N10|3TJ_SHIPPING_REGION');


SELECT *
FROM REGION
WHERE REGION_GID IN ('NBL/MX.3MZ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL/MX.3MZ_SHIPPING_REGION');


SELECT *
FROM REGION_DETAIL
WHERE REGION_GID IN ('NBL/MX.3MZ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL/MX.3MZ_SHIPPING_REGION');


