SELECT * --SOURCE_REGION_GID, DEST_REGION_GID
FROM X_LANE
WHERE DEST_REGION_GID IN ('NBL.3MX_SHIPPING_REGION',
'NBL.3TJ_SHIPPING_REGION',
'NBL.MTY_SHIPPING_REGION',
'NBL.MXC_SHIPPING_REGION')
--GROUP BY SOURCE_REGION_GID, DEST_REGION_GID
;




SELECT * 
FROM REGION
WHERE REGION_XID IN ('3MX_SHIPPING_REGION','3TJ_SHIPPING_REGION','MTY_SHIPPING_REGION','MXC_SHIPPING_REGION')
AND DOMAIN_NAME = 'NBL';


('3MX_SHIPPING_REGION','3TJ_SHIPPING_REGION','MTY_SHIPPING_REGION','MXC_SHIPPING_REGION)


DAL|3MZ_SHIPPING_REGION,DAL|3GD_SHIPPING_REGION,LAN|3MZ_SHIPPING_REGION,RIA|3MX_SHIPPING_REGION,RIA|3TJ_SHIPPING_REGION,PHI|3MX_SHIPPING_REGION,PHI|3TJ_SHIPPING_REGION,N10|3MX_SHIPPING_REGION,N10|3TJ_SHIPPING_REGION,SAN|3GD_SHIPPING_REGION,SAN|3MZ_SHIPPING_REGION