/*
Como obtener las regiones a las que si van los embarques dedicados
*/



SELECT *L2.LOCATION_NAME DEST_LOCATION,  RD2.REGION_GID
FROM (

        SELECT S.RATE_OFFERING_GID, L.LOCATION_NAME SRC_LOCATION, RG.RATE_GEO_GID--, RD.REGION_GID
        FROM SHIPMENT S INNER JOIN
            RATE_GEO RG ON S.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
            RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID INNER JOIN
            LOCATION L ON L.LOCATION_GID = S.SOURCE_LOCATION_GID --INNER JOIN
            --REGION_DETAIL RD ON RD.LOCATION_GID = L.LOCATION_GID
        WHERE RO.RATE_OFFERING_GID = 'NBL/MX.TMTY_DEDICADOS'--LIKE '%DEDICADOS%'
        AND RG.IS_ACTIVE = 'Y'
        AND TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01'
        --AND TO_CHAR(RD.INSERT_DATE, 'YYYY-MM-DD') > '2023-01-01'
        --AND REGEXP_LIKE(RD.REGION_GID,'(^|[^|])[|]([^|]|$)')
        --GROUP BY S.RATE_OFFERING_GID, L.LOCATION_NAME, RD.REGION_GID
        ORDER BY L.LOCATION_NAME

) A LOCATION L2 ON L2.LOCATION_GID = S.DEST_LOCATION_GID INNER JOIN
    REGION_DETAIL RD2 ON RD2.LOCATION_GID = L2.LOCATION_GID 

    AND TO_CHAR(RD2.INSERT_DATE, 'YYYY-MM-DD') > '2023-01-01'
            AND REGEXP_LIKE(RD2.REGION_GID,'(^|[^|])[|]([^|]|$)')
                    AND RD2.REGION_GID NOT LIKE '%FORANEO%'


SELECT S.RATE_OFFERING_GID, RD.REGION_GID
FROM SHIPMENT S INNER JOIN
        RATE_GEO RG ON S.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
        RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID INNER JOIN
        LOCATION L ON L.LOCATION_GID = S.DEST_LOCATION_GID INNER JOIN
        REGION_DETAIL RD ON RD.LOCATION_GID = L.LOCATION_GID
WHERE RO.RATE_OFFERING_GID LIKE '%DEDICADOS%'
AND RG.IS_ACTIVE = 'Y'
AND TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01'
--AND TO_CHAR(RD.INSERT_DATE, 'YYYY-MM-DD') > '2023-01-01'
AND REGEXP_LIKE(RD.REGION_GID,'(^|[^|])[|]([^|]|$)')
GROUP BY S.RATE_OFFERING_GID, RD.REGION_GID
ORDER BY S.RATE_OFFERING_GID, RD.REGION_GID



SELECT S.RATE_OFFERING_GID, RG.X_LANE_GID
FROM SHIPMENT S INNER JOIN
        RATE_GEO RG ON S.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
        RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID
WHERE RO.RATE_OFFERING_GID = 'NBL/MX.TMTY_DEDICADOS'--LIKE '%DEDICADOS%'
AND RG.IS_ACTIVE = 'Y'
AND TO_CHAR(S.START_TIME, 'YYYY-MM-DD') > '2025-01-01'


SELECT RG.X_LANE_GID
FROM RATE_GEO RG INNER JOIN
        RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID
WHERE RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
GROUP BY RG.X_LANE_GID
ORDER BY RG.X_LANE_GID

--AND RO.RATE_OFFERING_GID = 'NBL/MX.TMTY_DEDICADOS'--LIKE '%DEDICADOS%'

SELECT RD.REGION_GID, L.LOCATION_GID, L.CITY
FROM REGION_DETAIL RD INNER JOIN
        LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RD.REGION_GID LIKE '%FORANEO%'
ORDER BY L.CITY


SELECT RD.REGION_GID, L.LOCATION_GID, L.CITY
FROM REGION_DETAIL RD INNER JOIN
        LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RD.REGION_GID LIKE 'NBL/MX.MTY|NUEVO%'
ORDER BY L.CITY