DROP TABLE DISTANCE_RATES;

DROP TABLE LOCATION_REGIONS;

DROP TABLE OTM_LOC_RATES_DISTANCE;

TRUNCATE TABLE RATES;

--Tabla agrupada
CREATE TABLE LOCATION_REGIONS
AS (
        SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
        DEST_OTM_LOCATION_GID, DEST_REGION_GID, REG_SOUR, REG_DEST, DEST_OTM_PROVINCE_CODE, DEST_OTM_LOCATION_NAME
        FROM (
                SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
                     DEST_OTM_LOCATION_GID, DEST_REGION_GID, SUBSTR(SOUR_REGION_GID, 5, 3) REG_SOUR,
                     SUBSTR(DEST_REGION_GID, 8, 3) REG_DEST, DEST_OTM_PROVINCE_CODE, DEST_OTM_LOCATION_NAME
                FROM (
                           SELECT DIS.ID,
                           DIS.SOURCE_LOCATION_XID,
                           DIS.OTM_SOUR_LOCATION_GID,
                           CASE DIS.OTM_SOUR_LOCATION_GID
                               WHEN 'NBL.ORG-3767-152492' THEN 'NBL.3TJ_SHIPPING_REGION'
                               WHEN 'NBL.ORG-4729-194868' THEN 'NBL.3MX_SHIPPING_REGION'
                               WHEN 'NBL.ORG-5272-219663' THEN 'NBL.3GD_SHIPPING_REGION'
                               WHEN 'NBL.ORG-1894-94008' THEN 'NBL.MXC_SHIPPING_REGION'
                               WHEN 'NBL.ORG-4769-195887' THEN 'NBL.MTY_SHIPPING_REGION'
                               WHEN 'NBL.ORG-2024-98884' THEN 'NBL.MTY_SHIPPING_REGION'
                               END        SOUR_REGION_GID,
                           DIS.DESTINATION_LOCATION_XID,
                           DIS.DEST_OTM_LOCATION_GID,
                           REG.REGION_GID DEST_REGION_GID,
                           DEST_OTM_PROVINCE_CODE,
                           DEST_OTM_LOCATION_NAME
                    FROM DISTANCE_RC_OTM DIS INNER JOIN
                         REGION_DETAIL REG ON DIS.DEST_OTM_LOCATION_GID = REG.LOCATION_GID
                    )
              GROUP BY ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
                       DEST_OTM_LOCATION_GID, DEST_REGION_GID, DEST_OTM_PROVINCE_CODE, DEST_OTM_LOCATION_NAME
              )
        WHERE REG_SOUR = REG_DEST
        --ORDER BY ID
    )
;


--------------Query tabla agrupada--------------------------------------------------------------------------------------
SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
        DEST_OTM_LOCATION_GID, DEST_REGION_GID, REG_SOUR, REG_DEST
        FROM (
                SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
                     DEST_OTM_LOCATION_GID, DEST_REGION_GID, SUBSTR(SOUR_REGION_GID, 5, 3) REG_SOUR,
                     SUBSTR(DEST_REGION_GID, 8, 3) REG_DEST
                FROM (
                           SELECT DIS.ID,
                           DIS.SOURCE_LOCATION_XID,
                           DIS.OTM_SOUR_LOCATION_GID,
                           CASE DIS.OTM_SOUR_LOCATION_GID
                               WHEN 'NBL.ORG-3767-152492' THEN 'NBL.3TJ_SHIPPING_REGION'
                               WHEN 'NBL.ORG-4729-194868' THEN 'NBL.3MX_SHIPPING_REGION'
                               WHEN 'NBL.ORG-5272-219663' THEN 'NBL.3GD_SHIPPING_REGION'
                               WHEN 'NBL.ORG-1894-94008' THEN 'NBL.MXC_SHIPPING_REGION'
                               WHEN 'NBL.ORG-4769-195887' THEN 'NBL.MTY_SHIPPING_REGION'
                               WHEN 'NBL.ORG-2024-98884' THEN 'NBL.MTY_SHIPPING_REGION'
                               END        SOUR_REGION_GID,
                           DIS.DESTINATION_LOCATION_XID,
                           DIS.DEST_OTM_LOCATION_GID,
                           REG.REGION_GID DEST_REGION_GID
                    FROM DISTANCE_RC_OTM DIS INNER JOIN
                         REGION_DETAIL REG ON DIS.DEST_OTM_LOCATION_GID = REG.LOCATION_GID
                    WHERE DEST_OTM_LOCATION_GID = 'NBL.CUS-1034553-126282'
                    )
              GROUP BY ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
                       DEST_OTM_LOCATION_GID, DEST_REGION_GID
              )
        WHERE REG_SOUR = REG_DEST
        ORDER BY ID;

----Tabla nueva con Locations Regions / Lanes
CREATE TABLE DISTANCE_RATES
AS (
    SELECT *
    FROM (SELECT LAN.ID,
                 LAN.SOURCE_LOCATION_XID,
                 SOURCE_LATITUDE,
                 SOURCE_LONGITUD,
                 LAN.OTM_SOUR_LOCATION_GID,
                 OTM_SOUR_LOCATION_NAME,
                 OTM_SOUR_CITY,
                 OTM_SOUR_PROVINCE,
                 OTM_SOUR_PROVINCE_CODE,
                 OTM_SOUR_POSTAL_CODE,
                 OTM_SOUR_COUNTRY_CODE3_GID,
                 OTM_SOUR_LAT,
                 OTM_SOUR_LON,
                 LAN.DESTINATION_LOCATION_XID,
                 DESTINATION_LOCATION_NAME,
                 DESTINATION_LATITUDE,
                 DESTINATION_LONGITUD,
                 LAN.DEST_OTM_LOCATION_GID,
                 DEST_OTM_LOCATION_NAME,
                 DEST_OTM_CITY,
                 DEST_OTM_PROVINCE,
                 LAN.DEST_OTM_PROVINCE_CODE,
                 DEST_OTM_POSTAL_CODE,
                 DEST_OTM_COUNTRY_CODE3_GID,
                 DEST_OTM_LAT,
                 DEST_OTM_LON,
                 DISTANCE_KM,
                 SOUR_REGION_GID,
                 DEST_REGION_GID,
                 X_LANE_GID,
                 X_LANE_XID
          FROM (
                       SELECT REGS.ID,
                       REGS.SOURCE_LOCATION_XID,
                       REGS.OTM_SOUR_LOCATION_GID,
                       REGS.SOUR_REGION_GID,
                       REGS.DESTINATION_LOCATION_XID,
                       REGS.DEST_OTM_LOCATION_GID,
                       REGS.DEST_REGION_GID,
                       LANES.X_LANE_GID,
                       LANES.X_LANE_XID,
                       REGS.DEST_OTM_PROVINCE_CODE
                       FROM LOCATION_REGIONS REGS INNER JOIN
                            X_LANES LANES ON LANES.SOURCE_REGION_GID = REGS.SOUR_REGION_GID AND LANES.DEST_REGION_GID = REGS.DEST_REGION_GID
                       ORDER BY REGS.ID
                ) LAN INNER JOIN
                  DISTANCE_RC_OTM DIS ON DIS.ID = LAN.ID
          ) TOD INNER JOIN
         RATES R ON R.SOURCE_REGION_GID = TOD.SOUR_REGION_GID AND R.DESTINATION_REGION_GID = TOD.DEST_REGION_GID
        WHERE R.RATE_RECORD_GID LIKE '%24%'
    )
;


---Validacion de registros de LocationsRegions que no hicieron match
SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID,
       SOUR_REGION_GID, DESTINATION_LOCATION_XID,
       DEST_OTM_LOCATION_GID, DEST_REGION_GID
FROM LOCATION_REGIONS
WHERE ID NOT IN (
                    SELECT REGS.ID
                    FROM LOCATION_REGIONS REGS INNER JOIN
                        X_LANES LANES ON LANES.SOURCE_REGION_GID = REGS.SOUR_REGION_GID
                                     AND LANES.DEST_REGION_GID = REGS.DEST_REGION_GID
        )
--AND SOUR_REGION_GID = 'NBL.MTY_SHIPPING_REGION'
GROUP BY ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID,
         DESTINATION_LOCATION_XID, DEST_OTM_LOCATION_GID, DEST_REGION_GID
ORDER BY ID;

--------------Pivote----------------------------------------------------------------------------------------------------
SELECT  '''' || RATE_OFFERING_GID || '''' || ',', RATES
FROM (SELECT SUBSTR(RATE_OFFERING_GID, 8, LENGTH(RATE_OFFERING_GID) - 7) RATE_OFFERING_GID, COUNT(RATE_RECORD_GID) RATES
      /*ID,
       SOURCE_LOCATION_XID,
       --SOURCE_LATITUDE,
       --SOURCE_LONGITUD,
       --OTM_SOUR_LOCATION_GID,
       OTM_SOUR_LOCATION_NAME,
       --OTM_SOUR_CITY,
       --OTM_SOUR_PROVINCE,
       --OTM_SOUR_PROVINCE_CODE,
       --OTM_SOUR_POSTAL_CODE,
       --OTM_SOUR_COUNTRY_CODE3_GID,
       --OTM_SOUR_LAT,
       --OTM_SOUR_LON,
       DESTINATION_LOCATION_XID,
       --DESTINATION_LOCATION_NAME,
       --DESTINATION_LATITUDE,
       --DESTINATION_LONGITUD,
       --DEST_OTM_LOCATION_GID,
       --DEST_OTM_LOCATION_NAME,
       --DEST_OTM_CITY,
       --DEST_OTM_PROVINCE,
       --DEST_OTM_PROVINCE_CODE,
       --DEST_OTM_POSTAL_CODE,
       --DEST_OTM_COUNTRY_CODE3_GID,
       --DEST_OTM_LAT,
       --DEST_OTM_LON,
       DISTANCE_KM,
       SOUR_REGION_GID,
       DEST_REGION_GID,
       X_LANE_GID,
       X_LANE_XID,
       RATE_RECORD_GID,
       RATE_OFFERING_GID,
       LANE_GID,
       --SOURCE_REGION_GID,
       --DESTINATION_REGION_GID,
       --"Cost Parameter ID",
       --BASIS,
       AMOUNT,
       CURRENCY
     */
      FROM DISTANCE_RATES
--WHERE X_LANE_XID = 'MXC|MXC|LEON'
      GROUP BY RATE_OFFERING_GID--, RATE_RECORD_GID
     ) R
ORDER BY RATES DESC
;


-----------------------------Final-----------------------------------------------
CREATE TABLE OTM_LOC_RATES_DISTANCE
AS (
    SELECT *
        FROM (SELECT SOUR_REGION_GID,
             --DEST_REGION_GID,
             RATE_OFFERING_GID,
             X_LANE_XID,
             --LANE_GID,
             --RATE_RECORD_GID,
             DESTINATION_LOCATION_XID,
             AMOUNT,
             --CURRENCY
            DISTANCE_KM,
            DEST_OTM_PROVINCE_CODE,
            DESTINATION_LOCATION_NAME
      FROM (SELECT --ID,
                   --SOURCE_LOCATION_XID,
                   --OTM_SOUR_LOCATION_NAME,
                   SOUR_REGION_GID,
                   DESTINATION_LOCATION_XID,
                   DISTANCE_KM,
                   --DEST_REGION_GID,
                   --X_LANE_GID,
                   X_LANE_XID,
                   RATE_RECORD_GID,
                   SUBSTR(RATE_OFFERING_GID, 8, LENGTH(RATE_OFFERING_GID) - 7) RATE_OFFERING_GID,
                   --LANE_GID,
                   AMOUNT,
                   --CURRENCY
                   DEST_OTM_PROVINCE_CODE,
                   DESTINATION_LOCATION_NAME
            FROM DISTANCE_RATES
            --WHERE DESTINATION_LOCATION_XID = 'CUS-1175678-185552'
            --WHERE X_LANE_XID = 'MXC|MXC|LEON'
          )
      )
    PIVOT
    (
        MAX(AMOUNT) --COUNT_AMOUNT, MIN(AMOUNT) RATE
        FOR RATE_OFFERING_GID IN ('FEMSA' SOLISTICA,'CASTORES' CASTORES,'TRESGUERRAS' TRESGUERRAS,'TMS' TMS,'MEXAMERIK' MEXAMERIK,'TMTY' TMTY,'RFL' RFL,'DANIEL_MARTINEZ' DANIEL_MARTINEZ,
                                  'TRATELOGISTICA' TRATELOGISTICA,'PROTRANSPORT' PROTRANSPORT,'ESJ' ESJ,'TEVIAN' TEVIAN,'TUMSA' TUMSA,'EATI' EATI,'FSN' FSN,'ANDRADE' ANDRADE,'SILVESTRE' SILVESTRE,
                                  'GLP' GLP,'TAMEZ' TAMEZ,'READY_SOLUTIONS' READY_SOLUTIONS, 'SUPERTRACK' SUPERTRACK,'SETVAC' SETVAC,'GRS' GRS,'FBR' FBR,'ARACELY' ARACELY,'PRISA' PRISA,
                                  'NUEVOMEX' NUEVOMEX,'SHIPZO' SHIPZO,'FLETES' FLETES,'TEM' TEM,'RGT' RGT,'TRACUSA' TRACUSA,'KARESAN' KARESAN,'CORONA' CORONA,'TAMP' TAMP,'CARSOLIO' CARSOLIO,
                                  'ORIENTE' ORIENTE,'GASTELUM' GASTELUM,'SYS COORDINACION' SYS_COORDINACION,'ALGEZA' ALGEZA,'LARMEX' LARMEX,'A3V' A3V,'BKHL' BKHL,'PELM' PELM,'RGC' RGC,
                                  'LOZANO' LOZANO,'ADACNOM' ADACNOM,'NIETO' NIETO)
    )
    --ORDER BY SOUR_REGION_GID, X_LANE_XID, DESTINATION_LOCATION_XID, DISTANCE_KM
)
;

SELECT SOUR_REGION_GID,
       X_LANE_XID,
       DESTINATION_LOCATION_XID,
       DEST_OTM_PROVINCE_CODE,
       DESTINATION_LOCATION_NAME,
       DISTANCE_KM,
       SOLISTICA, CASTORES,
       TRESGUERRAS, TMS,
       MEXAMERIK, TMTY,
       RFL, DANIEL_MARTINEZ,
       TRATELOGISTICA, PROTRANSPORT,
       ESJ, TEVIAN,
       TUMSA, EATI,
       FSN, ANDRADE,
       SILVESTRE, GLP,
       TAMEZ, READY_SOLUTIONS,
       SUPERTRACK, SETVAC,
       GRS, FBR,
       ARACELY, PRISA,
       NUEVOMEX, SHIPZO,
       FLETES, TEM,
       RGT, TRACUSA,
       KARESAN, CORONA,
       TAMP, CARSOLIO,
       ORIENTE, GASTELUM,
       SYS_COORDINACION, ALGEZA,
       LARMEX, A3V,
       BKHL, PELM,
       RGC, LOZANO,
       ADACNOM, NIETO
FROM OTM_LOC_RATES_DISTANCE
ORDER BY SOUR_REGION_GID, X_LANE_XID, DESTINATION_LOCATION_XID, DISTANCE_KM;
--------------------------------------------------------------------------------
/*
'FEMSA','CASTORES','TRESGUERRAS','TMS','MEXAMERIK','TMTY','RFL','DANIEL_MARTINEZ'
'TRATELOGISTICA','PROTRANSPORT','ESJ','TEVIAN','TUMSA','EATI','FSN','ANDRADE','SILVESTRE','GLP','TAMEZ','READY_SOLUTIONS',
'SUPERTRACK','SETVAC','GRS','FBR','ARACELY','PRISA','NUEVOMEX','SHIPZO','FLETES','TEM','RGT','TRACUSA','KARESAN',
'CORONA','TAMP','CARSOLIO','ORIENTE','GASTELUM','SYS COORDINACION','ALGEZA','LARMEX','A3V','BKHL','PELM','RGC',
'LOZANO','ADACNOM','MONCADA','NIETO'
*/
----------------Alternativa de pivote-------------------------------------------
SELECT *
FROM (SELECT SOUR_REGION_GID,
             DESTINATION_LOCATION_XID,
             DISTANCE_KM,
                 CASE RATE_OFFERING_GID WHEN 'TMS' THEN AMOUNT END TMS,
        CASE RATE_OFFERING_GID WHEN 'TRESGUERRAS' THEN AMOUNT END TRESGUERRAS,
        CASE RATE_OFFERING_GID WHEN 'CASTORES' THEN AMOUNT END CASTORES,
        CASE RATE_OFFERING_GID WHEN 'MEXAMERIK' THEN AMOUNT END MEXAMERIK,
        CASE RATE_OFFERING_GID WHEN 'FEMSA' THEN AMOUNT END FEMSA,
        CASE RATE_OFFERING_GID WHEN 'DANIEL_MARTINEZ' THEN AMOUNT END DANIEL_MARTINEZ,
        CASE RATE_OFFERING_GID WHEN 'SETVAC' THEN AMOUNT END SETVAC,
        CASE RATE_OFFERING_GID WHEN 'TUMSA' THEN AMOUNT END TUMSA
      --Min(Case AMOUNT When 'MiddleName' Then Data End) MiddleName,
      --Min(Case AMOUNT When 'LastName' Then Data End) LastName,
      --Min(Case AMOUNT When 'Date' Then Data End) Date
      FROM (
          SELECT SOUR_REGION_GID,
          --DEST_REGION_GID,
          RATE_OFFERING_GID, X_LANE_XID,
          --LANE_GID,
          RATE_RECORD_GID, DESTINATION_LOCATION_XID, AMOUNT,
          --CURRENCY
          DISTANCE_KM
          FROM (
          SELECT --ID,
          --SOURCE_LOCATION_XID,
          --OTM_SOUR_LOCATION_NAME,
          SOUR_REGION_GID, DESTINATION_LOCATION_XID, DISTANCE_KM,
          --DEST_REGION_GID,
          --X_LANE_GID,
          X_LANE_XID, RATE_RECORD_GID, SUBSTR(RATE_OFFERING_GID, 8, LENGTH(RATE_OFFERING_GID) - 7) RATE_OFFERING_GID,
          --LANE_GID,
          AMOUNT--,
          --CURRENCY
          FROM DISTANCE_RATES
          WHERE X_LANE_XID = 'MXC|MXC|LEON'
          )
          )
      --GROUP BY SOUR_REGION_GID, DESTINATION_LOCATION_XID, AMOUNT
      ORDER BY SOUR_REGION_GID, DESTINATION_LOCATION_XID)
;


------------------------------------------------------------------------------------------------------------------------

--Tabla Original de Carga Join RC with OTM
SELECT ID, SOURCE_LOCATION_XID, SOURCE_LATITUDE, SOURCE_LONGITUD, OTM_SOUR_LOCATION_GID, OTM_SOUR_LOCATION_NAME, OTM_SOUR_CITY, OTM_SOUR_PROVINCE,
       OTM_SOUR_PROVINCE_CODE, OTM_SOUR_POSTAL_CODE, OTM_SOUR_COUNTRY_CODE3_GID, OTM_SOUR_LAT, OTM_SOUR_LON, DESTINATION_LOCATION_XID,
       DESTINATION_LOCATION_NAME, DESTINATION_LATITUDE, DESTINATION_LONGITUD, DEST_OTM_LOCATION_GID, DEST_OTM_LOCATION_NAME, DEST_OTM_CITY,
       DEST_OTM_PROVINCE, DEST_OTM_PROVINCE_CODE, DEST_OTM_POSTAL_CODE, DEST_OTM_COUNTRY_CODE3_GID, DEST_OTM_LAT, DEST_OTM_LON, DISTANCE_KM
FROM DISTANCE_RC_OTM
;

--Join con Regions
SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
       DEST_OTM_LOCATION_GID, DEST_REGION_GID,REG_SOUR, REG_DEST
FROM (
        SELECT ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, SOUR_REGION_GID, DESTINATION_LOCATION_XID,
            DEST_OTM_LOCATION_GID, DEST_REGION_GID,
            SUBSTR(SOUR_REGION_GID, 5,3) REG_SOUR, SUBSTR(DEST_REGION_GID, 8, 3) REG_DEST
        FROM LOCATION_REGIONS
        ORDER BY OTM_SOUR_LOCATION_GID
     )
WHERE REG_SOUR = REG_DEST
ORDER BY ID ASC
--AND SOURCE_LOCATION_XID = 'ORG-5272-219663'
;

---------Varios-------------------------------------------------------------------------------------------------------
SELECT DESTINATION_REGION_GID
FROM RATES
WHERE DESTINATION_REGION_GID LIKE '%MXC%'
GROUP BY DESTINATION_REGION_GID
ORDER BY DESTINATION_REGION_GID;

SELECT *
FROM RATES
WHERE RATE_RECORD_GID LIKE '%24%'
and RATE_OFFERING_GID = 'NBL/MX.TEM';

SELECT *
FROM RATES;
--WHERE LANE_GID LIKE '%MXC|MXC TEM GUSTAVO A%'
--WHERE RATE_RECORD_GID LIKE '%24%'
WHERE RATE_OFFERING_GID = 'NBL/MX.TEM'
;

SELECT *
FROM RATES
WHERE LANE_GID = 'NBL/MX.MXC|MXC TEM GUSTAVO A';

----REGION
SELECT *
FROM REGION_DETAIL
WHERE REGION_XID LIKE '%CHALCO%';

SELECT *
FROM LOCATION_REGIONS
WHERE DEST_OTM_LOCATION_GID  = 'NBL.CUS-1175678-185552';
WHERE DEST_REGION_GID LIKE '%MXC%';

SELECT *
FROM X_LANES
WHERE X_LANE_XID LIKE '%MXC|MXC CORONA GUSTAVO A%';

SELECT * --ID, SOURCE_LOCATION_XID, OTM_SOUR_LOCATION_GID, DESTINATION_LOCATION_XID, DEST_OTM_LOCATION_GID, DISTANCE_KM
FROM DISTANCE_RC_OTM
WHERE ID = 677;

SELECT *
FROM DISTANCE_RC_OTM
where DEST_OTM_CITY like '%CUAJI%';


SELECT * FROM ADMIN.REGION_DETAIL
WHERE LOCATION_GID = 'NBL.CUS-1175678-185552';

-------DELETE from REGION_DETAIL
DELETE FROM ADMIN.REGION_DETAIL WHERE ADMIN.REGION_DETAIL.REGION_GID = 'NBL/MX.MTY|CDMX ZONAMETRO'
AND ADMIN.REGION_DETAIL.LOCATION_GID = 'NBL.CUS-1034553-105323';

DELETE FROM X_LANES WHERE X_LANE_XID IN
                          (
'MXC|MXC ALMARAZ GUSTAVO A',
'MXC|MXC ANDRADE CHALCO',
'MXC|MXC ANDRADE CUAUTITLAN',
'MXC|MXC ANDRADE GUSTAVO A',
'MXC|MXC CASTORES CUAUTITLAN',
'MXC|MXC CORONA CHALCO',
'MXC|MXC CORONA CUAUTITLAN',
'MXC|MXC CORONA GUSTAVO A',
'MXC|MXC DANIEL CHALCO',
'MXC|MXC DANIEL CUAUTITLAN',
'MXC|MXC DANIEL GUST A',
'MXC|MXC DEDICADOS TEM',
'MXC|MXC FEMSA CHALCO',
'MXC|MXC FEMSA CUAUTITLAN',
'MXC|MXC FEMSA GUSTAVO A',
'MXC|MXC MEGAREY CHALCO',
'MXC|MXC MEXAMERIK CHALCO',
'MXC|MXC MEXAMERIK CUAUTITLAN',
'MXC|MXC MEXAMERIK GUSTAVO A',
'MXC|MXC MONCADA CHALCO',
'MXC|MXC MONCADA CUAUTITLAN',
'MXC|MXC SAMSUNG CHALCO',
'MXC|MXC SAMSUNG CUAUTITLAN',
'MXC|MXC TEM CHALCO',
'MXC|MXC TEM CUAUTITLAN',
'MXC|MXC TEM GUSTAVO A',
'MXC|MXC CORONA GUSTAVO A');

SELECT * FROM X_LANES
WHERE X_LANE_XID IN
(
'MXC|MXC ALMARAZ GUSTAVO A',
'MXC|MXC ANDRADE CHALCO',
'MXC|MXC ANDRADE CUAUTITLAN',
'MXC|MXC ANDRADE GUSTAVO A',
'MXC|MXC CASTORES CUAUTITLAN',
'MXC|MXC CORONA CHALCO',
'MXC|MXC CORONA CUAUTITLAN',
'MXC|MXC CORONA GUSTAVO A',
'MXC|MXC DANIEL CHALCO',
'MXC|MXC DANIEL CUAUTITLAN',
'MXC|MXC DANIEL GUST A',
'MXC|MXC DEDICADOS TEM',
'MXC|MXC FEMSA CHALCO',
'MXC|MXC FEMSA CUAUTITLAN',
'MXC|MXC FEMSA GUSTAVO A',
'MXC|MXC MEGAREY CHALCO',
'MXC|MXC MEXAMERIK CHALCO',
'MXC|MXC MEXAMERIK CUAUTITLAN',
'MXC|MXC MEXAMERIK GUSTAVO A',
'MXC|MXC MONCADA CHALCO',
'MXC|MXC MONCADA CUAUTITLAN',
'MXC|MXC SAMSUNG CHALCO',
'MXC|MXC SAMSUNG CUAUTITLAN',
'MXC|MXC TEM CHALCO',
'MXC|MXC TEM CUAUTITLAN',
'MXC|MXC TEM GUSTAVO A',
'MXC|MXC CORONA GUSTAVO A')
  ;


------------------Update Lat/Lon

SELECT * FROM (
    SELECT * FROM (
        SELECT OTM.LOCATION_GID, OTM.LOCATION_XID, OTM.LOCATION_NAME, OTM.LAT, OTM.LON,
        --RC.DESTINATION_LOCATION_XID, 
        TRUNC(RC.DESTINATION_LATITUDE, 5) RC_LAT, 
        --TO_CHAR(DESTINATION_LATITUDE, '9999.99999') RC_LAT, 
        TRUNC(RC.DESTINATION_LONGITUD, 5) RC_LON
        --TO_CHAR(DESTINATION_LONGITUD, '9999.99999') RC_LON
        --OTM.ADDRESS_VALIDATION_EDE
        FROM LOCATION_OTM_25 OTM INNER JOIN 
        DISTANCE_BY_LOCATION_LOCATION RC ON OTM.LOCATION_XID = RC.DESTINATION_LOCATION_XID
        WHERE OTM.DOMAIN_NAME = 'NBL'
    )
    WHERE LAT <> RC_LAT OR LON <> RC_LON
)
GROUP BY LOCATION_GID, LOCATION_XID, LOCATION_NAME, LAT, LON, RC_LAT, RC_LON
ORDER BY LOCATION_GID;

SELECT * FROM LOCATION_OTM_25
WHERE DOMAIN_NAME = 'NBL';

SELECT * --DESTINATION_LONGITUD,TRUNC(DESTINATION_LONGITUD,5), TO_CHAR(DESTINATION_LONGITUD, 'FM999999999999999.00000')--, regexp_like(DESTINATION_LONGITUD,'^[0-9].[0-9]+$')
FROM DISTANCE_BY_LOCATION_LOCATION
WHERE DESTINATION_LOCATION_XID = 'CUS-1034553-196527';


SELECT LOCATION_GID, LOCATION_XID, LAT, LON, COUNTRY_CODE3_GID FROM LOCATION WHERE LOCATION_GID = 'NBL.CUS-1034553-103013' AND COUNTRY_CODE3_GID = 'MEX' AND LOCATION_XID LIKE 'CUS%'
SELECT * FROM LOCATION WHERE COUNTRY_CODE3_GID = 'MEX' AND LOCATION_XID LIKE 'CUS%'