ALTER SESSION SET CURRENT_SCHEMA = MXC_WMS;

SELECT A.ASN_ID, A.REF_FIELD_1 PROD_LINE, A.REF_FIELD_2 BATCH_NBR, IFMW.SLOT_MISC_1, IC.ITEM_NAME, IC.DESCRIPTION, A.REF_FIELD_4, A.REF_FIELD_3
--INTO V_PROD_LINE, V_BATCH_NBR, V_ITEM_ID, V_ITEM_NAME, V_ITEM_DESCRIPTION, V_SHIPPED_QTY, V_JOB_NBR
FROM ASN A, ASN_DETAIL AD, ITEM_CBO IC, ITEM_FACILITY_MAPPING_WMS IFMW
WHERE IC.ITEM_ID = AD.SKU_ID 
AND A.ASN_ID = AD.ASN_ID 
AND A.ASN_ID = '297071'--V_ASN_ID 
AND IFMW.ITEM_ID = IC.ITEM_ID
--AND IC.ITEM_NAME = 'FNG100370'
--AND A.REF_FIELD_2 = 'MXC1070'
ORDER BY A.ASN_ID
;

--Original query
SELECT A.ASN_ID, A.REF_FIELD_1 PROD_LINE, A.REF_FIELD_2 BATCH_NBR, IFMW.SLOT_MISC_1, IC.ITEM_NAME,
IC.DESCRIPTION, A.REF_FIELD_4, A.REF_FIELD_3
--INTO V_PROD_LINE, V_BATCH_NBR, V_ITEM_ID, V_ITEM_NAME, V_ITEM_DESCRIPTION, V_SHIPPED_QTY, V_JOB_NBR
FROM ASN A, ASN_DETAIL AD, ITEM_CBO IC, ITEM_FACILITY_MAPPING_WMS IFMW
WHERE IC.ITEM_ID = AD.SKU_ID 
AND A.ASN_ID = AD.ASN_ID 
AND A.ASN_ID = '297071'--V_ASN_ID 
AND IFMW.ITEM_ID = IC.ITEM_ID
ORDER BY A.ASN_ID
;

SELECT *
FROM ASN
WHERE ASN_ID = '297071'
;

SELECT * FROM ITEM_CBO
WHERE ITEM_NAME = 'FNG100370';

--Por que se repitio
SELECT *
FROM ITEM_FACILITY_MAPPING_WMS
WHERE ITEM_ID = '50068'
;