SELECT SV.SERVPROV_XID, SV.SCAC_GID
/*S.SHIPMENT_GID,
    S.TRANSPORT_MODE_GID,
    S.TOTAL_ACTUAL_COST,
    S.TOTAL_ACTUAL_COST_BASE,
    S.T_ACTUAL_COST_CURRENCY_GID,
    S.LOADED_DISTANCE * 1.609344 LOADED_DISTANCE,
    'KM' LOADED_DISTANCE_UOM_CODE,
    S.SOURCE_LOCATION_GID,
    S.DEST_LOCATION_GID,
    S.START_TIME,
    S.END_TIME,
    S.SERVPROV_GID,
    S.RATE_OFFERING_GID,
    S.RATE_GEO_GID, */
FROM SHIPMENT S INNER JOIN 
SERVPROV SV ON SV.SERVPROV_GID = S.SERVPROV_GID 
WHERE TO_CHAR(S.START_TIME, 'YYYY-MM-DD') >= '2025-03-01' 
AND S.DOMAIN_NAME = 'NBL/MX' 
AND S.RATE_OFFERING_GID <> 'NBL/MX.CPU' 
GROUP BY SV.SERVPROV_XID, SV.SCAC_GID