SELECT *
FROM (
    SELECT OTM.LOCATION_XID, OTM.LOCATION_NAME, OTM.ADDRESS_VALIDATION_EDE, OTM.LAT || '/' || OTM.LON OTM_LAT_LON, ROUND(RC.LAT, 5) || '/' || ROUND(RC.LON, 5) RC_LAT_LON
    FROM LOCATION_OTM_25 OTM INNER JOIN
    RC_LOCATION RC ON RC.LOCATION_XID = OTM.LOCATION_XID
    GROUP BY OTM.LOCATION_XID, OTM.LOCATION_NAME, OTM.ADDRESS_VALIDATION_EDE, OTM.LAT, OTM.LON, RC.LAT, RC.LON
    ORDER BY OTM.LOCATION_XID
) T 
WHERE OTM_LAT_LON != RC_LAT_LON