SELECT RO.RATE_OFFERING_GID, RO.SERVPROV_GID 
FROM RATE_GEO RG INNER JOIN 
RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID 
WHERE 1 = 1 
AND RG.IS_ACTIVE = 'Y' 
AND RG.DOMAIN_NAME = 'NBL/MX' 
GROUP BY RO.RATE_OFFERING_GID, RO.SERVPROV_GID 