SELECT *
FROM (
SELECT * FROM LOCATION
WHERE LOCATION_XID IN (
SELECT LOCATION_XID 
FROM LOCATION
WHERE DOMAIN_NAME = 'NBL/MX'
AND COUNTRY_CODE3_GID = 'MEX'
AND (LOCATION_XID LIKE 'ORG%' OR LOCATION_XID LIKE 'CUS%'))
AND DOMAIN_NAME = 'NBL'
UNION ALL
SELECT * 
FROM LOCATION
WHERE DOMAIN_NAME = 'NBL/MX'
AND COUNTRY_CODE3_GID = 'MEX'
AND (LOCATION_XID LIKE 'ORG%' OR LOCATION_XID LIKE 'CUS%')
)
ORDER BY LOCATION_GID;



SELECT * FROM REGION_DETAIL
WHERE LOCATION_GID IN (
                        SELECT LOCATION_GID 
                        FROM LOCATION
                        WHERE DOMAIN_NAME = 'NBL/MX'
                        AND COUNTRY_CODE3_GID = 'MEX'
                        AND (LOCATION_XID LIKE 'ORG%' OR LOCATION_XID LIKE 'CUS%')
                        );


SELECT * FROM 
RATE_OFFERING RO INNER JOIN 
SERVPROV SER ON SER.SERVPROV_GID = RO.SERVPROV_GID
WHERE RO.IS_ACTIVE = 'Y'
--AND RO.DOMAIN_NAME = 'NBL/MX'
AND SER.DOMAIN_NAME = 'NBL/MX';


