 
SELECT 
SH.SHIPMENT_GID,
SH.SHIPMENT_XID,  
--REFNUM (Customer PO) -- SHIPMENT_REFNUM_QUAL_GID // CUST_PO
--SOURCE LOCATION NAME -- LOCATION // LOCATION_NAME
--REFNUM (Delivery Number) -- SHIPMENT_REFNUM_QUAL_GID // NBL.OR_GROUP
SH.INDICATOR,
SH.USER_DEFINED1_ICON_GID SHIP_CONFIRMED, --  // NBL.SHIP_CONFIRMED
--REMARK (label.ShipDate) -- REMARK_QUAL_GID// SHIP_DATE
--REMARK (Pickup Appointment) -- REMARK_QUAL_GID// NBL.PU_APPOINTMENT
--REMARK (Delivery Appointment) -- REMARK_QUAL_GID// NBL.DELIVERY_STOP_2
SH.LOCATION_GID AS "Destination Location Name", -- LOCATION // LOCATION_NAME
--Service Provider Name -- SERVPROV/LOCATION // LOCATION_NAME
--Status Value (WMS_STATUS) -- STATUS_TYPE_GID // NBL/MX.WMS_STATUS
--Start Time // START_TIME
--REFNUM (Preload) -- SHIPMENT_REFNUM_QUAL_GID // NBL.IS_PRELOAD
SH.ATTRIBUTE3 AS "Trailer Number",
--REFNUM (CPU_CONTACT) -- SHIPMENT_REFNUM_QUAL_GID // NBL.CPU_CONTACT
--Source Location ID // SOURCE_LOCATION_GID
--REFNUM (EBS Sales Order) -- SHIPMENT_REFNUM_QUAL_GID // SO_NUM
SH.DEST_LOCATION_GID AS "Destination Location ID",
--Destination City -- LOCATION // CITY
--Destination Province Code -- LOCATION // PROVINCE_CODE
SH.ATTRIBUTE2 DTS_LOCATION_TYPE,
SH.USER_DEFINED4_ICON_GID SPOT,
SH.RATE_GEO_GID AS "Rate Record ID",
--REFNUM (Base Cost) -- SHIPMENT_REFNUM_QUAL_GID // NBL.BASE_COST
SH.TOTAL_ACTUAL_COST AS "Total Actual Cost",
SH.ORIGINAL_INVOICE_COST AS "Original Invoice Cost",
SH.TOTAL_MATCHED_INVOICE_COST AS "Total Matched Invoice Cost",
SH.TOTAL_APPROVED_COST AS "Total Approved Cost",
SH.TOTAL_WEIGHT AS "Total Gross Weight",
--REFNUM (Total Pallets) -- SHIPMENT_REFNUM_QUAL_GID // NBL.TOTAL_PALLET
SH.LOADED_DISTANCE AS "Loaded Distance",
--Status Value (HOLD_STATUS) -- SHIPMENT_REFNUM_QUAL_GID // NBL/MX.TENDER_HOLD
--Status Value (label.spot_bid_tender) -- SHIPMENT_REFNUM_QUAL_GID // NBL/MX.TENDER_SPOT_BID
SH.INSERT_USER AS "Insert User",
SH.INSERT_DATE AS "Insert Time",
SH.UPDATE_USER AS "Update User",
SH.UPDATE_DATE  AS "Last Update Time",
--REFNUM (Original Req Date) -- SHIPMENT_REFNUM_QUAL_GID // NBL.ORIGINAL_REQUEST_DATE
SH.PLANNED_TRANSPORT_MODE_GID AS Mode,
--REFNUM (QTY_MOD) -- SHIPMENT_REFNUM_QUAL_GID // NBL.QTY_MOD
SH.USER_DEFINED2_ICON_GID AS "PICKUP APPT SCHEDULED", --//NBL.FK_SCHEDULED_APPOINTMENT  
SH.USER_DEFINED3_ICON_GID AS "DELIVERY APPT SCHEDULED", --  //NBL.FK_SCHEDULED_APPOINTMENT
SH.USER_DEFINED5_ICON_GID APPT_NEEDED,
SH.NUM_STOPS STOPS, 
--Refnum Value (Refnum Qual ID:CUS_LOAD_REF) Load Reference -- SHIPMENT_REFNUM_QUAL_GID // NBL.CUS_LOAD_REF
--REFNUM (Ref Value) -- SHIPMENT_REFNUM_QUAL_GID // NBL.REF_VALUE
TOTAL_ITEM_PACKAGE_COUNT AS "Total Item Package Count",
SH.DOMAIN_NAME AS "Domain Name",
--Status Value [Tier Status] -- SHIPMENT_REFNUM_QUAL_GID //NBL/MX.TIER
--Status Value (Secure Resources) -- SHIPMENT_REFNUM_QUAL_GID //NBL/MX.SECURE RESOURCES
SH.DROP_INVENTORY_PROCESSED AS "Drop Inventory Processed",
SH.ATTRIBUTE4 AS "Shipping Notes"
FROM SHIPMENT SH
WHERE SH.SHIPMENT_XID = 'MX51088246';
  
SHIPMENT_REMARK
SHIPMENT_REFNUM  
LOCATION

SERVPROV (LOC)
SHIPMENT_STATUS 



SELECT 
SH.SHIPMENT_GID,
SH.SHIPMENT_XID,  
--SR1.SHIPMENT_REFNUM_VALUE AS "Customer PO",
LISTAGG(SR1.SHIPMENT_REFNUM_VALUE, '|') WITHIN GROUP (ORDER BY SR1.SHIPMENT_REFNUM_VALUE) "Customer PO",
SL.LOCATION_NAME AS "SOURCE LOCATION NAME", 
SR2.SHIPMENT_REFNUM_VALUE AS "Delivery Number", 
SH.INDICATOR,
SH.USER_DEFINED1_ICON_GID AS "SHIP_CONFIRMED", 
SK1.REMARK_TEXT AS "SHIP_DATE",
SK2.REMARK_TEXT AS "Pickup Appointment", 
SK3.REMARK_TEXT AS "Delivery Appointment",
DL.LOCATION_NAME AS "Destination Location Name", 
SRV.LOCATION_NAME AS "Service Provider Name",  
ST.STATUS_VALUE_GID AS "WMS_STATUS",
SH.START_TIME AS "Start Time",
SR3.SHIPMENT_REFNUM_VALUE AS "Preload",
SH.ATTRIBUTE3 AS "Trailer Number",
SR4.SHIPMENT_REFNUM_VALUE AS "CPU_CONTACT",
SH.SOURCE_LOCATION_GID AS "Source Location ID",
SR5.SHIPMENT_REFNUM_VALUE AS "EBS Sales Order",
SH.DEST_LOCATION_GID AS "Destination Location ID",
DL.CITY AS "Destination City",
DL.PROVINCE_CODE AS "Destination Province Code",
SH.ATTRIBUTE2 AS DTS_LOCATION_TYPE,
SH.USER_DEFINED4_ICON_GID AS SPOT,
SH.RATE_GEO_GID AS "Rate Record ID",
SR6.SHIPMENT_REFNUM_VALUE AS "Base Cost", 
SH.TOTAL_ACTUAL_COST AS "Total Actual Cost",
SH.ORIGINAL_INVOICE_COST AS "Original Invoice Cost",
SH.TOT_MATCHED_INVOICE_COST AS "Total Matched Invoice Cost",
SH.TOTAL_APPROVED_COST AS "Total Approved Cost",
SH.TOTAL_WEIGHT AS "Total Gross Weight",
SR7.SHIPMENT_REFNUM_VALUE AS "Total Pallets",
SH.LOADED_DISTANCE AS "Loaded Distance",
SR8.SHIPMENT_REFNUM_VALUE AS "HOLD_STATUS",
SR9.SHIPMENT_REFNUM_VALUE AS "Spot BID Tender", 
SH.INSERT_USER AS "Insert User",
SH.INSERT_DATE AS "Insert Time",
SH.UPDATE_USER AS "Update User",
SH.UPDATE_DATE  AS "Last Update Time",
SR10.SHIPMENT_REFNUM_VALUE AS "Original Req Date", 
SH.PLANNED_TRANSPORT_MODE_GID AS "Mode",
SR11.SHIPMENT_REFNUM_VALUE AS "QTY_MOD", 
SH.USER_DEFINED2_ICON_GID AS "PICKUP APPT SCHEDULED",  
SH.USER_DEFINED3_ICON_GID AS "DELIVERY APPT SCHEDULED", 
SH.USER_DEFINED5_ICON_GID AS APPT_NEEDED,
SH.NUM_STOPS AS STOPS, 
SR12.SHIPMENT_REFNUM_VALUE AS "Load Reference", 
SR13.SHIPMENT_REFNUM_VALUE AS "Ref Value",
SH.TOTAL_ITEM_PACKAGE_COUNT AS "Total Item Package Count",
SH.DOMAIN_NAME AS "Domain Name",
SR14.SHIPMENT_REFNUM_VALUE AS "Tier Status", 
SR15.SHIPMENT_REFNUM_VALUE AS "Secure Resources", 
SH.DROP_INVENTORY_PROCESSED AS "Drop Inventory Processed",
SH.ATTRIBUTE4 AS "Shipping Notes" 
FROM SHIPMENT SH INNER JOIN 
LOCATION DL ON DL.LOCATION_GID = SH.DEST_LOCATION_GID INNER JOIN 
LOCATION SRV ON SRV.LOCATION_GID = SH.SERVPROV_GID INNER JOIN 
LOCATION SL ON SL.LOCATION_GID = SH.SOURCE_LOCATION_GID INNER JOIN 
SHIPMENT_STOP SST ON SH.SHIPMENT_GID = SST.SHIPMENT_GID AND SST.STOP_NUM = 2 LEFT JOIN  
SHIPMENT_STATUS ST ON ST.SHIPMENT_GID = SH.SHIPMENT_GID AND ST.STATUS_TYPE_GID = 'NBL/MX.WMS_STATUS' LEFT JOIN 
SHIPMENT_REMARK SK1 ON SK1.SHIPMENT_GID = SH.SHIPMENT_GID AND SK1.REMARK_QUAL_GID = 'SHIP_DATE' LEFT JOIN 
SHIPMENT_REMARK SK2 ON SK2.SHIPMENT_GID = SH.SHIPMENT_GID AND SK2.REMARK_QUAL_GID = 'NBL.PU_APPOINTMENT' LEFT JOIN 
SHIPMENT_REMARK SK3 ON SK3.SHIPMENT_GID = SH.SHIPMENT_GID AND SK3.REMARK_QUAL_GID = 'NBL.DELIVERY_STOP_2' LEFT JOIN 
SHIPMENT_REFNUM SR1 ON SH.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID = 'CUST_PO' LEFT JOIN 
SHIPMENT_REFNUM SR2 ON SH.SHIPMENT_GID = SR2.SHIPMENT_GID AND SR2.SHIPMENT_REFNUM_QUAL_GID = 'NBL.OR_GROUP' LEFT JOIN 
SHIPMENT_REFNUM SR3 ON SH.SHIPMENT_GID = SR3.SHIPMENT_GID AND SR3.SHIPMENT_REFNUM_QUAL_GID = 'NBL.IS_PRELOAD' LEFT JOIN 
SHIPMENT_REFNUM SR4 ON SH.SHIPMENT_GID = SR4.SHIPMENT_GID AND SR4.SHIPMENT_REFNUM_QUAL_GID = 'NBL.CPU_CONTACT' LEFT JOIN 
SHIPMENT_REFNUM SR5 ON SH.SHIPMENT_GID = SR5.SHIPMENT_GID AND SR5.SHIPMENT_REFNUM_QUAL_GID = 'SO_NUM' LEFT JOIN 
SHIPMENT_REFNUM SR6 ON SH.SHIPMENT_GID = SR6.SHIPMENT_GID AND SR6.SHIPMENT_REFNUM_QUAL_GID = 'NBL.BASE_COST' LEFT JOIN 
SHIPMENT_REFNUM SR7 ON SH.SHIPMENT_GID = SR7.SHIPMENT_GID AND SR7.SHIPMENT_REFNUM_QUAL_GID = 'NBL.TOTAL_PALLET' LEFT JOIN 
SHIPMENT_REFNUM SR8 ON SH.SHIPMENT_GID = SR8.SHIPMENT_GID AND SR8.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TENDER_HOLD' LEFT JOIN 
SHIPMENT_REFNUM SR9 ON SH.SHIPMENT_GID = SR9.SHIPMENT_GID AND SR9.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TENDER_SPOT_BID' LEFT JOIN 
SHIPMENT_REFNUM SR10 ON SH.SHIPMENT_GID = SR10.SHIPMENT_GID AND SR10.SHIPMENT_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' LEFT JOIN 
SHIPMENT_REFNUM SR11 ON SH.SHIPMENT_GID = SR11.SHIPMENT_GID AND SR11.SHIPMENT_REFNUM_QUAL_GID = 'NBL.QTY_MOD' LEFT JOIN 
SHIPMENT_REFNUM SR12 ON SH.SHIPMENT_GID = SR12.SHIPMENT_GID AND SR12.SHIPMENT_REFNUM_QUAL_GID = 'NBL.CUS_LOAD_REF' LEFT JOIN 
SHIPMENT_REFNUM SR13 ON SH.SHIPMENT_GID = SR13.SHIPMENT_GID AND SR13.SHIPMENT_REFNUM_QUAL_GID = 'NBL.REF_VALUE' LEFT JOIN 
SHIPMENT_REFNUM SR14 ON SH.SHIPMENT_GID = SR14.SHIPMENT_GID AND SR14.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TIER' LEFT JOIN 
SHIPMENT_REFNUM SR15 ON SH.SHIPMENT_GID = SR15.SHIPMENT_GID AND SR15.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.SECURE RESOURCES' 
WHERE SH.DOMAIN_NAME = 'NBL/MX'  
--AND SH.SHIPMENT_XID = 'MX23058628'
AND APPOINTMENT_DELIVERY > TO_DATE('2025-10-15','YYYY-MM-DD')
GROUP BY 
SH.SHIPMENT_GID,
SH.SHIPMENT_XID,  
SL.LOCATION_NAME, 
SR2.SHIPMENT_REFNUM_VALUE, 
SH.INDICATOR,
SH.USER_DEFINED1_ICON_GID, 
SK1.REMARK_TEXT,
SK2.REMARK_TEXT, 
SK3.REMARK_TEXT,
DL.LOCATION_NAME, 
SRV.LOCATION_NAME,  
ST.STATUS_VALUE_GID,
SH.START_TIME,
SR3.SHIPMENT_REFNUM_VALUE,
SH.ATTRIBUTE3,
SR4.SHIPMENT_REFNUM_VALUE,
SH.SOURCE_LOCATION_GID,
SR5.SHIPMENT_REFNUM_VALUE,
SH.DEST_LOCATION_GID,
DL.CITY,
DL.PROVINCE_CODE,
SH.ATTRIBUTE2,
SH.USER_DEFINED4_ICON_GID,
SH.RATE_GEO_GID,
SR6.SHIPMENT_REFNUM_VALUE, 
SH.TOTAL_ACTUAL_COST,
SH.ORIGINAL_INVOICE_COST,
SH.TOT_MATCHED_INVOICE_COST,
SH.TOTAL_APPROVED_COST,
SH.TOTAL_WEIGHT,
SR7.SHIPMENT_REFNUM_VALUE,
SH.LOADED_DISTANCE,
SR8.SHIPMENT_REFNUM_VALUE,
SR9.SHIPMENT_REFNUM_VALUE, 
SH.INSERT_USER,
SH.INSERT_DATE,
SH.UPDATE_USER,
SH.UPDATE_DATE,
SR10.SHIPMENT_REFNUM_VALUE, 
SH.PLANNED_TRANSPORT_MODE_GID,
SR11.SHIPMENT_REFNUM_VALUE,
SH.USER_DEFINED2_ICON_GID,
SH.USER_DEFINED3_ICON_GID,
SH.USER_DEFINED5_ICON_GID,
SH.NUM_STOPS, 
SR12.SHIPMENT_REFNUM_VALUE, 
SR13.SHIPMENT_REFNUM_VALUE, 
SH.TOTAL_ITEM_PACKAGE_COUNT,
SH.DOMAIN_NAME,
SR14.SHIPMENT_REFNUM_VALUE, 
SR15.SHIPMENT_REFNUM_VALUE,
SH.DROP_INVENTORY_PROCESSED,
SH.ATTRIBUTE4
;


SELECT 
SH.SHIPMENT_XID,  
LISTAGG(SR1.SHIPMENT_REFNUM_VALUE, '|') WITHIN GROUP (ORDER BY SR1.SHIPMENT_REFNUM_VALUE) "Customer PO"
FROM SHIPMENT SH INNER JOIN
SHIPMENT_REFNUM SR1 ON SH.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID = 'CUST_PO'
WHERE SH.DOMAIN_NAME = 'NBL/MX'
AND SH.SHIPMENT_XID = 'MX23058628'
GROUP BY SHIPMENT_XID



SELECT 
TO_CHAR(APPOINTMENT_DELIVERY, 'YYYY-MM-DD') AS "APPOINTMENT_DELIVERY"
FROM SHIPMENT SH INNER JOIN 
LOCATION DL ON DL.LOCATION_GID = SH.DEST_LOCATION_GID INNER JOIN 
LOCATION SRV ON SRV.LOCATION_GID = SH.SERVPROV_GID INNER JOIN 
LOCATION SL ON SL.LOCATION_GID = SH.SOURCE_LOCATION_GID INNER JOIN 
SHIPMENT_STOP SST ON SH.SHIPMENT_GID = SST.SHIPMENT_GID AND SST.STOP_NUM = 2 LEFT JOIN  
SHIPMENT_STATUS ST ON ST.SHIPMENT_GID = SH.SHIPMENT_GID AND ST.STATUS_TYPE_GID = 'NBL/MX.WMS_STATUS' LEFT JOIN 
SHIPMENT_REMARK SK1 ON SK1.SHIPMENT_GID = SH.SHIPMENT_GID AND SK1.REMARK_QUAL_GID = 'SHIP_DATE' LEFT JOIN 
SHIPMENT_REMARK SK2 ON SK2.SHIPMENT_GID = SH.SHIPMENT_GID AND SK2.REMARK_QUAL_GID = 'NBL.PU_APPOINTMENT' LEFT JOIN 
SHIPMENT_REMARK SK3 ON SK3.SHIPMENT_GID = SH.SHIPMENT_GID AND SK3.REMARK_QUAL_GID = 'NBL.DELIVERY_STOP_2' LEFT JOIN 
SHIPMENT_REFNUM SR1 ON SH.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID = 'CUST_PO' LEFT JOIN 
SHIPMENT_REFNUM SR2 ON SH.SHIPMENT_GID = SR2.SHIPMENT_GID AND SR2.SHIPMENT_REFNUM_QUAL_GID = 'NBL.OR_GROUP' LEFT JOIN 
SHIPMENT_REFNUM SR3 ON SH.SHIPMENT_GID = SR3.SHIPMENT_GID AND SR3.SHIPMENT_REFNUM_QUAL_GID = 'NBL.IS_PRELOAD' LEFT JOIN 
SHIPMENT_REFNUM SR4 ON SH.SHIPMENT_GID = SR4.SHIPMENT_GID AND SR4.SHIPMENT_REFNUM_QUAL_GID = 'NBL.CPU_CONTACT' LEFT JOIN 
SHIPMENT_REFNUM SR5 ON SH.SHIPMENT_GID = SR5.SHIPMENT_GID AND SR5.SHIPMENT_REFNUM_QUAL_GID = 'SO_NUM' LEFT JOIN 
SHIPMENT_REFNUM SR6 ON SH.SHIPMENT_GID = SR6.SHIPMENT_GID AND SR6.SHIPMENT_REFNUM_QUAL_GID = 'NBL.BASE_COST' LEFT JOIN 
SHIPMENT_REFNUM SR7 ON SH.SHIPMENT_GID = SR7.SHIPMENT_GID AND SR7.SHIPMENT_REFNUM_QUAL_GID = 'NBL.TOTAL_PALLET' LEFT JOIN 
SHIPMENT_REFNUM SR8 ON SH.SHIPMENT_GID = SR8.SHIPMENT_GID AND SR8.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TENDER_HOLD' LEFT JOIN 
SHIPMENT_REFNUM SR9 ON SH.SHIPMENT_GID = SR9.SHIPMENT_GID AND SR9.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TENDER_SPOT_BID' LEFT JOIN 
SHIPMENT_REFNUM SR10 ON SH.SHIPMENT_GID = SR10.SHIPMENT_GID AND SR10.SHIPMENT_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE' LEFT JOIN 
SHIPMENT_REFNUM SR11 ON SH.SHIPMENT_GID = SR11.SHIPMENT_GID AND SR11.SHIPMENT_REFNUM_QUAL_GID = 'NBL.QTY_MOD' LEFT JOIN 
SHIPMENT_REFNUM SR12 ON SH.SHIPMENT_GID = SR12.SHIPMENT_GID AND SR12.SHIPMENT_REFNUM_QUAL_GID = 'NBL.CUS_LOAD_REF' LEFT JOIN 
SHIPMENT_REFNUM SR13 ON SH.SHIPMENT_GID = SR13.SHIPMENT_GID AND SR13.SHIPMENT_REFNUM_QUAL_GID = 'NBL.REF_VALUE' LEFT JOIN 
SHIPMENT_REFNUM SR14 ON SH.SHIPMENT_GID = SR14.SHIPMENT_GID AND SR14.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.TIER' LEFT JOIN 
SHIPMENT_REFNUM SR15 ON SH.SHIPMENT_GID = SR15.SHIPMENT_GID AND SR15.SHIPMENT_REFNUM_QUAL_GID = 'NBL/MX.SECURE RESOURCES' 
WHERE SH.DOMAIN_NAME = 'NBL/MX'  
--AND SH.SHIPMENT_XID = 'MX51089394' --'MX51088246'
AND APPOINTMENT_DELIVERY > TO_DATE('2025-10-15','YYYY-MM-DD')