------Rate Offering
SELECT RO.RATE_OFFERING_GID, RO.RATE_OFFERING_XID--, RO.INSERT_USER
FROM RATE_OFFERING RO INNER JOIN
RATE_GEO RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID
WHERE 1 = 1
AND RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
AND RO.DOMAIN_NAME = 'NBL/MX'
ORDER BY RO.RATE_OFFERING_GID


-------Rate Service
SELECT RS.RATE_SERVICE_GID, RS.RATE_SERVICE_XID
FROM RATE_GEO RG INNER JOIN 
RATE_SERVICE RS ON RS.RATE_SERVICE_GID = RG.RATE_SERVICE_GID
WHERE 1 = 1
AND RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
GROUP BY RS.RATE_SERVICE_GID, RS.RATE_SERVICE_XID
ORDER BY RS.RATE_SERVICE_GID

-------Transport Mode
SELECT TRANSPORT_MODE_GID, TRANSPORT_MODE_XID
FROM TRANSPORT_MODE
WHERE DOMAIN_NAME = 'NBL'

-------Transport Type
SELECT EGP.EQUIPMENT_GROUP_PROFILE_GID, EGP.EQUIPMENT_GROUP_PROFILE_XID
FROM RATE_OFFERING RO INNER JOIN
RATE_GEO RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
EQUIPMENT_GROUP_PROFILE EGP ON RO.EQUIPMENT_GROUP_PROFILE_GID = EGP.EQUIPMENT_GROUP_PROFILE_GID
WHERE 1 = 1
AND RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
AND RO.DOMAIN_NAME = 'NBL/MX'
GROUP BY EGP.EQUIPMENT_GROUP_PROFILE_GID, EGP.EQUIPMENT_GROUP_PROFILE_XID
ORDER BY EGP.EQUIPMENT_GROUP_PROFILE_GID


-------X_LANE
SELECT XL.X_LANE_GID, XL.X_LANE_XID, 
        XL.SOURCE_REGION_GID, RE1.REGION_XID AS SOURCE_REGION_XID, 
        XL.DEST_REGION_GID, RE2.REGION_XID AS DEST_REGION_XID
FROM RATE_GEO RG INNER JOIN 
X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN 
REGION RE1 ON RE1.REGION_GID = XL.SOURCE_REGION_GID INNER JOIN
REGION RE2 ON RE2.REGION_GID = XL.DEST_REGION_GID
WHERE 1 = 1
AND RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
AND NOT REGEXP_LIKE(XL.X_LANE_XID,'^[0-9]*$') 
GROUP BY XL.X_LANE_GID, XL.X_LANE_XID, XL.SOURCE_REGION_GID, 
XL.DEST_REGION_GID, RE1.REGION_XID, RE2.REGION_XID
ORDER BY XL.X_LANE_GID, XL.SOURCE_REGION_GID, XL.DEST_REGION_GID