ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy';-- hh24:mi:ss';

SELECT SH.SHIPMENT_XID, 
        SERV.SERVPROV_XID, 
        L.LOCATION_NAME, 
        CL.CAPACITY_LIMIT_XID,
        LA.X_LANE_XID LANE,
        TRUNC(CU.START_DATE) START_DATE, 
        --TRUNC(CU.END_DATE) END_DATE, 
        CU.LIMIT, 
        CU.USAGE
FROM SHIPMENT SH INNER JOIN
SHIPMENT_S_EQUIPMENT_JOIN SSE ON SH.SHIPMENT_GID = SSE.SHIPMENT_GID INNER JOIN
CAPACITY_USAGE CU ON CU.CAPACITY_USAGE_GID = SSE.CAPACITY_USAGE_GID INNER JOIN
CAPACITY_GROUP CG ON CG.CAPACITY_GROUP_GID  = CU.CAPACITY_GROUP_GID INNER JOIN
CAPACITY_LIMIT CL ON CL.CAPACITY_LIMIT_GID = CU.CAPACITY_LIMIT_GID INNER JOIN
X_LANE LA ON LA.X_LANE_GID = CL.X_LANE_GID INNER JOIN  
LOCATION L ON CG.SERVPROV_GID = L.LOCATION_GID INNER JOIN
SERVPROV SERV ON SERV.SERVPROV_GID = CG.SERVPROV_GID
WHERE SH.DEST_LOCATION_GID IN (SELECT LOCATION_GID 
                                FROM REGION_DETAIL
                                WHERE REGION_GID IN ('NBL/MX.MXC|MXC CHALCO','NBL/MX.MXC|MXC CUAUTITLAN','NBL/MX.MTY|MTY NUEVO LEON')
                            ) 
AND SH.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(SH.START_TIME, 'DD-MM-YYYY') BETWEEN '24-01-2025' AND '30-01-2025'
ORDER BY CU.START_DATE, CU.CAPACITY_LIMIT_GID;


'NBL/MX.MXC|MXC CHALCO','NBL/MX.MXC|MXC CUAUTITLAN','NBL/MX.MTY|MTY NUEVO LEON'



SELECT START_DATE, LANE, LOCATION_NAME, SUM(USAGE) USAGE, SUM(LIMIT) LIMIT
FROM (
        SELECT SH.SHIPMENT_XID, 
                SERV.SERVPROV_XID, 
                L.LOCATION_NAME, 
                CL.CAPACITY_LIMIT_XID,
                LA.X_LANE_XID LANE,
                TRUNC(CU.START_DATE) START_DATE, 
                --TRUNC(CU.END_DATE) END_DATE, 
                CU.LIMIT, 
                CU.USAGE
        FROM SHIPMENT SH INNER JOIN
        SHIPMENT_S_EQUIPMENT_JOIN SSE ON SH.SHIPMENT_GID = SSE.SHIPMENT_GID INNER JOIN
        CAPACITY_USAGE CU ON CU.CAPACITY_USAGE_GID = SSE.CAPACITY_USAGE_GID INNER JOIN
        CAPACITY_GROUP CG ON CG.CAPACITY_GROUP_GID  = CU.CAPACITY_GROUP_GID INNER JOIN
        CAPACITY_LIMIT CL ON CL.CAPACITY_LIMIT_GID = CU.CAPACITY_LIMIT_GID INNER JOIN
        X_LANE LA ON LA.X_LANE_GID = CL.X_LANE_GID INNER JOIN  
        LOCATION L ON CG.SERVPROV_GID = L.LOCATION_GID INNER JOIN
        SERVPROV SERV ON SERV.SERVPROV_GID = CG.SERVPROV_GID
        WHERE LA.X_LANE_GID IN ('NBL/MX.MTY|MTY NUEVO LEON')
        AND TO_CHAR(CU.START_DATE, 'YYYY-MM-DD') >= '2025-01-24'
        AND SERV.SERVPROV_XID = 'CAR-3139497'
        AND SH.DOMAIN_NAME = 'NBL/MX'
) T
GROUP BY START_DATE, LANE, LOCATION_NAME
ORDER BY START_DATE, LANE, LOCATION_NAME
;

/*'NBL/MX.MXC|MXC CHALCO','NBL/MX.MXC|MXC CUAUTITLAN',*/


SELECT START_DATE, LANE, LOCATION_NAME, SUM(USAGE) USAGE, SUM(LIMIT) LIMIT
FROM (
        SELECT  SERV.SERVPROV_XID, 
                L.LOCATION_NAME, 
                CL.CAPACITY_LIMIT_XID,
                LA.X_LANE_XID LANE,
                TRUNC(CU.START_DATE) START_DATE, 
                --TRUNC(CU.END_DATE) END_DATE, 
                CU.LIMIT, 
                CU.USAGE
        FROM SHIPMENT SH INNER JOIN
        SHIPMENT_S_EQUIPMENT_JOIN SSE ON SH.SHIPMENT_GID = SSE.SHIPMENT_GID INNER JOIN
        CAPACITY_USAGE CU ON CU.CAPACITY_USAGE_GID = SSE.CAPACITY_USAGE_GID INNER JOIN
        CAPACITY_GROUP CG ON CG.CAPACITY_GROUP_GID  = CU.CAPACITY_GROUP_GID INNER JOIN
        CAPACITY_LIMIT CL ON CL.CAPACITY_LIMIT_GID = CU.CAPACITY_LIMIT_GID INNER JOIN 
        X_LANE LA ON LA.X_LANE_GID = CL.X_LANE_GID INNER JOIN  
        LOCATION L ON CG.SERVPROV_GID = L.LOCATION_GID INNER JOIN 
        SERVPROV SERV ON SERV.SERVPROV_GID = CG.SERVPROV_GID 
        WHERE LA.X_LANE_GID IN ('NBL/MX.MXC|MXC CHALCO','NBL/MX.MXC|MXC CUAUTITLAN','NBL/MX.MTY|MTY NUEVO LEON') 
        AND TO_CHAR(CU.START_DATE, 'YYYY-MM-DD') BETWEEN '2025-01-24' AND '2025-01-30'      
        --AND SERV.SERVPROV_XID IN ('CAR-3139497','CAR-4744463', 'CAR-2480207') 
        AND SH.DOMAIN_NAME = 'NBL/MX' 
        GROUP BY CU.START_DATE, LA.X_LANE_XID, L.LOCATION_NAME, CL.CAPACITY_LIMIT_XID, SERV.SERVPROV_XID, LA.X_LANE_XID, CU.LIMIT, CU.USAGE
        ORDER BY CU.START_DATE, LA.X_LANE_XID, L.LOCATION_NAME
) T
GROUP BY START_DATE, LANE, LOCATION_NAME
ORDER BY LANE, LOCATION_NAME, START_DATE


SELECT  TRUNC(CU.START_DATE) START_DATE, 
        LA.X_LANE_XID LANE,
        L.LOCATION_NAME,
        CU.LIMIT, 
        CU.USAGE
FROM SHIPMENT SH INNER JOIN
SHIPMENT_S_EQUIPMENT_JOIN SSE ON SH.SHIPMENT_GID = SSE.SHIPMENT_GID INNER JOIN
CAPACITY_USAGE CU ON CU.CAPACITY_USAGE_GID = SSE.CAPACITY_USAGE_GID INNER JOIN
CAPACITY_GROUP CG ON CG.CAPACITY_GROUP_GID  = CU.CAPACITY_GROUP_GID INNER JOIN
CAPACITY_LIMIT CL ON CL.CAPACITY_LIMIT_GID = CU.CAPACITY_LIMIT_GID INNER JOIN 
X_LANE LA ON LA.X_LANE_GID = CL.X_LANE_GID INNER JOIN  
LOCATION L ON CG.SERVPROV_GID = L.LOCATION_GID INNER JOIN 
SERVPROV SERV ON SERV.SERVPROV_GID = CG.SERVPROV_GID 
WHERE LA.X_LANE_GID IN ('NBL/MX.MXC|MXC CHALCO','NBL/MX.MXC|MXC CUAUTITLAN','NBL/MX.MTY|MTY NUEVO LEON') 
AND TO_CHAR(CU.START_DATE, 'YYYY-MM-DD') BETWEEN '2025-01-24' AND '2025-01-30'      
AND SERV.SERVPROV_XID IN ('CAR-3139497','CAR-4744463', 'CAR-2480207') 
AND SH.DOMAIN_NAME = 'NBL/MX' 
GROUP BY CU.START_DATE, LA.X_LANE_XID, L.LOCATION_NAME, CL.CAPACITY_LIMIT_XID, SERV.SERVPROV_XID, LA.X_LANE_XID, CU.LIMIT, CU.USAGE
ORDER BY LA.X_LANE_XID, L.LOCATION_NAME, CU.START_DATE