
--------------------------------Shipment Costs-------------------------------

SELECT SC.SHIPMENT_GID, OM.ORDER_RELEASE_GID, SC.COST_TYPE, SC.ACCESSORIAL_CODE_GID, SC.ADJUSTMENT_REASON_GID, SC.COST,
SC.INSERT_DATE, SC.INSERT_USER
FROM SHIPMENT_COST SC INNER JOIN
ORDER_MOVEMENT OM ON SC.SHIPMENT_GID = OM.SHIPMENT_GID
WHERE 1 = 1
AND SC.DOMAIN_NAME = 'NBL/MX'
AND SC.COST_TYPE = 'A'
AND SC.INSERT_DATE >= TO_DATE('01/02/2026', 'DD/MM/YYYY')
ORDER BY SC.INSERT_DATE ASC


--SHIPMENT_COST_DETAIL SCD ON SC.SHIPMENT_COST_SEQNO = SCD.SHIPMENT_COST_SEQNO INNER JOIN

-------------------------------Invoices-------------------------------

SELECT V.*--IV.INVOICE_GID, IVS.SHIPMENT_GID, V. 
FROM INVOICE IV INNER JOIN
INVOICE_LINEITEM IVL ON IV.INVOICE_GID = IVL.INVOICE_GID INNER JOIN
INVOICE_SHIPMENT IVS ON IV.INVOICE_GID = IVS.INVOICE_GID INNER JOIN
INVOICE_LINEITEM_BOV V ON IV.INVOICE_GID = V.INVOICE_GID
WHERE IV.DOMAIN_NAME = 'NBL/MX'
AND IV.INSERT_DATE >= TO_DATE('01/02/2026', 'DD/MM/YYYY')
AND IVL.DESCRIPTION = 'A'


SELECT * 
FROM INVOICE_LINEITEM_BOV  
WHERE INSERT_DATE >= TO_DATE('01/02/2026', 'DD/MM/YYYY')