SELECT * FROM RATES_JUN_24;

SELECT * FROM RATES_MAY_24;


SELECT MAY.ID MAY_ID, JUN.ID JUN_ID, JUN.ORIGEN, JUN.DESTINO, JUN.NICK_NAME, JUN.TIPO_DE_UNIDAD, JUN.TARIFA JUN_TARIFA, MAY.TARIFA MAY_TARIFA
FROM RATES_JUN_24 JUN LEFT JOIN
RATES_MAY_24 MAY ON MAY.ORIGEN = JUN.ORIGEN
                AND MAY.DESTINO = JUN.DESTINO
                AND MAY.SERVICE_PROVIDER_ID = JUN.SERVICE_PROVIDER_ID
WHERE MAY.ID IS NULL;

--Faltantes
JUN-042
JUN-043
JUN-589
JUN-590
JUN-748
JUN-750
JUN-756
