SELECT S.SHIPMENT_GID,
       S.SHIPMENT_XID,
       S.LOADED_DISTANCE,
       S.LOADED_DISTANCE_UOM_CODE,
       S.SOURCE_LOCATION_GID,
       L.LOCATION_NAME SOURCE,
       L.LAT S_LAT,
       L.LON S_LON,
       S.DEST_LOCATION_GID,
       L2.LOCATION_NAME DEST,
       L2.LAT D_LAT,
       L2.LON D_LON,
       S.START_TIME,
       S.END_TIME,
       S.SERVPROV_GID,
       S.RATE_OFFERING_GID,
       S.RATE_GEO_GID,
       S.INSERT_DATE
FROM SHIPMENT S INNER JOIN
    LOCATION L ON S.SOURCE_LOCATION_GID = L.LOCATION_GID INNER JOIN
    LOCATION L2 ON S.DEST_LOCATION_GID = L2.LOCATION_GID
WHERE TO_CHAR(S.INSERT_DATE, 'YYYY-MM-DD') = TO_CHAR(SYSDATE, 'YYYY-MM-DD')
AND S.DOMAIN_NAME = 'NBL/MX'