SELECT ORE.ORDER_RELEASE_GID, OMV.SHIPMENT_GID, S.SHIPMENT_GID S_SHIPMENT_GID
FROM ORDER_RELEASE ORE INNER JOIN
ORDER_RELEASE_STATUS  ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID LEFT JOIN
ORDER_MOVEMENT OMV ON ORE.ORDER_RELEASE_GID = OMV.ORDER_RELEASE_GID LEFT JOIN
SHIPMENT S ON OMV.SHIPMENT_GID = S.SHIPMENT_GID
WHERE ORE.INSERT_DATE >= SYSDATE - 10
AND ORE.DOMAIN_NAME = 'NBL/MX'
AND ORS.STATUS_TYPE_GID LIKE '%PLANNING%'
AND ORS.STATUS_VALUE_GID  LIKE '%PLANNING_PLANNED - FINAL%'
AND  S.SHIPMENT_GID IS NULL