--3PL_OR_BULKPLAN_EDM--
SELECT ORR.ORDER_RELEASE_GID    
FROM ORDER_RELEASE ORR  
INNER JOIN   ORDER_RELEASE_STATUS ORS  
ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID      
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'      
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'      
AND ORR.DOMAIN_NAME = 'NBL/MX'      
AND ORR.DELIVERY_IS_APPT  = 'Y'      
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'    
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE      
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD')
BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD')
AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')        
AND ORR.SOURCE_LOCATION_GID
IN (SELECT LOCATION_GID  
FROM REGION_DETAIL  
WHERE REGION_GID  
IN ('NBL.3SV_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION')                               )  
GROUP BY ORR.ORDER_RELEASE_GID

--MTY_OR_BULKPLAN_EDM--
SELECT ORR.ORDER_RELEASE_GID    
FROM ORDER_RELEASE ORR  
INNER JOIN   ORDER_RELEASE_STATUS ORS  
ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID      
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'      
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'      
AND ORR.DOMAIN_NAME = 'NBL/MX'      
AND ORR.DELIVERY_IS_APPT  = 'Y'      
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'    
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE      
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD')
BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')    
AND ORR.SOURCE_LOCATION_GID
IN ( SELECT LOCATION_GID                                    
FROM REGION_DETAIL                                    
WHERE REGION_GID  
IN ('NBL.MTY_SHIPPING_REGION')                               )  
GROUP BY ORR.ORDER_RELEASE_GID

--MXC_OR_BULKPLAN_EDM--
SELECT ORR.ORDER_RELEASE_GID    
FROM ORDER_RELEASE ORR  
INNER JOIN    ORDER_RELEASE_STATUS ORS  
ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID      
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'      
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'      
AND ORR.DOMAIN_NAME = 'NBL/MX'      
AND ORR.DELIVERY_IS_APPT  = 'Y'      
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'    
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE      
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD')
BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')        
AND ORR.SOURCE_LOCATION_GID
IN ( SELECT LOCATION_GID                                    
FROM REGION_DETAIL                                    
WHERE REGION_GID  
IN ('NBL.MXC_SHIPPING_REGION')                               )  
GROUP BY ORR.ORDER_RELEASE_GID

--WO_REG_OR_BULKPLAN_EDM--//GDL_OR_BULKPLAN_EDM--
SELECT ORR.ORDER_RELEASE_GID    
FROM ORDER_RELEASE ORR  
INNER JOIN    ORDER_RELEASE_STATUS ORS  
ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID      
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'      
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'      
AND ORR.DOMAIN_NAME = 'NBL/MX'      
AND ORR.DELIVERY_IS_APPT  = 'Y'      
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'    
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE      
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD')
BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')        
AND ORR.SOURCE_LOCATION_GID
IN ( SELECT LOCATION_GID                                    
FROM REGION_DETAIL                                    
WHERE REGION_GID  
IN ('NBL.GDL_SHIPPING_REGION')                               )  
GROUP BY ORR.ORDER_RELEASE_GID