

SELECT ORDER_RELEASE_GID, COUNT(ORDER_RELEASE_REFNUM_QUAL_GID)
FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
GROUP BY ORDER_RELEASE_GID
HAVING COUNT(ORDER_RELEASE_REFNUM_QUAL_GID) > 2


SELECT ORDER_RELEASE_GID, ORDER_RELEASE_REFNUM_VALUE--, COUNT(ORDER_RELEASE_REFNUM_QUAL_GID)
FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
AND DOMAIN_NAME = 'NBL/MX'
GROUP BY ORDER_RELEASE_GID, ORDER_RELEASE_REFNUM_VALUE
HAVING COUNT(ORDER_RELEASE_REFNUM_QUAL_GID) >= 2;



SELECT ORDER_RELEASE_GID, ORDER_RELEASE_REFNUM_VALUE
FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_GID IN (
                SELECT ORDER_RELEASE_GID
                FROM ORDER_RELEASE_REFNUM
                WHERE ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
                --AND DOMAIN_NAME = 'NBL/MX'
                GROUP BY ORDER_RELEASE_GID
                HAVING COUNT(ORDER_RELEASE_REFNUM_QUAL_GID) > 1
            )
AND ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
AND (insert_date >= TO_DATE('2025-01-01','YYYY-MM-DD'))
AND ORDER_RELEASE_REFNUM_VALUE LIKE '22%'
ORDER BY ORDER_RELEASE_GID ASC
;

-------------------------------------Final---------------------------------------------
SELECT ORDER_RELEASE_GID, ORDER_RELEASE_REFNUM_VALUE
FROM ORDER_RELEASE_REFNUM
WHERE ORDER_RELEASE_GID IN (
                SELECT ORDER_RELEASE_GID
                FROM ORDER_RELEASE_REFNUM
                WHERE ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
                GROUP BY ORDER_RELEASE_GID
                HAVING COUNT(ORDER_RELEASE_REFNUM_QUAL_GID) > 1
            )
AND ORDER_RELEASE_REFNUM_QUAL_GID IN ('SO_NUM')
AND (insert_date >= TO_DATE('2025-01-01','YYYY-MM-DD'))
AND ORDER_RELEASE_REFNUM_VALUE LIKE '22%'
ORDER BY ORDER_RELEASE_GID ASC
---------------------------------------------------------------------------------------