SELECT *
FROM AGENT_ACTION_DETAILS D INNER JOIN
AGENT A ON A.AGENT_GID = D.AGENT_GID
WHERE 1 = 1 
--AND ACTION_PARAMETERS LIKE '%ACCEPT TENDER%'
AND AGENT_ACTION_GID LIKE '%ACCEPT TENDER%'
AND A.IS_ACTIVE = 'Y'
--AND A.AGENT_GID LIKE '%SECURE_RESOURCES_CPU%'


SHIPMENT TENDER - TENDERED
NBL_DIMITRI WITHDRAW TENDER
NBL_SECURE_RESOURCES_TENDERED-DRGCONSOL
NBL_SPOTNOW_FINAL_CARRIER
NBL_SECURE_RESOURCES_PROCESS1
SPOT BID AUTO
CAPACITYPLUS_FINAL_CARRIER


SHIPMENT TENDER - TENDERED,NBL_DIMITRI WITHDRAW TENDER,NBL_SECURE_RESOURCES_TENDERED-DRGCONSOL,NBL_SPOTNOW_FINAL_CARRIER,NBL_SECURE_RESOURCES_PROCESS1,SPOT BID AUTO,CAPACITYPLUS_FINAL_CARRIER


select 1 
from shipment 
where shipment_gid ='NBL/MX.MX5001011443'
and servprov_gid like 'NBL.CAR-SUP-%'