ALTER SESSION SET CURRENT_SCHEMA = ND2_ARC;
ALTER SESSION SET CURRENT_SCHEMA = MXC_WMS;

SELECT LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION AS STATUS, FAC.DESCRIPTION AS FACILITY_STATUS, DET.ITEM_NAME, 'MXC' AS SITE
FROM MXC_WMS.LPN LPN INNER JOIN
MXC_WMS.LPN_DETAIL DET ON LPN.LPN_ID = DET.LPN_ID INNER JOIN
MXC_WMS.LPN_STATUS STAT ON LPN.LPN_STATUS = STAT.LPN_STATUS INNER JOIN
MXC_WMS.LPN_FACILITY_STATUS FAC ON LPN.LPN_FACILITY_STATUS = FAC.LPN_FACILITY_STATUS
WHERE 1 = 1
--AND TC_LPN_ID = '00800275411101456531'
AND LPN.inbound_outbound_indicator = 'I'
AND FAC.inbound_outbound_indicator = 'I'
AND LPN.LPN_STATUS = 45
AND DET.ITEM_NAME IN ('BUR22Z24PZALHCT',
'BUR22Z24PZBBHCT',
'BUR22Z24PZGRHCT',
'BUR22Z24PZSKHCT')
GROUP BY LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION, FAC.DESCRIPTION, DET.ITEM_NAME
UNION ALL
SELECT LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION AS STATUS, FAC.DESCRIPTION AS FACILITY_STATUS, DET.ITEM_NAME, 'MTY' AS SITE
FROM MTY_WMS.LPN LPN INNER JOIN
MTY_WMS.LPN_DETAIL DET ON LPN.LPN_ID = DET.LPN_ID INNER JOIN
MTY_WMS.LPN_STATUS STAT ON LPN.LPN_STATUS = STAT.LPN_STATUS INNER JOIN
MTY_WMS.LPN_FACILITY_STATUS FAC ON LPN.LPN_FACILITY_STATUS = FAC.LPN_FACILITY_STATUS
WHERE 1 = 1
--AND TC_LPN_ID = '00800275411101456531'
AND LPN.inbound_outbound_indicator = 'I'
AND FAC.inbound_outbound_indicator = 'I'
AND LPN.LPN_STATUS = 45
AND DET.ITEM_NAME IN ('BUR22Z24PZALHCT',
'BUR22Z24PZBBHCT',
'BUR22Z24PZGRHCT',
'BUR22Z24PZSKHCT')
GROUP BY LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION, FAC.DESCRIPTION, DET.ITEM_NAME
UNION ALL 
SELECT LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION AS STATUS, FAC.DESCRIPTION AS FACILITY_STATUS, DET.ITEM_NAME, 'GDL' AS SITE
FROM GDL_WMS.LPN LPN INNER JOIN
GDL_WMS.LPN_DETAIL DET ON LPN.LPN_ID = DET.LPN_ID INNER JOIN
GDL_WMS.LPN_STATUS STAT ON LPN.LPN_STATUS = STAT.LPN_STATUS INNER JOIN
GDL_WMS.LPN_FACILITY_STATUS FAC ON LPN.LPN_FACILITY_STATUS = FAC.LPN_FACILITY_STATUS
WHERE 1 = 1
--AND TC_LPN_ID = '00800275411101456531'
AND LPN.inbound_outbound_indicator = 'I'
AND FAC.inbound_outbound_indicator = 'I'
AND LPN.LPN_STATUS = 45
AND DET.ITEM_NAME IN ('BUR22Z24PZALHCT',
'BUR22Z24PZBBHCT',
'BUR22Z24PZGRHCT',
'BUR22Z24PZSKHCT')
GROUP BY LPN.TC_LPN_ID, LPN.LPN_STATUS, STAT.DESCRIPTION, FAC.DESCRIPTION, DET.ITEM_NAME
;
/*
TC_ORDER_ID
TC_ASN_ID
5774-41320968
*/

--SELECT * FROM MXC_WMS.LPN_FACILITY_STATUS;

