SELECT DISTINCT O.ORDER_RELEASE_GID 
FROM ORDER_RELEASE O 
WHERE O.ORDER_RELEASE_GID = ? 
AND NOT EXISTS (SELECT '1' 
FROM ORDER_RELEASE_REFNUM R , ORDER_RELEASE_REFNUM ORR WHERE ORR.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.REF_VALUE' AND R.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.REF_VALUE' AND ORR.ORDER_RELEASE_GID = R.ORDER_RELEASE_GID AND R.ORDER_RELEASE_REFNUM_VALUE!= ORR.ORDER_RELEASE_REFNUM_VALUE AND O.ORDER_RELEASE_GID = R.ORDER_RELEASE_GID AND O.ORDER_RELEASE_GID = ORR.ORDER_RELEASE_GID)