SELECT RG.RATE_OFFERING_GID, XL.X_LANE_GID, XL.X_LANE_XID, 
        XL.SOURCE_REGION_GID, XL.DEST_REGION_GID, XL.DEST_LOCATION_GID 
FROM RATE_GEO RG INNER JOIN 
    RATE_OFFERING RO ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID INNER JOIN 
    X_LANE XL ON RG.X_LANE_GID = XL.X_LANE_GID 
WHERE 1 = 1 
AND RG.DOMAIN_NAME = 'NBL/MX' 
AND RG.IS_ACTIVE = 'Y' 
AND TO_CHAR(RG.INSERT_DATE, 'YYYY-MM-DD') > '2026-01-01' 
AND REGEXP_LIKE(XL.X_LANE_XID,'^[0-9]*$') 