/*
Request from Uber Freight:

" We will need some help from Niagara to perform a rate audit on everything tendered so far (unclear if this is just the shared lane set or something broader).
• List of NBs tendered to UFLB and UBER SCACs since March 10 1600 CT - Ok
• Include Delivery number - Ok
o Where there are multiple delivery numbers, separate by comma. - Ok
• Pickup City / State - Ok 
• Dropoff City / State - Ok
• OTM Mileage - Ok
• Line items in unique columns
o Flat rate (pt 1)
o Flat rate (pt 2)
o LH RPM Total
o FSC
o Accessorial
• Bid item code
• Rate record (need to confirm if T1 or T0 rate)

What we don't have is an easy way to pull in the rate record systematically, as well as mileage.
Once we have this data set, we will pull in the active rates to make sure everything is accurate based on the bid item code."

--------------------------------------------------------------------------------
SELECT SH.*
FROM SHIPMENT SH INNER JOIN
SERVPROV SV ON SH.SERVPROV_GID  = SV.SERVPROV_GID INNER JOIN
SCAC SC ON SV.SCAC_GID = SC.SCAC_GID
WHERE SC.SCAC_XID  IN ('UFLB', 'UBER')
AND SH.INSERT_DATE > TO_DATE('2026-03-20 16:00:00', 'YYYY-MM-DD HH24:MI:SS')
---------------------------------------------------------------------------------

Tricia: 
List of NBs tendered to UFLB and UBER SCACs since March 10 1600 CT - just accepted (shipment not tender collab) - Ok
Order releases, if multistep order release group - Ok
Pickup City / State - Ok
Dropoff City / State - if multistep last stop- Ok
OTM Mileage - Ok
Line items in unique columns - in shipment cost
Flat rate (pt 1) - Flat Rate Ok
Flat rate (pt 2) Flat Rate |uber ok
LH RPM Total - total base cost ok
FSC ok
Accessorial - if lumper
stop of
Bid item code - no need to include - Ok
Rate offering - Ok
Rate record (need to confirm if T1 or T0 rate)  - Ok

NB54751576
*/


SELECT T.SHIPMENT_XID, 
    T.SCAC_XID, 
    T.DELIVERIES, 
    T.STATUS_VALUE_XID, 
    T.SOU_CITY, 
    T.SOU_STATE, 
    T.DEST_CITY, 
    T.DEST_STATE,
    T.MILEAGE, 
    T.RATE_OFFERING_GID, 
    T.RATE_GEO_GID, 
    ROUND(SCB.COST, 2) AS TOTAL_BASE_COST,
    --SC.COST_TYPE, 
    ROUND(FSC.COST, 2) AS FSC_NIAGARA,
    FDSC.ACCESSORIAL_CODE_GID AS ACCESSORIAL_CODE,
    ROUND(FDSC.COST, 2) AS ACCESORIAL_COST
FROM ( 
    SELECT STV.SHIPMENT_XID, 
        SHP.SHIPMENT_GID,
        SC.SCAC_XID, 
        --ORL.ORDER_RELEASE_GID, 
        LISTAGG(ORL.ORDER_RELEASE_XID, ', ') WITHIN GROUP (ORDER BY ORL.ORDER_RELEASE_XID) AS DELIVERIES, 
        STV.STATUS_VALUE_XID, 
        LOC3.CITY AS SOU_CITY, 
        LOC3.PROVINCE_CODE AS SOU_STATE, 
        LOC2.CITY AS DEST_CITY, 
        LOC2.PROVINCE_CODE AS DEST_STATE,
        SHP.LOADED_DISTANCE AS MILEAGE, 
        SHP.RATE_OFFERING_GID, 
        SHP.RATE_GEO_GID 
    FROM SHIP_TENDER_COLLAB_BOV STV INNER JOIN 
        SHIPMENT SHP ON STV.SHIPMENT_GID = SHP.SHIPMENT_GID INNER JOIN 
        ORDER_MOVEMENT OM ON SHP.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN 
        ORDER_RELEASE ORL ON OM.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID INNER JOIN 
        LOCATION LOC2 ON SHP.DEST_LOCATION_GID = LOC2.LOCATION_GID INNER JOIN 
        LOCATION LOC3 ON SHP.SOURCE_LOCATION_GID = LOC3.LOCATION_GID INNER JOIN 
        SERVPROV SV ON SHP.SERVPROV_GID  = SV.SERVPROV_GID INNER JOIN 
        SCAC SC ON SV.SCAC_GID = SC.SCAC_GID 
    WHERE 1 = 1 
    AND SC.SCAC_XID IN ('UFLB', 'UBER') 
    AND SHP.INSERT_DATE > TO_DATE('2026-03-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS') 
    AND STV.DOMAIN_NAME  = 'NBL'  
    AND STV.STATUS_VALUE_XID IN ('SECURE RESOURCES_ACCEPTED'/*, 'SECURE RESOURCES_DECLINED',  
                                'SECURE RESOURCES_TIMED OUT', 'SECURE RESOURCES_WITHDRAWN'*/) 
    --AND SHP.SHIPMENT_GID = 'NBL.NB54751576'
    GROUP BY STV.SHIPMENT_XID, SHP.SHIPMENT_GID, SC.SCAC_XID, STV.STATUS_VALUE_XID, LOC3.CITY, 
        LOC3.PROVINCE_CODE, LOC2.CITY, LOC2.PROVINCE_CODE, SHP.LOADED_DISTANCE, SHP.RATE_OFFERING_GID, SHP.RATE_GEO_GID 
    ORDER BY STV.SHIPMENT_XID
) T LEFT JOIN 
SHIPMENT_COST SCB ON T.SHIPMENT_GID = SCB.SHIPMENT_GID AND SCB.COST_TYPE = 'B' LEFT JOIN  
SHIPMENT_COST FSC ON T.SHIPMENT_GID = FSC.SHIPMENT_GID AND FSC.ACCESSORIAL_CODE_GID = 'NBL.FSC_NIAGARA' LEFT JOIN  
SHIPMENT_COST FDSC ON T.SHIPMENT_GID = FDSC.SHIPMENT_GID AND FDSC.ACCESSORIAL_CODE_GID <> 'NBL.FSC_NIAGARA' 
ORDER BY T.SHIPMENT_GID ASC




SELECT T.SHIPMENT_XID, T.SCAC_XID, T.DELIVERIES, T.STATUS_VALUE_XID, T.SOU_CITY, T.SOU_STATE, T.DEST_CITY, T.DEST_STATE, T.MILEAGE, T.RATE_OFFERING_GID, 
    T.RATE_GEO_GID, ROUND(SCB.COST, 2) AS TOTAL_BASE_COST, ROUND(FSC.COST, 2) AS FSC_NIAGARA, FDSC.ACCESSORIAL_CODE_GID AS ACCESSORIAL_CODE, ROUND(FDSC.COST, 2) AS ACCESORIAL_COST
FROM ( SELECT STV.SHIPMENT_XID, SHP.SHIPMENT_GID, SC.SCAC_XID, 
        LISTAGG(ORL.ORDER_RELEASE_XID, ', ') WITHIN GROUP (ORDER BY ORL.ORDER_RELEASE_XID) AS DELIVERIES, 
        STV.STATUS_VALUE_XID, LOC3.CITY AS SOU_CITY, LOC3.PROVINCE_CODE AS SOU_STATE, LOC2.CITY AS DEST_CITY, 
        LOC2.PROVINCE_CODE AS DEST_STATE, SHP.LOADED_DISTANCE AS MILEAGE, SHP.RATE_OFFERING_GID, 
        SHP.RATE_GEO_GID 
    FROM SHIP_TENDER_COLLAB_BOV STV INNER JOIN 
        SHIPMENT SHP ON STV.SHIPMENT_GID = SHP.SHIPMENT_GID INNER JOIN 
        ORDER_MOVEMENT OM ON SHP.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN 
        ORDER_RELEASE ORL ON OM.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID INNER JOIN 
        LOCATION LOC2 ON SHP.DEST_LOCATION_GID = LOC2.LOCATION_GID INNER JOIN 
        LOCATION LOC3 ON SHP.SOURCE_LOCATION_GID = LOC3.LOCATION_GID INNER JOIN 
        SERVPROV SV ON SHP.SERVPROV_GID  = SV.SERVPROV_GID INNER JOIN 
        SCAC SC ON SV.SCAC_GID = SC.SCAC_GID 
    WHERE 1 = 1 
    AND SC.SCAC_XID IN ('UFLB', 'UBER') 
    AND SHP.INSERT_DATE > TO_DATE('2026-03-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS') 
    AND STV.DOMAIN_NAME  = 'NBL'  
    AND STV.STATUS_VALUE_XID IN ('SECURE RESOURCES_ACCEPTED')  
    GROUP BY STV.SHIPMENT_XID, SHP.SHIPMENT_GID, SC.SCAC_XID, STV.STATUS_VALUE_XID, LOC3.CITY, 
        LOC3.PROVINCE_CODE, LOC2.CITY, LOC2.PROVINCE_CODE, SHP.LOADED_DISTANCE, SHP.RATE_OFFERING_GID, SHP.RATE_GEO_GID 
    ORDER BY STV.SHIPMENT_XID 
) T LEFT JOIN 
SHIPMENT_COST SCB ON T.SHIPMENT_GID = SCB.SHIPMENT_GID AND SCB.COST_TYPE = 'B' LEFT JOIN  
SHIPMENT_COST FSC ON T.SHIPMENT_GID = FSC.SHIPMENT_GID AND FSC.ACCESSORIAL_CODE_GID = 'NBL.FSC_NIAGARA' LEFT JOIN  
SHIPMENT_COST FDSC ON T.SHIPMENT_GID = FDSC.SHIPMENT_GID AND FDSC.ACCESSORIAL_CODE_GID <> 'NBL.FSC_NIAGARA' 
ORDER BY T.SHIPMENT_GID ASC 
