
SELECT * FROM all_objects
where object_name like '%FREIGHT%'
and object_type in ('TABLE', 'VIEW')
and owner = 'WSH';

SELECT * FROM all_objects
where object_name like '%SUPPLIER%'
and object_type in ('TABLE', 'VIEW')
ORDER BY OBJECT_NAME;

SELECT * 
FROM AP_SUPPLIERS
WHERE VENDOR_ID = '2161599';

SELECT *
FROM ap_supplier_sites_all
WHERE vendor_id = '2161599'
AND vendor_site_id = '212804';

SELECT *
FROM WSH_CARRIERS
WHERE SCAC_CODE = 'SOLI';

SELECT /*C.CARRIER_ID, A.VENDOR_ID, */ A.VENDOR_NAME, C.FREIGHT_CODE, C.SCAC_CODE /*, C.CURRENCY_CODE, S.VENDOR_SITE_CODE, S.VENDOR_SITE_ID*/
FROM WSH_CARRIERS C INNER JOIN
AP_SUPPLIERS A ON A.VENDOR_ID = C.SUPPLIER_ID INNER JOIN
AP_SUPPLIER_SITES_ALL S ON S.VENDOR_ID = A.VENDOR_ID AND S.VENDOR_SITE_ID = C.SUPPLIER_SITE_ID
WHERE VENDOR_SITE_CODE = 'TRK-EDM'
ORDER BY A.VENDOR_NAME;
--C.SCAC_CODE = 'SOLI';

DESCRIBE WSH_ORG_CARRIER_SERVICES ;

DESCRIBE WSH_CARRIER_SERVICES;


SELECT C.CARRIER_ID, C.CURRENCY_CODE, SV.MODE_OF_TRANSPORT, A.VENDOR_NAME, C.FREIGHT_CODE, C.SCAC_CODE, SV.SERVICE_LEVEL, SV.SHIP_METHOD_MEANING, A.ORGANIZATION_TYPE_LOOKUP_CODE
/*, C.CURRENCY_CODE, S.VENDOR_SITE_CODE, S.VENDOR_SITE_ID*/
FROM WSH_CARRIERS C INNER JOIN
AP_SUPPLIERS A ON A.VENDOR_ID = C.SUPPLIER_ID INNER JOIN
AP_SUPPLIER_SITES_ALL S ON S.VENDOR_ID = A.VENDOR_ID AND S.VENDOR_SITE_ID = C.SUPPLIER_SITE_ID INNER JOIN
WSH_CARRIER_SERVICES SV ON SV.CARRIER_ID = C.CARRIER_ID
WHERE VENDOR_SITE_CODE = 'TRK-EDM'
ORDER BY A.VENDOR_NAME, SV.SERVICE_LEVEL, SV.SHIP_METHOD_MEANING;

SELECT C.CARRIER_ID, C.CURRENCY_CODE, SV.MODE_OF_TRANSPORT, A.VENDOR_NAME, C.FREIGHT_CODE, C.SCAC_CODE, SV.SERVICE_LEVEL, SV.SHIP_METHOD_MEANING, H.ORGANIZATION_CODE
FROM WSH_CARRIERS C INNER JOIN
AP_SUPPLIERS A ON A.VENDOR_ID = C.SUPPLIER_ID INNER JOIN
AP_SUPPLIER_SITES_ALL S ON S.VENDOR_ID = A.VENDOR_ID AND S.VENDOR_SITE_ID = C.SUPPLIER_SITE_ID INNER JOIN
WSH_CARRIER_SERVICES SV ON SV.CARRIER_ID = C.CARRIER_ID INNER JOIN
WSH_ORG_CARRIER_SERVICES SOV ON SOV.CARRIER_SERVICE_ID = SV.CARRIER_SERVICE_ID AND SOV.CARRIER_SERVICE_ID = SV.CARRIER_SERVICE_ID INNER JOIN
ORG_ORGANIZATION_DEFINITIONS H ON SOV.ORGANIZATION_ID = H.ORGANIZATION_ID 
WHERE S.VENDOR_SITE_CODE = 'TRK-EDM'
--AND C.SCAC_CODE = 'SOLI'
AND H.ORGANIZATION_code IN ('MXC','MTY','GDL','3MX','3TJ','3SV','3MZ','3GD','3EM')
GROUP BY C.CARRIER_ID, C.CURRENCY_CODE, SV.MODE_OF_TRANSPORT, A.VENDOR_NAME, C.FREIGHT_CODE, C.SCAC_CODE, SV.SERVICE_LEVEL, SV.SHIP_METHOD_MEANING, H.ORGANIZATION_CODE
ORDER BY A.VENDOR_NAME, SV.SERVICE_LEVEL, SV.SHIP_METHOD_MEANING;


SELECT * 
FROM WSH_ORG_CARRIER_SERVICES ; 
WHERE ORGANIZATION_ID = 1893;
