SELECT LO.LOCATION_NAME AS CARRIER, RE1.REGION_XID AS SOURCE_REGION, RS.RATE_SERVICE_XID AS RATE_SERVICE
FROM RATE_GEO RG INNER JOIN 
    RATE_SERVICE RS ON RS.RATE_SERVICE_GID = RG.RATE_SERVICE_GID INNER JOIN
    X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN 
    REGION RE1 ON RE1.REGION_GID = XL.SOURCE_REGION_GID INNER JOIN
    REGION RE2 ON RE2.REGION_GID = XL.DEST_REGION_GID INNER JOIN
    RATE_OFFERING RO ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
    SERVPROV SP ON SP.SERVPROV_GID = RO.SERVPROV_GID INNER JOIN
    LOCATION LO ON SP.SERVPROV_GID = LO.LOCATION_GID
WHERE 1 = 1
AND RG.IS_ACTIVE = 'Y'
AND RG.DOMAIN_NAME = 'NBL/MX'
GROUP BY RS.RATE_SERVICE_GID, RS.RATE_SERVICE_XID, LO.LOCATION_NAME, RE1.REGION_XID
ORDER BY RS.RATE_SERVICE_GID


SELECT RS.RATE_SERVICE_XID AS RATE_SERVICE, RSS.MIN_DRIVE_TIME / 3600 AS MIN_DRIVE_TIME_HOURS, XL.SOURCE_REGION_GID, XL.DEST_REGION_GID 
FROM RATE_GEO RG INNER JOIN  
    RATE_SERVICE RS ON RS.RATE_SERVICE_GID = RG.RATE_SERVICE_GID INNER JOIN 
    RATE_SERVICE_SPEED RSS ON RSS.RATE_SERVICE_GID = RS.RATE_SERVICE_GID INNER JOIN 
    X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN  
    REGION RE1 ON RE1.REGION_GID = XL.SOURCE_REGION_GID INNER JOIN 
    REGION RE2 ON RE2.REGION_GID = XL.DEST_REGION_GID INNER JOIN 
    RATE_OFFERING RO ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN 
    SERVPROV SP ON SP.SERVPROV_GID = RO.SERVPROV_GID INNER JOIN 
    LOCATION LO ON SP.SERVPROV_GID = LO.LOCATION_GID 
WHERE 1 = 1 
AND RG.IS_ACTIVE = 'Y' 
AND RG.DOMAIN_NAME = 'NBL/MX' 
GROUP BY RS.RATE_SERVICE_GID, RS.RATE_SERVICE_XID, RSS.MIN_DRIVE_TIME, RSS.MIN_DRIVE_TIME_UOM_CODE,XL.SOURCE_REGION_GID, XL.DEST_REGION_GID 
ORDER BY RSS.MIN_DRIVE_TIME, XL.SOURCE_REGION_GID, XL.DEST_REGION_GID 