SELECT 
    SH.SHIPMENT_GID, 
    SH.SHIPMENT_XID,
    SH.INDICATOR,
    SR1.SHIPMENT_REFNUM_VALUE AS OR_GROUP,
    SR2.SHIPMENT_REFNUM_VALUE AS CUST_PO,
    SR3.SHIPMENT_REFNUM_VALUE AS SO_NUM,
    SR4.SHIPMENT_REFNUM_VALUE AS IS_PRELOAD,
    SRM1.REMARK_TEXT AS PU_APPOINTMENT,
    SR5.SHIPMENT_REFNUM_VALUE AS DELIVERY_APPOINTMENT,
    L2.LOCATION_GID AS SOURCE_LOCATION_GID,
    L1.LOCATION_XID AS DEST_LOCATION_GID,
    L1.LOCATION_NAME AS DEST_LOC_NAME
FROM SHIPMENT SH INNER JOIN
LOCATION L1 ON SH.DEST_LOCATION_GID = L1.LOCATION_GID INNER JOIN 
SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID AND STATUS_TYPE_GID IN ('NBL.SECURE RESOURCES','NBL/MX.SECURE RESOURCES')INNER JOIN
LOCATION L2 ON SH.SOURCE_LOCATION_GID = L2.LOCATION_GID LEFT JOIN
SHIPMENT_REFNUM SR1 ON SH.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID   = 'NBL.OR_GROUP' LEFT JOIN
SHIPMENT_REFNUM  SR2 ON SH.SHIPMENT_GID = SR2.SHIPMENT_GID AND SR2.SHIPMENT_REFNUM_QUAL_GID   = 'CUST_PO' LEFT JOIN
SHIPMENT_REFNUM  SR3 ON SH.SHIPMENT_GID = SR3.SHIPMENT_GID AND SR3.SHIPMENT_REFNUM_QUAL_GID   = 'SO_NUM' LEFT JOIN
SHIPMENT_REFNUM  SR4 ON SH.SHIPMENT_GID = SR4.SHIPMENT_GID AND SR4.SHIPMENT_REFNUM_QUAL_GID   = 'NBL.IS_PRELOAD' LEFT JOIN
SHIPMENT_REMARK SRM1 ON SH.SHIPMENT_GID = SRM1.SHIPMENT_GID AND SRM1.REMARK_QUAL_GID = 'NBL.PU_APPOINTMENT' LEFT JOIN
SHIPMENT_REFNUM SR5 ON SH.SHIPMENT_GID = SR5.SHIPMENT_GID AND SR5.SHIPMENT_REFNUM_QUAL_GID   = 'NBL.DELIVERY_APPOINTMENT' 
WHERE 1 = 1
AND SH.START_TIME >= SYSDATE+24/24 AND SH.START_TIME <= SYSDATE+48/24
AND SS.STATUS_VALUE_GID  IN ('NBL.SECURE RESOURCES_ACCEPTED','NBL/MX.SECURE RESOURCES_ACCEPTED')
AND SH.SOURCE_LOCATION_GID LIKE '%ORG%'
AND SH.DEST_LOCATION_GID LIKE '%CUS%'
ORDER BY SH.START_TIME DESC
;

/*
WHERE SH.SHIPMENT_GID = 'NBL.NB54125115'
SELECT *
FROM SHIPMENT_REFNUM     
WHERE SHIPMENT_GID = 'NBL/MX.MX5001000048'
*/


---------------------------------------------------------------------------------------


;

SELECT *
FROM SHIPMENT_REMARK     
WHERE SHIPMENT_GID = 'NBL.NB54129488'


SELECT 
SH.SHIPMENT_GID, 
SH.SHIPMENT_XID, 
SH.USER_DEFINED1_ICON_GID AS SHIP_CONFIRMED, 
SR1.REMARK_TEXT AS SHIP_DATE 
FROM SHIPMENT SH LEFT JOIN 
SHIPMENT_REMARK SR1 ON SH.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.REMARK_QUAL_GID = 'SHIP_DATE' 
WHERE 1 = 1 
AND SH.SOURCE_LOCATION_GID LIKE '%ORG%' 
AND SH.DEST_LOCATION_GID LIKE '%CUS%' 
AND SH.USER_DEFINED1_ICON_GID = 'NBL.SHIP_CONFIRMED' 
AND TO_CHAR(SH.UPDATE_DATE,'YYYY-MM-DD') = TO_CHAR(SYSDATE,'YYYY-MM-DD') 
ORDER BY SH.SHIPMENT_GID DESC