---Todo los shipments abiertos de 2026 sin ShipDate
---Fecha de Entrega (Delivery Date)
---Pick Date
---Indicador Ship Confirmation

--Todas las ordenes
--Por Ordenes



SELECT ORDER_RELEASE, 
        SHIPMENT, 
        PU_APPOINTMENT, 
        EARLY_DELIVERY_DATE, 
        SHIP_DATE, 
        SHIP_CONFIRMED, 
        SCHEDULED_APPT, 
        SUM(LINE_PACKAGE_COUNT) AS TOTAL_LINE_SUM
FROM (
        SELECT GLOG_UTIL.REMOVE_DOMAIN(ORE.ORDER_RELEASE_GID) AS ORDER_RELEASE, 
            GLOG_UTIL.REMOVE_DOMAIN(S.SHIPMENT_GID) AS SHIPMENT,
            SR2.REMARK_TEXT AS PU_APPOINTMENT, 
            TO_CHAR(utc.get_local_date(ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS EARLY_DELIVERY_DATE, 
            SR1.REMARK_TEXT AS SHIP_DATE,
            ORE.USER_DEFINED1_ICON_GID AS SCHEDULED_APPT,
            ORE.USER_DEFINED2_ICON_GID AS SHIP_CONFIRMED, 
            ORL.ITEM_PACKAGE_COUNT AS LINE_PACKAGE_COUNT
        FROM ORDER_RELEASE ORE INNER JOIN 
            ORDER_RELEASE_LINE ORL ON ORL.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID LEFT JOIN 
            ORDER_MOVEMENT OM ON ORE.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID LEFT JOIN  
            SHIPMENT S ON S.SHIPMENT_GID = OM.SHIPMENT_GID LEFT JOIN  
            SHIPMENT_REMARK SR1 ON SR1.SHIPMENT_GID = S.SHIPMENT_GID AND SR1.REMARK_QUAL_GID = 'SHIP_DATE' LEFT JOIN
            SHIPMENT_REMARK SR2 ON SR2.SHIPMENT_GID = S.SHIPMENT_GID AND SR2.REMARK_QUAL_GID = 'NBL.PU_APPOINTMENT'  
        WHERE 1 = 1   
        AND ORE.INSERT_DATE BETWEEN TO_DATE('2026-02-01', 'YYYY-MM-DD') AND TO_DATE('2026-02-10', 'YYYY-MM-DD') 
        AND ORE.DOMAIN_NAME = 'NBL/MX'  
) T 
GROUP BY ORDER_RELEASE, 
        SHIPMENT, 
        PU_APPOINTMENT, 
        EARLY_DELIVERY_DATE, 
        SHIP_DATE, 
        SHIP_CONFIRMED, 
        SCHEDULED_APPT
        ;