SELECT S.SERVPROV_XID,
L.LOCATION_NAME,
S.SCAC_GID,
C.EMAIL_ADDRESS
FROM SERVPROV S INNER JOIN 
CONTACT C ON S.SERVPROV_GID = C.CONTACT_GID INNER JOIN
LOCATION L ON S.SERVPROV_GID = L.LOCATION_GID INNER JOIN
SHIPMENT SH ON SH.SERVPROV_GID = S.SERVPROV_GID
WHERE SH.DOMAIN_NAME = 'NBL/MX'
AND TO_CHAR(SH.INSERT_DATE, 'YYYY-MM-DD') >= '2024-09-01'
GROUP BY S.SERVPROV_XID, L.LOCATION_NAME, S.SCAC_GID, C.EMAIL_ADDRESS
;

--AND S.SERVPROV_GID = 'NBL.CAR-2198423'


SELECT * FROM CONTACT WHERE CONTACT_GID = 'NBL.CAR-2198423';