select order_release_gid,packaged_item_gid,substr(packaged_item_gid,5,3) as "Shipping_Org"
from order_release_line 
where order_release_gid='NBL.41102321'
group by order_release_gid,packaged_item_gid,substr(packaged_item_gid,5,3);






SELECT 
    O.ORDER_RELEASE_GID, 
    L.ORDER_RELEASE_LINE_GID,
    L.PACKAGED_ITEM_GID, 
    O.SOURCE_LOCATION_GID,
        SUBSTR(O.SOURCE_LOCATION_GID, 9, 3) AS "SOURCE_ORG",
    SUBSTR(L.PACKAGED_ITEM_GID, 5, 3) AS "PACKAGED_ITEM_ORG"
FROM ORDER_RELEASE O INNER JOIN 
ORDER_RELEASE_LINE L ON L.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
WHERE O.ORDER_RELEASE_GID IN ( 
        SELECT 
            ORE.ORDER_RELEASE_GID
        FROM ORDER_RELEASE ORE INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
        WHERE 1 = 1
        AND SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) <> SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3)
        AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
        AND ORE.DOMAIN_NAME = 'NBL'
        AND ORE.ORDER_RELEASE_GID NOT LIKE '%TONU%'
    )
ORDER BY O.ORDER_RELEASE_GID
;


SELECT 
    ORE.ORDER_RELEASE_GID,
    ORL.ORDER_RELEASE_LINE_GID,
    ORL.PACKAGED_ITEM_GID, 
    SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) AS "Shipping_Org",
    ORE.SOURCE_LOCATION_GID,
    SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3) AS "Source_Loc_Org"
FROM ORDER_RELEASE ORE INNER JOIN
    ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
WHERE 1 = 1
AND SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) <> SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3)
AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
AND ORE.ORDER_RELEASE_GID = 'NBL.41102321';





SELECT 
    O.ORDER_RELEASE_GID, 
    L.ORDER_RELEASE_LINE_GID,
    L.PACKAGED_ITEM_GID, 
    O.SOURCE_LOCATION_GID,
        SUBSTR(O.SOURCE_LOCATION_GID, 9, 3) AS "SOURCE_ORG",
    SUBSTR(L.PACKAGED_ITEM_GID, 5, 3) AS "PACKAGED_ITEM_ORG"
FROM ORDER_RELEASE O INNER JOIN 
ORDER_RELEASE_LINE L ON L.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
WHERE O.ORDER_RELEASE_GID IN ( 
        SELECT 
            ORE.ORDER_RELEASE_GID
        FROM ORDER_RELEASE ORE INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
        WHERE 1 = 1
        AND SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) <> SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3)
        AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
        AND ORE.DOMAIN_NAME = 'NBL'
    )
ORDER BY O.ORDER_RELEASE_GID