ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS';
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';
ALTER SESSION SET TIME_ZONE = 'America/Mexico_City';

SELECT SR.SERVPROV_GID, L.LOCATION_NAME, SC.SCAC_XID, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, SR.OUT_XML_PROFILE_GID, LR.LOCATION_REFNUM_QUAL_GID, 
LR.LOCATION_REFNUM_VALUE, SR.INSERT_DATE, SR.UPDATE_DATE
FROM SERVPROV SR INNER JOIN
    LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID INNER JOIN
    RATE_OFFERING RO ON RO.SERVPROV_GID = SR.SERVPROV_GID LEFT JOIN
    LOCATION_REFNUM LR ON L.LOCATION_GID = LR.LOCATION_GID AND LR.LOCATION_REFNUM_QUAL_GID = 'SC' LEFT JOIN
    SCAC SC ON SC.SCAC_GID = SR.SCAC_GID
WHERE RO.DOMAIN_NAME = 'NBL/MX'
--AND RO.IS_ACTIVE = 'Y' 
--GROUP BY SR.SERVPROV_GID, L.LOCATION_NAME, SC.SCAC_XID, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, SR.OUT_XML_PROFILE_GID, LR.LOCATION_REFNUM_QUAL_GID, LR.LOCATION_REFNUM_VALUE, SR.INSERT_DATE, SR.UPDATE_DATE
ORDER BY L.LOCATION_NAME;

SELECT * FROM LOCATION_REFNUM_QUAL
WHERE LOCATION_REFNUM_QUAL_GID = 'SC';



-------ServProv Activos-----------------------------------------------

ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';
ALTER SESSION SET TIME_ZONE = 'America/Mexico_City';

SELECT SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS SC, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, 
SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID INNER JOIN
RATE_OFFERING RO ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
RATE_GEO RG ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID LEFT JOIN
SCAC SC ON SC.SCAC_GID = SR.SCAC_GID LEFT JOIN   
SERVPROV_ALIAS SA ON SA.SERVPROV_GID = SR.SERVPROV_GID AND SERVPROV_ALIAS_QUAL_GID = 'SC'
WHERE RO.DOMAIN_NAME = 'NBL/MX'
AND RO.IS_ACTIVE = 'Y'
--AND RG.IS_ACTIVE = 'Y'
--AND SC.SCAC_XID IS NULL
AND SR.SERVPROV_GID IN (SELECT I.SERVPROV_GID
                        FROM INVOICE I INNER JOIN
                        INVOICE_STATUS ISTAT ON ISTAT.INVOICE_GID  = I.INVOICE_GID AND ISTAT.STATUS_TYPE_GID = 'NBL/MX.MATCH' AND STATUS_VALUE_GID IN ('NBL/MX.MATCH_MATCHED_AUTO', 'NBL/MX.MATCH_FAILED')
                        WHERE TRUNC(ISTAT.UPDATE_DATE) BETWEEN '01/01/2024' AND '10/06/2024'
)
GROUP BY SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE
ORDER BY L.LOCATION_NAME;




---------------ServProv Activos 2025-----------------------------------
SELECT * FROM (
SELECT SERVPROV, RAZON_SOCIAL, NVL(SCAC, ' ') SCAC, NVL(SC, ' ') SC, TARIFA_ACTIVA
FROM (
    SELECT SERVPROV_XID SERVPROV, RAZON_SOCIAL, SCAC, SC, IS_ACTIVE TARIFA_ACTIVA, ROW_NUMBER() OVER(PARTITION BY SERVPROV_XID, RAZON_SOCIAL, SCAC, SC ORDER BY SERVPROV_XID, IS_ACTIVE DESC) AS CON_TARIFA
    FROM (
        SELECT SR.SERVPROV_XID, 
            L.LOCATION_NAME RAZON_SOCIAL, 
            SC.SCAC_XID SCAC, 
            SA.ALIAS SC, 
            --SR.MATCH_RULE_PROFILE_GID, 
            --SR.AUTO_APPROVE_RULE_PROFILE_GID, 
            --SR.ALLOCATION_RULE_PROFILE_GID, 
            --SR.LINE_APPROVE_TOL_PROFILE_GID, 
            --SR.OUT_XML_PROFILE_GID, 
            --SR.INSERT_DATE, 
            --SR.UPDATE_DATE
            RO.IS_ACTIVE
        FROM SERVPROV SR INNER JOIN
        LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID INNER JOIN
        RATE_OFFERING RO ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
        RATE_GEO RG ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID LEFT JOIN
        SCAC SC ON SC.SCAC_GID = SR.SCAC_GID LEFT JOIN   
        SERVPROV_ALIAS SA ON SA.SERVPROV_GID = SR.SERVPROV_GID AND SERVPROV_ALIAS_QUAL_GID = 'SC'
        WHERE RO.DOMAIN_NAME = 'NBL/MX'
        --AND RO.IS_ACTIVE = 'Y'
        --AND RG.IS_ACTIVE = 'Y'
        --AND SC.SCAC_XID IS NULL
        GROUP BY SR.SERVPROV_XID, 
                L.LOCATION_NAME, 
                SC.SCAC_XID, 
                SA.ALIAS, 
                --SR.MATCH_RULE_PROFILE_GID, 
                --SR.AUTO_APPROVE_RULE_PROFILE_GID, 
                --SR.ALLOCATION_RULE_PROFILE_GID, 
                --SR.LINE_APPROVE_TOL_PROFILE_GID, 
                --SR.OUT_XML_PROFILE_GID, 
                RO.IS_ACTIVE
        ORDER BY L.LOCATION_NAME
    ) T
) T2
WHERE CON_TARIFA = 1
AND SERVPROV NOT LIKE '%SPOT_BID%'
ORDER BY RAZON_SOCIAL
) T3
WHERE TARIFA_ACTIVA = 'Y'
;
/*
, ROW_NUMBER() over(PARTITION BY O.IS_ACTIVE) AS CON_TARIFA
*/



SELECT *
FROM SCAC
WHERE SCAC_XID = 'TARF';

SELECT ISTAT.STATUS_VALUE_GID, I.SERVPROV_GID 
FROM INVOICE I INNER JOIN
INVOICE_STATUS ISTAT ON ISTAT.INVOICE_GID  = I.INVOICE_GID AND ISTAT.STATUS_TYPE_GID = 'NBL/MX.MATCH' AND STATUS_VALUE_GID IN ('NBL/MX.MATCH_MATCHED_AUTO', 'NBL/MX.MATCH_FAILED')-- AND STATUS_VALUE_GID IN ('NBL/MX.APPROVAL_APPROVED_MANUAL', 'NBL/MX.APPROVAL_APPROVED_AUTO')
WHERE TRUNC(ISTAT.UPDATE_DATE) BETWEEN '01/04/2024' AND '8/05/2024'
AND I.DOMAIN_NAME = 'NBL/MX';
--GROUP BY STATUS_VALUE_GID



------------ServProv---------------------------------------------------
-------Provedores para CrossBorder-------------------------------------

--ServProv
SELECT *
FROM SERVPROV
WHERE SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                       'CAR-4705721','CAR-3850506','CAR-4746484','CAR-4732409','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506')
ORDER BY SERVPROV_XID;

SELECT SR.DOMAIN_NAME, SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS SC, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, 
SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID LEFT JOIN
SCAC SC ON SC.SCAC_GID = SR.SCAC_GID LEFT JOIN   
SERVPROV_ALIAS SA ON SA.SERVPROV_GID = SR.SERVPROV_GID AND SERVPROV_ALIAS_QUAL_GID = 'SC'
WHERE SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                       'CAR-4705721','CAR-3850506','CAR-4746484','CAR-4732409','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506')
GROUP BY SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, 
         SR.LINE_APPROVE_TOL_PROFILE_GID, SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE,SR.DOMAIN_NAME
ORDER BY L.LOCATION_NAME;

SELECT SR.DOMAIN_NAME, SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS SC, LF.LOCATION_REFNUM_VALUE CARNM, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, 
SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID INNER JOIN
RATE_OFFERING RO ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
RATE_GEO RG ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID LEFT JOIN
SCAC SC ON SC.SCAC_GID = SR.SCAC_GID LEFT JOIN   
SERVPROV_ALIAS SA ON SA.SERVPROV_GID = SR.SERVPROV_GID AND SERVPROV_ALIAS_QUAL_GID = 'SC' LEFT JOIN
LOCATION_REFNUM LF ON LF.LOCATION_GID = SR.SERVPROV_GID AND LOCATION_REFNUM_QUAL_GID = 'CARNM'
WHERE /*RO.DOMAIN_NAME = 'NBL'
AND */ RO.IS_ACTIVE = 'Y'
--AND RG.IS_ACTIVE = 'Y'
--AND SC.SCAC_XID IS NULL
/*AND SR.SERVPROV_GID IN (SELECT I.SERVPROV_GID
                        FROM INVOICE I INNER JOIN
                        INVOICE_STATUS ISTAT ON ISTAT.INVOICE_GID  = I.INVOICE_GID --AND ISTAT.STATUS_TYPE_GID = 'NBL.MATCH' AND STATUS_VALUE_GID IN ('NBL.MATCH_MATCHED_AUTO', 'NBL.MATCH_FAILED') 
                        INNER JOIN
                        SERVPROV SERV ON SERV.SERVPROV_GID = I.SERVPROV_GID 
                        WHERE TRUNC(ISTAT.UPDATE_DATE) BETWEEN '01/12/2023' AND '10/05/2024'
                        AND SERV.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                                               'CAR-4705721','CAR-3850506','CAR-4746484','CAR-4732409','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506') 
)*/
AND SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4749539','CAR-4519508','CAR-4705721','CAR-4746484','CAR-4732409','CAR-4749540','CAR-4749575','CAR-3853507','CAR-2962496','CAR-4737486','CAR-2990506','CAR-3811506','CAR-2541148','CAR-4002504','CAR-4733476','CAR-4751476','CAR-2693280','CAR-2198423')
/*AND SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                       'CAR-4705721','CAR-3850506','CAR-4746484','CAR-4732409','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506')*/
GROUP BY SR.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, SA.ALIAS, LF.LOCATION_REFNUM_VALUE, SR.MATCH_RULE_PROFILE_GID, SR.AUTO_APPROVE_RULE_PROFILE_GID, SR.ALLOCATION_RULE_PROFILE_GID, SR.LINE_APPROVE_TOL_PROFILE_GID, 
         SR.OUT_XML_PROFILE_GID, SR.INSERT_DATE, SR.UPDATE_DATE, SR.DOMAIN_NAME
ORDER BY L.LOCATION_NAME;

SELECT I.SERVPROV_GID
FROM INVOICE I INNER JOIN
INVOICE_STATUS ISTAT ON ISTAT.INVOICE_GID  = I.INVOICE_GID AND ISTAT.STATUS_TYPE_GID = 'NBL.MATCH' AND STATUS_VALUE_GID IN ('NBL.MATCH_MATCHED_AUTO', 'NBL.MATCH_FAILED') INNER JOIN
SERVPROV SERV ON SERV.SERVPROV_GID = I.SERVPROV_GID 
WHERE TRUNC(ISTAT.UPDATE_DATE) BETWEEN '01/01/2024' AND '10/05/2024'
AND SERV.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                       'CAR-4705721','CAR-3850506','CAR-4746484','CAR-4732409','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506');
                       
--Rate Offering

SELECT RO.DOMAIN_NAME, RO.RATE_OFFERING_XID, RO.RATE_OFFERING_TYPE_GID, RO.CURRENCY_GID, RO.TRANSPORT_MODE_GID, RO.EQUIPMENT_GROUP_PROFILE_GID, RO.RATE_SERVICE_GID, RO.CAPACITY_GROUP_GID  
FROM RATE_OFFERING RO INNER JOIN
SERVPROV SR ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID
WHERE RO.IS_ACTIVE = 'Y'
AND SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508',
                       'CAR-4705721','CAR-3850506','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506')
ORDER BY L.LOCATION_NAME;

--Regions



--Lanes
--Rate Records

SELECT RG.RATE_GEO_XID, RG.RATE_OFFERING_GID, RG.X_LANE_GID, RG.RATE_SERVICE_GID, RGC.CHARGE_AMOUNT, RGC.CHARGE_CURRENCY_GID, RGC.CHARGE_AMOUNT_BASE
FROM RATE_GEO RG INNER JOIN
RATE_GEO_COST_GROUP RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID  
WHERE RATE_OFFERING_GID IN (
                            SELECT RO.RATE_OFFERING_GID
                            FROM RATE_OFFERING RO INNER JOIN
                            SERVPROV SR ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
                            LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID
                            WHERE RO.IS_ACTIVE = 'Y'
                            AND SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4519508','CAR-4705721','CAR-3850506','CAR-3853507','CAR-29622496','CAR-4737486','CAR-2990506','CAR-3811506')
)
ORDER BY RG.RATE_GEO_XID
;


SELECT RG.RATE_OFFERING_GID, SR.SCAC_GID, L.LOCATION_NAME, RG.RATE_SERVICE_GID
FROM RATE_GEO RG INNER JOIN
RATE_GEO_COST_GROUP RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID  INNER JOIN
RATE_OFFERING RO ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
SERVPROV SR ON SR.SERVPROV_GID = RO.SERVPROV_GID INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID
WHERE RO.RATE_OFFERING_GID IN (
                            SELECT RO.RATE_OFFERING_GID
                            FROM RATE_OFFERING RO INNER JOIN
                            SERVPROV SR ON RO.SERVPROV_GID = SR.SERVPROV_GID INNER JOIN
                            LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID
                            WHERE RO.IS_ACTIVE = 'Y'
                            AND SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4749539','CAR-4519508','CAR-4705721','CAR-4746484','CAR-4732409','CAR-4749540','CAR-4749575','CAR-3853507','CAR-2962496','CAR-4737486','CAR-2990506','CAR-3811506')
)
AND RG.RATE_SERVICE_GID IS NOT NULL
AND RG.DOMAIN_NAME = 'NBL'
GROUP BY RG.RATE_OFFERING_GID, SR.SCAC_GID, L.LOCATION_NAME, RG.RATE_SERVICE_GID
ORDER BY RG.RATE_OFFERING_GID
;




INSERT INTO shipment_refnum (shipment_gid,shipment_refnum_qual_gid,shipment_refnum_value,domain_name) 
select shipment_gid, remark_qual_gid, remark_text, domain_name from shipment_remark s where shipment_gid = $gid and remark_qual_gid = 'NBL.PU_APPOINTMENT'and exists( select 1 from shipment_remark r where r.remark_qual_gid = 'NBL.PU_APPOINTMENT' and r.shipment_gid = s.shipment_gid);

INSERT INTO shipment_refnum (shipment_gid,shipment_refnum_qual_gid,shipment_refnum_value,domain_name) select shipment_gid, remark_qual_gid, remark_text, domain_name from shipment_remark s where shipment_gid = $gid and remark_qual_gid = 'NBL.PU_APPOINTMENT'and exists( select 1 from shipment_remark r where r.remark_qual_gid = 'NBL.PU_APPOINTMENT' and r.shipment_gid = s.shipment_gid);

select SHIPMENT_GID from shipment where user_defined3_icon_gid in ('NBL.CAR_SCHEDULED_APPT','NBL.NBL_SCHEDULED_APPT','NBL.NBL_PENDING_APPT') AND SHIPMENT_GID = 'NBL.NB32133884';



/*
SELECT *
FROM GL_USER
SERVPROV
LOCARTION
*/

SELECT SR.SERVPROV_XID, L.LOCATION_NAME, US.USERNAME
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID LEFT JOIN
GL_USER US ON L.LOCATION_NAME = US.GL_USER_XID
WHERE SR.SERVPROV_XID IN ('CAR-4195504','CAR-2261813','CAR-4678506','CAR-2695315','CAR-2683304','CAR-4681845','CAR-2541148','CAR-4566517','CAR-4749539','CAR-4519508','CAR-4705721','CAR-4746484',
'CAR-4732409','CAR-4749540','CAR-4749575','CAR-3853507','CAR-2962496','CAR-4737486','CAR-2990506','CAR-3811506','CAR-2541148','CAR-4002504','CAR-4733476','CAR-4751476','CAR-2693280','CAR-2198423');

SELECT SR.SERVPROV_XID, L.LOCATION_NAME, US.USERNAME
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID LEFT JOIN
GL_USER US ON L.LOCATION_NAME = US.GL_USER_XID
WHERE US.USERNAME = 'MOCORTES';

SELECT SR.SERVPROV_XID, L.LOCATION_NAME, US.USERNAME, CO.EMAIL_ADDRESS
FROM SERVPROV SR INNER JOIN
LOCATION L ON SR.SERVPROV_GID = L.LOCATION_GID LEFT JOIN
GL_USER US ON L.LOCATION_NAME = US.GL_USER_XID LEFT JOIN
CONTACT CO ON CO.CONTACT_GID = SR.SERVPROV_GID
WHERE SR.SERVPROV_GID IN 
('NBL.CAR-4195504','NBL.CAR-2261813','NBL.CAR-2695315','NBL.CAR-4678506','NBL.CAR-2198423',
'NBL.CAR-2683304','NBL.CAR-4681845','NBL.CAR-2541148','NBL.CAR-4566517','NBL.CAR-4519508',
'NBL.CAR-4749539','NBL.CAR-3811506','NBL.CAR-4002504','NBL.CAR-4733476','NBL.CAR-4749540',
'NBL.CAR-3853507','NBL.CAR-2962496','NBL.CAR-2990506','NBL.CAR-2693280','NBL.CAR-4705721',
'NBL.CAR-4737486','NBL.CAR-4749575','NBL.CAR-4733462','NBL.CAR-4751476')
ORDER BY L.LOCATION_NAME;



SELECT * FROM CONTACT WHERE CONTACT_XID  = 'CAR-2261813';





