SELECT *
FROM BULK_PLAN
WHERE INSERT_USER LIKE '%FLORES%'
AND TO_CHAR(INSERT_DATE, 'DD/MM/YYYY') >= '01/06/2025'





SELECT     
    SELECT BULK_PLAN_GID, 
    START_TIME, 
    END_TIME,
    extract(minute from interval) Minutes, 
    NUM_OF_ORDERS_SELECTED,
    NUM_OF_ORDERS_UNASSIGNED,
    NUM_OF_ORDERS_PLANNED,
    NUM_OF_SHIPMENTS_BUILT,
    NUM_ORDERS_PLANNED_FAILED,
    STATE,
    SINCE,
    TERMINATION_TIME
FROM (
    SELECT BULK_PLAN_GID, 
    START_TIME, 
    END_TIME,
    --DATEDIFF(minute, START_TIME, END_TIME) DURATION,
    numtodsinterval(END_TIME - START_TIME, day) interval,
    NUM_OF_ORDERS_SELECTED,
    NUM_OF_ORDERS_UNASSIGNED,
    NUM_OF_ORDERS_PLANNED,
    NUM_OF_SHIPMENTS_BUILT,
    NUM_ORDERS_PLANNED_FAILED,
    STATE,
    SINCE,
    TERMINATION_TIME
    FROM BULK_PLAN
    WHERE INSERT_USER LIKE '%CEFLORES%'
    AND TO_CHAR(INSERT_DATE, 'DD/MM/YYYY') >= '01/06/2025'
) A
