SELECT SHIPMENT_GID, INVOICE_GID
FROM (
        SELECT ISH.INVOICE_GID, SH.SHIPMENT_GID, COUNT(ORL.ORDER_RELEASE_GID) COUNT
        FROM ORDER_RELEASE ORL INNER JOIN 
        ORDER_MOVEMENT OM ON ORL.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN 
        SHIPMENT SH ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
        SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID  
                            AND SS.STATUS_TYPE_GID = 'NBL.PAYMENT' AND SS.STATUS_VALUE_GID = 'NBL.PAYMENT_VOUCHERED' INNER JOIN 
        INVOICE_SHIPMENT ISH ON SH.SHIPMENT_GID = ISH.SHIPMENT_GID INNER JOIN
        INVOICE_LINEITEM  ILI ON ISH.INVOICE_GID = ILI.INVOICE_GID 
        WHERE SH.INSERT_DATE BETWEEN TO_DATE('2025-10-01','YYYY-MM-DD') AND TO_DATE('2025-10-10','YYYY-MM-DD') 
        AND SH.DOMAIN_NAME = 'NBL'
        GROUP BY ISH.INVOICE_GID, SH.SHIPMENT_GID
        ORDER BY SH.SHIPMENT_GID
    ) T
GROUP BY SHIPMENT_GID, INVOICE_GID
HAVING SUM(COUNT) > 4
; 


SELECT ISH.INVOICE_GID, COUNT(ILI.DESCRIPTION) AS LINE_COUNT
FROM SHIPMENT SH INNER JOIN 
SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID  
                    AND SS.STATUS_TYPE_GID = 'NBL.PAYMENT' AND SS.STATUS_VALUE_GID = 'NBL.PAYMENT_VOUCHERED' INNER JOIN 
INVOICE_SHIPMENT ISH ON SH.SHIPMENT_GID = ISH.SHIPMENT_GID INNER JOIN
INVOICE_LINEITEM  ILI ON ISH.INVOICE_GID = ILI.INVOICE_GID 
WHERE SH.INSERT_DATE BETWEEN TO_DATE('2025-10-01','YYYY-MM-DD') AND TO_DATE('2025-10-20','YYYY-MM-DD') 
AND SH.DOMAIN_NAME = 'NBL'
GROUP BY ISH.INVOICE_GID, ILI.DESCRIPTION
HAVING COUNT(ILI.DESCRIPTION) >= 3