SELECT U.GL_USER_GID, U.GL_USER_XID, U.USERNAME, U.DEFAULT_USER_ROLE_GID, U.LAST_LOGIN_DATE, C.EMAIL_ADDRESS
FROM GL_USER U LEFT JOIN
CONTACT C ON C.GL_USER_GID = U.GL_USER_GID
WHERE U.DOMAIN_NAME = 'NBL/MX'
AND U.EXPIRATION_DATE IS NULL
ORDER BY U.GL_USER_GID, U.LAST_LOGIN_DATE ;