SELECT SHIPMENT_GID,
    TRANSPORT_MODE_GID,
    TOTAL_ACTUAL_COST,
    TOTAL_ACTUAL_COST_BASE,
    T_ACTUAL_COST_CURRENCY_GID,
    LOADED_DISTANCE * 1.609344 LOADED_DISTANCE,
    'KM' LOADED_DISTANCE_UOM_CODE,
    SOURCE_LOCATION_GID,
    DEST_LOCATION_GID,
    START_TIME,
    END_TIME,
    SERVPROV_GID,
    RATE_OFFERING_GID,
    RATE_GEO_GID
FROM SHIPMENT
WHERE TO_CHAR(START_TIME, 'YYYY-MM-DD') >= '2025-03-01'
AND DOMAIN_NAME = 'NBL/MX'
AND RATE_GEO_GID NOT LIKE '%|25'
AND RATE_OFFERING_GID <> 'NBL/MX.CPU'
ORDER BY SHIPMENT_GID;


SHIPMENT_GID,
TRANSPORT_MODE_GID,
TOTAL_ACTUAL_COST,
TOTAL_ACTUAL_COST_BASE,
T_ACTUAL_COST_CURRENCY_GID,
LOADED_DISTANCE,
LOADED_DISTANCE_UOM_CODE,
SOURCE_LOCATION_GID,
DEST_LOCATION_GID,
START_TIME,
END_TIME,
SERVPROV_GID,
RATE_OFFERING_GID,
RATE_GEO_GID


MX51005351





SELECT SHIPMENT_COST_SEQNO, 
SHIPMENT_COST_SEQNO,
SHIPMENT_GID,
COST_TYPE,
COST,
COST_GID,
COST_BASE,
ACCESSORIAL_CODE_GID,
ACCESSORIAL_COST_GID,
DOMAIN_NAME,
INSERT_USER,
INSERT_DATE,
UPDATE_USER,
UPDATE_DATE
FROM SHIPMENT_COST
WHERE SHIPMENT_GID IN ('NBL/MX.MX51056850','NBL/MX.MX51042407','NBL/MX.MX51055880','NBL/MX.MX51054704','NBL/MX.MX51056888','NBL/MX.MX51056840')
ORDER BY SHIPMENT_GID;