SELECT L.LOCATION_XID, L.LOCATION_NAME, L.CITY, L.PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.TIME_ZONE_GID, L.LAT, L.LON
FROM RATE_GEO RG INNER JOIN
    RATE_OFFERING RO ON RO.RATE_OFFERING_GID   = RG.RATE_OFFERING_GID INNER JOIN
    X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN
    REGION_DETAIL RD ON RD.REGION_GID = XL.DEST_REGION_GID INNER JOIN
    LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RO.RATE_OFFERING_GID = 'NBL/MX.FEMSA'
AND RG.IS_ACTIVE = 'Y'
--AND L.LOCATION_XID LIKE 'CUS%'
GROUP BY L.LOCATION_XID, L.LOCATION_NAME, L.CITY, L.PROVINCE, L.PROVINCE_CODE, L.POSTAL_CODE, L.COUNTRY_CODE3_GID, L.TIME_ZONE_GID, L.LAT, L.LON
ORDER BY L.PROVINCE_CODE, L.CITY,L.LOCATION_XID;