
SELECT DISTINCT 
    ITN.OBJECT_GID,
    ITM.EXTERNAL_STATUS, 
    ITN.ELEMENT_NAME, 
    IACK.ACK_STATUS 
FROM I_transaction ITN INNER JOIN 
I_TRANSMISSION ITM ON ITN.I_TRANSMISSION_NO = ITM.I_TRANSMISSION_NO INNER JOIN
I_TRANSMISSION_ACK IACK ON ITN.I_TRANSMISSION_NO = IACK.I_TRANSMISSION_NO
WHERE ITM.IS_INBOUND='N' 
AND ITM.INSERT_DATE > SYSDATE-1/24  
AND itn.ELEMENT_NAME ='PlannedShipment' 
and ITM.EXTERNAL_SYSTEM_GID IN ('NBL.XXNBLWSHRECEIVEPSHIPMENTFROMOTM_V63') 
AND ITN.TRANSACTION_CODE != 'D'
AND (ITM.insert_date >= :P_CREATION_DATE_FROM OR  :P_CREATION_DATE_FROM IS NULL)


--------------Final--------------------------------------------------------------------------------------------
SELECT * 
FROM (
    SELECT I_TRANSMISSION_NO,
            OBJECT_GID,
            EXTERNAL_STATUS, 
            ELEMENT_NAME, 
            ACK_STATUS,
            ACK_REASON,
            REF_TRANSACTION_NO,
            SOURCE_LOCATION_GID
    FROM (
        SELECT DISTINCT 
            ITN.I_TRANSMISSION_NO,
            ITN.OBJECT_GID,
            ITM.EXTERNAL_STATUS, 
            ITN.ELEMENT_NAME, 
            IACK.ACK_STATUS,
            IACK.ACK_REASON,
            IACK.REF_TRANSACTION_NO,
            ORE.SOURCE_LOCATION_GID,
            IACK.INSERT_DATE, 
            ROW_NUMBER() 
            OVER (
                    PARTITION BY ITN.OBJECT_GID 
                    ORDER BY IACK.INSERT_DATE DESC
                ) as RN
        FROM I_transaction ITN INNER JOIN 
            I_TRANSMISSION ITM ON ITN.I_TRANSMISSION_NO = ITM.I_TRANSMISSION_NO INNER JOIN
            I_TRANSMISSION_ACK IACK ON ITN.I_TRANSMISSION_NO = IACK.I_TRANSMISSION_NO INNER JOIN
            SHIPMENT SH ON SH.SHIPMENT_GID = ITN.OBJECT_GID INNER JOIN
            ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN
            ORDER_RELEASE ORE ON ORE.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN
            TENDER_COLLABORATION TC ON TC.SHIPMENT_GID = SH.SHIPMENT_GID  INNER JOIN
            TENDER_COLLAB_SERVPROV TCS ON TCS.I_TRANSACTION_NO = TC.I_TRANSACTION_NO  
        WHERE ITM.IS_INBOUND = 'N' 
        AND ITM.INSERT_DATE > SYSDATE-48/24  
        AND itn.ELEMENT_NAME = 'PlannedShipment' 
        and ITM.EXTERNAL_SYSTEM_GID 
            IN ('NBL.XXNBLWSHRECEIVEPSHIPMENTFROMOTM_V63') 
        AND ITN.TRANSACTION_CODE != 'D'
        AND IACK.ACK_STATUS != 'IN PROGRESS'
        AND SH.SOURCE_LOCATION_GID = ORE.SOURCE_LOCATION_GID
        AND ORE.SOURCE_LOCATION_GID LIKE 'NBL.ORG%'
        AND TCS.ACCEPTANCE_CODE = 'A'
    ) T
    WHERE RN = 1
) S
WHERE ACK_STATUS = 'ERROR'
AND ACK_REASON LIKE 'Unexpected Error in WSH_OTM_INBOUND_GRP.initiate_planned_shipment API. Interface to WSH Failed%'
------------------------------------------------------------------------------------------------------------------------------------

--AND (ITM.insert_date >= TO_DATE('2025-01-05','YYYY-MM-DD'))

SELECT TCS.* FROM TENDER_COLLABORATION TC INNER JOIN
TENDER_COLLAB_SERVPROV  tcs ON TCS.I_TRANSACTION_NO  = TC.I_TRANSACTION_NO  
WHERE SHIPMENT_GID = 'NBL.NB54124886'

SELECT IACK.* 
FROM  I_transaction ITN INNER JOIN 
      I_TRANSMISSION ITM ON ITN.I_TRANSMISSION_NO = ITM.I_TRANSMISSION_NO INNER JOIN
      I_TRANSMISSION_ACK IACK ON ITN.I_TRANSMISSION_NO = IACK.I_TRANSMISSION_NO 
WHERE OBJECT_GID = 'NBL.NB54123113';