INSERT INTO SHIPMENT_REFNUM (SHIPMENT_GID, SHIPMENT_REFNUM_QUAL_GID, SHIPMENT_REFNUM_VALUE, DOMAIN_NAME) 
(select shipment_gid, domain_name ||'.CLAVE_PRODUCTO_SAT', '50202301', domain_name from shipment where shipment_gid = $gid);

SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT', 
CASE 
    WHEN ORL.PACKAGED_ITEM_GID = 'NBL.5272-7167397' THEN '50202300'
    ELSE '50202301'
END CLAVE_CODIGO_SAT,
SH.DOMAIN_NAME   
FROM SHIPMENT SH INNER JOIN 
ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
WHERE SH.SHIPMENT_GID = 'NBL/MX.MX55015508' ;

SELECT SHIPMENT_GID, CLAVE_CODIGO_SAT, DOMAIN_NAME 
FROM ( 

    SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT', 
    CASE 
        WHEN ORL.PACKAGED_ITEM_GID = 'NBL.5272-7167397' THEN '50202300'
        ELSE '50202301'
    END CLAVE_CODIGO_SAT,
    SH.DOMAIN_NAME   
    FROM SHIPMENT SH INNER JOIN 
    ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
    ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
    ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
    WHERE SH.SHIPMENT_GID = 'NBL/MX.MX55015508' 

) T1
GROUP BY SHIPMENT_GID, CLAVE_CODIGO_SAT, DOMAIN_NAME;

SELECT SHIPMENT_GID, CLAVE_CODIGO_SAT, DOMAIN_NAME 
FROM ( 
    SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT', 
    CASE 
        WHEN ORL.PACKAGED_ITEM_GID = 'NBL.5272-7167397' THEN '50202300'
        ELSE '50202301'
    END CLAVE_CODIGO_SAT,
    SH.DOMAIN_NAME   
    FROM SHIPMENT SH INNER JOIN 
    ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
    ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
    ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
    WHERE SH.SHIPMENT_GID = 'NBL/MX.MX55015508' 
) T1
PIVOT (
    COUNT(SHIPMENT_GID)
    FOR SHIPMENT_GID IN ('CLAVE_CODIGO_SAT')
)
GROUP BY SHIPMENT_GID, CLAVE_CODIGO_SAT, DOMAIN_NAME;


SELECT SHIPMENT_GID, REFNUM, DOMAIN_NAME
FROM (
    SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
    FROM CLAVE_SAT
) T
PIVOT (
    COUNT(SHIPMENT_GID)
    FOR REFNUM IN ('CLAVE_CODIGO_SAT')
);


SELECT SHIPMENT_GID, REFNUM, LISTAGG(CLAVE_CODIGO_SAT,'|'), DOMAIN_NAME
FROM (
    SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
    FROM CLAVE_SAT
    GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT,DOMAIN_NAME
    )
GROUP BY SHIPMENT_GID, REFNUM, DOMAIN_NAME;


SELECT SHIPMENT_GID, REFNUM, LISTAGG(CLAVE_CODIGO_SAT,'|'), DOMAIN_NAME
FROM (
        SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
        FROM (
                SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM, 
                CASE 
                    WHEN ORL.PACKAGED_ITEM_GID = 'NBL.5272-7167397' THEN '50202300'
                    ELSE '50202301'
                END CLAVE_CODIGO_SAT,
                SH.DOMAIN_NAME   
                FROM SHIPMENT SH INNER JOIN 
                ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
                ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
                ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
                WHERE SH.SHIPMENT_GID = 'NBL/MX.MX55015508'
        ) T 
        GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME
    )
GROUP BY SHIPMENT_GID, REFNUM, DOMAIN_NAME;


SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM, orl.PACKAGED_ITEM_GID,
CASE 
    WHEN SUBSTR(ORL.PACKAGED_ITEM_GID, INSTR(ORL.PACKAGED_ITEM_GID, '-')+1) IN ('8741403','8742281','8741453','8741625', '8735963') THEN '50202300'
    ELSE '50202301'
END CLAVE_CODIGO_SAT,
SH.DOMAIN_NAME   
FROM SHIPMENT SH INNER JOIN 
ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
WHERE SH.SHIPMENT_GID IN ('NBL/MX.MX55015623','NBL/MX.MX55015624');

SELECT SUBSTR(PACKAGED_ITEM_GID, INSTR(PACKAGED_ITEM_GID, '-')-1) output
FROM PACKAGED_ITEM
WHERE PACKAGED_ITEM_GID LIKE '%8735963';

------

INSERT INTO SHIPMENT_REFNUM (SHIPMENT_GID, SHIPMENT_REFNUM_QUAL_GID, SHIPMENT_REFNUM_VALUE, DOMAIN_NAME) 
(select shipment_gid, domain_name ||'.CLAVE_PRODUCTO_SAT', '50202301', domain_name from shipment where shipment_gid = $gid);


INSERT INTO SHIPMENT_REFNUM (SHIPMENT_GID, SHIPMENT_REFNUM_QUAL_GID, SHIPMENT_REFNUM_VALUE, DOMAIN_NAME) 
(SELECT SHIPMENT_GID, REFNUM, LISTAGG(CLAVE_CODIGO_SAT,'|'), DOMAIN_NAME
FROM ( 
        SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME 
        FROM ( 
                SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM, 
                CASE 
                    WHEN SUBSTR(ORL.PACKAGED_ITEM_GID, INSTR(ORL.PACKAGED_ITEM_GID, '-')+1) IN ('8741403','8742281','8741453','8741625', '8735963') THEN '50202300' 
                    ELSE '50202301' 
                END CLAVE_CODIGO_SAT, 
                SH.DOMAIN_NAME   
                FROM SHIPMENT SH INNER JOIN  
                ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN  
                ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
                ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
                WHERE SH.SHIPMENT_GID = $gid 
        ) T  
        GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME 
    ) 
GROUP BY SHIPMENT_GID, REFNUM, DOMAIN_NAME) 
;


'8741403','8742281','8741453','8741625' 


SELECT SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME 
FROM ( 
        SELECT SH.SHIPMENT_GID, SH.DOMAIN_NAME || '.CLAVE_PRODUCTO_SAT' REFNUM, 
        CASE 
            WHEN SUBSTR(ORL.PACKAGED_ITEM_GID, INSTR(ORL.PACKAGED_ITEM_GID, '-')+1) IN ('8741403','8742281','8741453','8741625', '8735963') THEN '50202300' 
            ELSE '50202301' 
        END CLAVE_CODIGO_SAT, 
        SH.DOMAIN_NAME   
        FROM SHIPMENT SH INNER JOIN  
        ORDER_MOVEMENT OM ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN  
        ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
        ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
        WHERE SH.SHIPMENT_GID IN ('NBL/MX.MX55015623','NBL/MX.MX55015624') 
) T   
GROUP BY SHIPMENT_GID, REFNUM, CLAVE_CODIGO_SAT, DOMAIN_NAME 


38438328,38438330