SELECT *
FROM ORDER_RELEASE
WHERE TO_CHAR(INSERT_DATE, 'YYYY-MM-DD') = '2024-10-18'
AND DOMAIN_NAME = 'NBL/MX'


SELECT ORDER_RELEASE_GID 
FROM ORDER_RELEASE 
WHERE TO_CHAR(INSERT_DATE, 'YYYY-MM-DD') = '2024-10-18'
AND ((ORDER_RELEASE_TYPE_GID NOT IN ('NBL.TONU','NBL.SHUTTLE') 
and (INSTR(ORDER_RELEASE_GID,'TONU')<= 0)) OR ORDER_RELEASE_TYPE_GID IS NULL)