--SAN|3MZ_SHIPPING_REGION,DAL|3MZ_SHIPPING_REGION,RIA|3MX_SHIPPING_REGION,PHI|3MX_SHIPPING_REGION,N10|3MX_SHIPPING_REGION,RIA|3TJ_SHIPPING_REGION,PHI|3TJ_SHIPPING_REGION,N10|3TJ_SHIPPING_REGION
--3MZ_SHIPPING_REGION,3MX_SHIPPING_REGION,3TJ_SHIPPING_REGION

SELECT RG.* 
FROM RATE_GEO RG INNER JOIN
X_LANE XL ON RG.X_LANE_GID = XL.X_LANE_GID
WHERE RG.IS_ACTIVE = 'Y'
AND XL.DEST_REGION_GID IN ('NBL.3MZ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION')


SELECT RG.* FROM RATE_GEO RG INNER JOIN X_LANE XL ON RG.X_LANE_GID = XL.X_LANE_GID WHERE RG.IS_ACTIVE = 'Y' AND XL.DEST_REGION_GID IN ('NBL.3MZ_SHIPPING_REGION','NBL.3MX_SHIPPING_REGION','NBL.3TJ_SHIPPING_REGION')



MX55015354,MX55015351