SELECT SH.SHIPMENT_XID,
SH.SERVPROV_GID, 
RC1.CHARGE_AMOUNT AS ACTUAL_CHARGE_AMOUNT_BASE,
RC2.CHARGE_AMOUNT AS PLANNED_CHARGE_AMOUNT_BASE,
SH.PLANNED_SERVPROV_GID,
SH.RATE_OFFERING_GID, 
SH.PLANNED_RATE_OFFERING_GID,
SH.RATE_GEO_GID, 
SH.PLANNED_RATE_GEO_GID,
SH.TOTAL_ACTUAL_COST , 
SH.PLANNED_COST,
SH.TOT_MATCHED_INVOICE_COST,
SH.ORIGINAL_INVOICE_COST,
SH.TOTAL_APPROVED_COST,
SH.DOMAIN_NAME,
SH.INSERT_USER,
SH.INSERT_DATE,
SH.UPDATE_USER,
SS.STATUS_TYPE_GID,
SS.STATUS_VALUE_GID
FROM SHIPMENT SH INNER JOIN
SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID 
                    AND STATUS_TYPE_GID = 'NBL/MX.PAYMENT' AND STATUS_VALUE_GID = 'NBL/MX.PAYMENT_VOUCHERED' INNER JOIN
RATE_GEO_COST RC1 ON RC1.RATE_GEO_COST_GROUP_GID = SH.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RC2 ON RC2.RATE_GEO_COST_GROUP_GID = SH.PLANNED_RATE_GEO_GID
WHERE SH.INSERT_DATE BETWEEN TO_DATE('2025-10-06','YYYY-MM-DD') AND TO_DATE('2025-10-10','YYYY-MM-DD')
AND SH.SERVPROV_GID <> PLANNED_SERVPROV_GID
AND SH.DOMAIN_NAME = 'NBL/MX'
AND SH.SHIPMENT_XID = 'MX51089008'
ORDER BY SH.SHIPMENT_XID;

RATE_GEO_GID

SELECT * 
FROM RATE_GEO_COST_GROUP
WHERE RATE_GEO_GID = 'NBL/MX.MEXAMERIK|GDL|CULIACAN|25';