SELECT ORE.ORDER_RELEASE_GID
FROM ORDER_RELEASE ORE INNER JOIN 
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN 
LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID INNER JOIN 
TIME_ZONE TZ ON TZ.time_zone_gid = LOC.time_zone_gid  
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'  
AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL')  
AND ORE.DOMAIN_NAME = 'NBL/MX'  
AND UTC.GET_LOCAL_DATE (ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) BETWEEN 
CAST(FROM_TZ(CAST(SYSDATE - 7 AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)
AND CAST(FROM_TZ(CAST(SYSDATE AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)
GROUP BY ORE.ORDER_RELEASE_GID

SELECT SUM(Suma)
FROM (
SELECT COUNT(ORE.ORDER_RELEASE_GID) Suma--, ORE.EARLY_DELIVERY_DATE, ORS.STATUS_VALUE_GID
FROM ORDER_RELEASE ORE INNER JOIN 
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN 
LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID INNER JOIN 
TIME_ZONE TZ ON TZ.time_zone_gid = LOC.time_zone_gid  
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'  
AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL')  
AND ORE.DOMAIN_NAME = 'NBL/MX'  
AND UTC.GET_LOCAL_DATE (ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) BETWEEN 
CAST(FROM_TZ(CAST(SYSDATE - 7 AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)
AND CAST(FROM_TZ(CAST(SYSDATE AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)
GROUP BY ORE.ORDER_RELEASE_GID
) T
GROUP BY Suma
