SELECT *
FROM SHIP_TENDER_COLLAB_BOV 
WHERE SHIPMENT_GID = 'NBL/MX.MX5001000058'
WHERE SHIPMENT_GID = 'NBL/MX.MX5001007293'
;

SELECT *
FROM TENDER_COLLABORATION  
WHERE SHIPMENT_GID = 'NBL/MX.MX5001000058'
;

SELECT * 
FROM TENDER_COLLABORATION_STATUS
WHERE I_TRANSACTION_NO IN (807462162,807367277,807463440)
;

SELECT *
FROM TENDER_COLLAB_SERVPROV 
WHERE I_TRANSACTION_NO IN (807462162,807367277,807463440)
;


SELECT TC.I_TRANSACTION_NO,
TC.SHIPMENT_GID,
TC.SHIPMENT_TIME,

FROM TENDER_COLLABORATION TC INNER JOIN
TENDER_COLLABORATION_STATUS TCS ON TC.I_TRANSACTION_NO = TCS.I_TRANSACTION_NO
WHERE TC.SHIPMENT_GID = 'NBL/MX.MX5001000058'
;


SELECT TENDER_SERVPROV_GID, TENDER_SERVPROV_XID, 
COUNT(STATUS_VALUE_XID) AS TOTAL_COUNT,
SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_ACCEPTED' THEN 1 ELSE 0 END) AS ACCEPTED_COUNT,
SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_WITHDRAWN' THEN 1 ELSE 0 END) AS WITHDRAW_COUNT,
SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_DECLINED' THEN 1 ELSE 0 END) AS DECLINED_COUNT,
SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_TIMED OUT' THEN 1 ELSE 0 END) AS TIMED_OUT_COUNT
FROM (
    SELECT SHIPMENT_XID, SHIPMENT_SERVPROV_GID, SHIPMENT_SERVPROV_XID, TENDER_SERVPROV_GID, TENDER_SERVPROV_XID, TENDER_EXPECTED_RESPONSE
    TENDER_ACCEPTANCE_CODE, TENDER_RESPONSE_METHOD, TENDER_DECLINE_REASON_CODE_GID, TENDER_ORIGINAL_PICKUP_TIME,
    STATUS_TYPE_GID, STATUS_VALUE_GID, STATUS_VALUE_XID
    FROM SHIP_TENDER_COLLAB_BOV /*INNER JOIN
    TENDER_COLLABORATION_STATUS TCS ON STV.TENDER_TRANSACTION_NO = TCS.I_TRANSACTION_NO*/
    WHERE TENDER_ORIGINAL_PICKUP_TIME BETWEEN TO_DATE('2026-01-01', 'YYYY-MM-DD') AND TO_DATE('2026-02-18', 'YYYY-MM-DD')
    AND DOMAIN_NAME  = 'NBL/MX'
)
GROUP BY TENDER_SERVPROV_GID, TENDER_SERVPROV_XID
ORDER BY TENDER_SERVPROV_GID
--AND STATUS_VALUE_XID <> 'SECURE RESOURCES_ACCEPTED'

SELECT SHIPMENT_SERVPROV_XID, 
        SERVPROV_NAME, 
        SOURCE, 
        DEST_CITY, 
        WEEK, 
        MONTH, 
        COUNT(STATUS_VALUE_XID) AS TOTAL_COUNT, 
        SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_ACCEPTED' THEN 1 ELSE 0 END) AS ACCEPTED_COUNT, 
        SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_WITHDRAWN' THEN 1 ELSE 0 END) AS WITHDRAW_COUNT, 
        SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_DECLINED' THEN 1 ELSE 0 END) AS DECLINED_COUNT, 
        SUM(CASE WHEN STATUS_VALUE_XID = 'SECURE RESOURCES_TIMED OUT' THEN 1 ELSE 0 END) AS TIMED_OUT_COUNT 
FROM ( 
        SELECT STV.SHIPMENT_XID, 
        STV.SHIPMENT_SERVPROV_XID, 
        LOC.LOCATION_NAME AS SERVPROV_NAME, 
        STV.TENDER_SERVPROV_GID, 
        STV.TENDER_SERVPROV_XID, 
        STV.TENDER_EXPECTED_RESPONSE, 
        TO_CHAR(utc.get_local_date(STV.TENDER_EXPECTED_RESPONSE, LOC3.LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS TENDER_EXPECTED_RESPONSE_LOCALTIME, 
        TO_CHAR(utc.get_local_date(STV.TENDER_ORIGINAL_PICKUP_TIME, LOC3.LOCATION_GID), 'IW') AS WEEK, 
        TO_CHAR(utc.get_local_date(STV.TENDER_ORIGINAL_PICKUP_TIME, LOC3.LOCATION_GID), 'Month') AS MONTH, 
        STV.TENDER_ACCEPTANCE_CODE, 
        STV.TENDER_RESPONSE_METHOD, 
        STV.TENDER_DECLINE_REASON_CODE_GID, 
        STV.TENDER_ORIGINAL_PICKUP_TIME, 
        TO_CHAR(utc.get_local_date(STV.TENDER_ORIGINAL_PICKUP_TIME, LOC2.LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS TENDER_ORIGINAL_PICKUP_TIME_LOCALTIME,  
        STV.STATUS_TYPE_GID, 
        STV.STATUS_VALUE_GID, 
        STV.STATUS_VALUE_XID, 
        LOC3.LOCATION_XID AS SOURCE, 
        LOC2.CITY  AS DEST_CITY 
        FROM SHIP_TENDER_COLLAB_BOV STV INNER JOIN 
        LOCATION LOC ON STV.SHIPMENT_SERVPROV_GID = LOC.LOCATION_GID INNER JOIN 
        SHIPMENT SHP ON STV.SHIPMENT_GID = SHP.SHIPMENT_GID INNER JOIN 
        LOCATION LOC2 ON SHP.DEST_LOCATION_GID = LOC2.LOCATION_GID INNER JOIN 
        LOCATION LOC3 ON SHP.SOURCE_LOCATION_GID = LOC3.LOCATION_GID 
        WHERE utc.get_local_date(STV.TENDER_ORIGINAL_PICKUP_TIME, LOC2.LOCATION_GID) BETWEEN TO_DATE('2026-01-01', 'YYYY-MM-DD') AND TO_DATE('2026-04-02', 'YYYY-MM-DD') + 7 
        AND STV.DOMAIN_NAME  = 'NBL/MX'  
    )  
GROUP BY SHIPMENT_SERVPROV_XID,SERVPROV_NAME, SOURCE, DEST_CITY, WEEK, MONTH 
ORDER BY WEEK, SERVPROV_NAME, SOURCE, DEST_CITY  ASC 
;
/*
La fecha de oferta o algun dato de fecha que nos pueda dar certeza por semana o mes? 
Asi como tambien colocar desde que source fue el origen del tender, es decir, mty, gdl o mxc?
*/