SELECT LL.LPN, LL.ITEM, LH.LPN_NEW, LH.LPN_OLD
FROM WMS_LOADED_LPNS LL LEFT JOIN 
WMS_HYDRATION_LPNS LH ON LL.LPN = LH.LPN_NEW
;


SELECT * 
FROM WMS_HYDRATION_LPNS
WHERE ITEM = 'BUR22Z24PZSKHCT'--'BUR22Z24PZALHCT'
ORDER BY LPN_OLD
;

SELECT * 
FROM WMS_HYDRATION_ALL_LPNS
--WHERE ITEM = 'BUR22Z24PZSKHCT'--'BUR22Z24PZALHCT'
ORDER BY LPN_OLD
;

SELECT HYD_LPNS.LPN_NEW, HYD_LPNS.LPN_OLD, WMS_LPN.TC_LPN_ID, WMS_LPN.TC_SHIPMENT_ID, WMS_LPN.LPN_STATUS, WMS_LPN.inbound_outbound_indicator
FROM WMS_HYDRATION_ALL_LPNS HYD_LPNS LEFT JOIN
LAN_WMS.LPN@MA_DB_LINK WMS_LPN ON WMS_LPN.TC_LPN_ID = HYD_LPNS.LPN_OLD
WHERE WMS_LPN.inbound_outbound_indicator = 'O'
--WHERE WMS_LPN.TC_LPN_ID IS NULL
--GROUP BY HYD_LPNS.LPN_NEW, HYD_LPNS.LPN_OLD, WMS_LPN.TC_LPN_ID
;


SELECT HYD_LPNS.LPN_NEW, HYD_LPNS.LPN_OLD, HYD_LPNS.LOT, OUTPT_LPN.TC_LPN_ID, OUTPT_LPN.TC_SHIPMENT_ID
FROM WMS_HYDRATION_ALL_LPNS HYD_LPNS LEFT JOIN
LAN_ARC.OUTPT_LPN@MA_DB_LINK OUTPT_LPN ON HYD_LPNS.LPN_OLD = OUTPT_LPN.TC_LPN_ID
ORDER BY HYD_LPNS.LOT
;

/*
Embarques encontrados
59223123
59950201
*/

SELECT * 
FROM WMS_HYDRATION_FILTERED_LK
;


59223150

SELECT * 
FROM LAN_ARC.ORDERS@MA_DB_LINK
WHERE SHIPMENT_ID = '59223150'
;

SELECT HYD_LK.LPN, HYD_LK.SKU, HYD_LK.LOT, HYD_LK.PEDIMENTO, HYD_LK.DELIVERY_ID_LK, ORD.TC_ORDER_ID, SHP.TC_SHIPMENT_ID
--HYD_LPNS.LPN_OLD ,OUTPT_LPN.TC_LPN_ID, ORD.ORDER_ID, ORD.TC_ORDER_ID, ORD.SHIPMENT_ID, SHP.TC_SHIPMENT_ID 
FROM WMS_HYDRATION_FILTERED_LK HYD_LK LEFT JOIN
WMS_HYDRATION_ALL_LPNS HYD_LPNS ON HYD_LK.LPN = HYD_LPNS.LPN_NEW LEFT JOIN
LAN_ARC.OUTPT_LPN@MA_DB_LINK OUTPT_LPN ON HYD_LPNS.LPN_OLD = OUTPT_LPN.TC_LPN_ID LEFT JOIN
LAN_ARC.SHIPMENT@MA_DB_LINK SHP ON OUTPT_LPN.TC_SHIPMENT_ID = SHP.TC_SHIPMENT_ID LEFT JOIN
LAN_ARC.ORDERS@MA_DB_LINK ORD ON ORD.SHIPMENT_ID = SHP.SHIPMENT_ID 
--WHERE OUTPT_LPN.inbound_outbound_indicator = 'O'
--WHERE OUTPT_LPN.TC_SHIPMENT_ID = '59223150'
WHERE SHP.TC_SHIPMENT_ID IS NOT NULL
UNION ALL
SELECT T.LPN, T.SKU, T.LOT, T.PEDIMENTO, T.DELIVERY_ID_LK, ORD.TC_ORDER_ID, SHP.TC_SHIPMENT_ID
FROM (
    SELECT HYD_LK.LPN, HYD_LK.SKU, HYD_LK.LOT, HYD_LK.PEDIMENTO, HYD_LK.DELIVERY_ID_LK, HYD_LPNS.LPN_NEW, HYD_LPNS.LPN_OLD
    FROM WMS_HYDRATION_FILTERED_LK HYD_LK LEFT JOIN
    WMS_HYDRATION_ALL_LPNS HYD_LPNS ON HYD_LK.LPN = HYD_LPNS.LPN_NEW LEFT JOIN
    LAN_ARC.OUTPT_LPN@MA_DB_LINK OUTPT_LPN ON HYD_LPNS.LPN_OLD = OUTPT_LPN.TC_LPN_ID LEFT JOIN
    LAN_ARC.SHIPMENT@MA_DB_LINK SHP ON OUTPT_LPN.TC_SHIPMENT_ID = SHP.TC_SHIPMENT_ID LEFT JOIN
    LAN_ARC.ORDERS@MA_DB_LINK ORD ON ORD.SHIPMENT_ID = SHP.SHIPMENT_ID 
    --WHERE OUTPT_LPN.inbound_outbound_indicator = 'O'
    --WHERE OUTPT_LPN.TC_SHIPMENT_ID = '59223150'
    WHERE SHP.TC_SHIPMENT_ID IS NULL
) T LEFT JOIN
LAN_WMS.OUTPT_LPN@MA_DB_LINK OUTPT_LPN ON T.LPN_OLD = OUTPT_LPN.TC_LPN_ID LEFT JOIN
LAN_WMS.SHIPMENT@MA_DB_LINK SHP ON OUTPT_LPN.TC_SHIPMENT_ID = SHP.TC_SHIPMENT_ID LEFT JOIN
LAN_WMS.ORDERS@MA_DB_LINK ORD ON ORD.SHIPMENT_ID = SHP.SHIPMENT_ID 
;


SELECT OUTPT_LPN.*
FROM WMS_HYDRATION_FILTERED_LK HYD_LPNS LEFT JOIN
LAN_ARC.OUTPT_LPN@MA_DB_LINK OUTPT_LPN ON HYD_LPNS.LPN = OUTPT_LPN.TC_LPN_ID
ORDER BY HYD_LPNS.LPN
;