
ALTER SESSION SET CURRENT_SCHEMA = MXC_WMS;

ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

SELECT * 
FROM TRAN_LOG
WHERE TRAN_LOG_ID = '10388509';
 

SELECT *
FROM TRAN_LOG_MESSAGE
WHERE MSG_LINE_TEXT LIKE '%5001003286%';
--WHERE TRAN_LOG_ID = '10388509';



SELECT TL.TRAN_LOG_ID,
        TL.REFERENCE_ID,
        --TRC.CODE_DESC AS RESULT_DESC,
        TL.RESULT_CODE,
        TL.CREATED_DTTM,
        TL.MSG_TYPE,
        TL.HAS_ERRORS
--        ,TLM.MSG_LINE_TEXT
FROM TRAN_LOG TL INNER JOIN 
TRAN_LOG_MESSAGE TLM ON TL.TRAN_LOG_ID = TLM.TRAN_LOG_ID /*INNER JOIN
SYSTEM_CODE TRC ON TRC.SYS_CODE_ID = TL.RESULT_CODE*/
WHERE TL.MSG_TYPE = 'ShipConfirm'
AND TLM.MSG_LINE_TEXT LIKE '%54220482%'
GROUP BY TL.TRAN_LOG_ID,
        TL.REFERENCE_ID,
        TL.RESULT_CODE,
        --TRC.CODE_DESC,
        TL.CREATED_DTTM,
        TL.MSG_TYPE,
        TL.HAS_ERRORS;


SELECT TL.TRAN_LOG_ID,
        TL.REFERENCE_ID,
        --TRC.CODE_DESC AS RESULT_DESC,
        TL.RESULT_CODE,
        TL.CREATED_DTTM,
        TL.MSG_TYPE,
        TL.HAS_ERRORS
--        ,TLM.MSG_LINE_TEXT
FROM TRAN_LOG TL INNER JOIN 
TRAN_LOG_MESSAGE TLM ON TL.TRAN_LOG_ID = TLM.TRAN_LOG_ID /*INNER JOIN
SYSTEM_CODE TRC ON TRC.SYS_CODE_ID = TL.RESULT_CODE*/
WHERE TL.MSG_TYPE = 'shipmentFull' --'%App%' --'shipmentFull'
AND TLM.MSG_LINE_TEXT LIKE '%MX5001006011%'
GROUP BY TL.TRAN_LOG_ID,
        TL.REFERENCE_ID,
        TL.RESULT_CODE,
        --TRC.CODE_DESC,
        TL.CREATED_DTTM,
        TL.MSG_TYPE,
        TL.HAS_ERRORS
ORDER BY TL.CREATED_DTTM ASC;


SELECT * FROM SYSTEM_CODE;


SELECT * FROM all_objects
where object_name like '%CODE%'
and object_type in ('TABLE', 'VIEW')
AND OWNER = 'MTY_WMS';


POD_REASON_CODE
CAT_CODE

OBJECT_REASON_CODES

SYSTEM_CODE
TRANS_RESP_CODE



SELECT * 
FROM cl_message INNER JOIN
cl_endpoint_queue ON cl_message.msg_id = cl_endpoint_queue.msg_id
WHERE 1 = 1 
AND cl_message.source_id = 'SDM TO WM'
--AND cl_message.MSG_ID = '14883244'
AND cl_message.data LIKE '%5001013953%'
AND cl_endpoint_queue.status <> 5;

SELECT * 
FROM cl_endpoint_queue
WHERE MSG_ID = '14885252';

SELECT * 
FROM msg_log 
where 1 = 1
--AND pgM_Id like '%SU_EXT%'
AND MSG LIKE '%41370007%'--IN ('00400275411100370601','00400275411100370618')
ORDER BY LOG_DATE_TIME DESC
;

14900381
14885252

00400275411100370540

Cannot Find Open Line to Load Item: BUR22Z24PZGRHCT on Order 41370007