select order_release_gid,packaged_item_gid,substr(packaged_item_gid,5,3) as "Shipping_Org"
from order_release_line 
where order_release_gid='NBL.41102321'
group by order_release_gid,packaged_item_gid,substr(packaged_item_gid,5,3);


SELECT 
    O.ORDER_RELEASE_GID, 
    L.ORDER_RELEASE_LINE_GID,
    L.PACKAGED_ITEM_GID, 
    O.SOURCE_LOCATION_GID,
        SUBSTR(O.SOURCE_LOCATION_GID, 9, 3) AS "SOURCE_ORG",
    SUBSTR(L.PACKAGED_ITEM_GID, 5, 3) AS "PACKAGED_ITEM_ORG"
FROM ORDER_RELEASE O INNER JOIN 
ORDER_RELEASE_LINE L ON L.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
WHERE O.ORDER_RELEASE_GID IN ( 
        SELECT 
            ORE.ORDER_RELEASE_GID
        FROM ORDER_RELEASE ORE INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
        WHERE 1 = 1
        AND SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) <> SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3)
        AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
        AND ORE.DOMAIN_NAME = 'NBL'
        AND ORE.ORDER_RELEASE_GID NOT LIKE '%TONU%'
    )
ORDER BY O.ORDER_RELEASE_GID
;


SELECT 
    O.ORDER_RELEASE_GID, 
    L.ORDER_RELEASE_LINE_GID,
    L.PACKAGED_ITEM_GID, 
    O.SOURCE_LOCATION_GID,
        SUBSTR(O.SOURCE_LOCATION_GID, 9, 3) AS "SOURCE_ORG",
    SUBSTR(L.PACKAGED_ITEM_GID, 5, 3) AS "PACKAGED_ITEM_ORG"
FROM ORDER_RELEASE O INNER JOIN 
ORDER_RELEASE_LINE L ON L.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
WHERE O.ORDER_RELEASE_GID IN ( 
        SELECT 
            ORE.ORDER_RELEASE_GID
        FROM ORDER_RELEASE ORE INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
        WHERE 1 = 1
        AND SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3) <> SUBSTR(ORE.SOURCE_LOCATION_GID, 9, 3)
        AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
        AND ORE.DOMAIN_NAME = 'NBL'
        AND ORE.ORDER_RELEASE_GID NOT LIKE '%TONU%'
    )
ORDER BY O.ORDER_RELEASE_GID;
                --AND ORE.ORDER_RELEASE_GID IN ('NBL.41102321','NBL.41174617')

-------------------------------Final version to find multiple packaged item orgs in an order release-----------------------------
SELECT 
    O.ORDER_RELEASE_GID, 
    L.ORDER_RELEASE_LINE_GID,
    L.PACKAGED_ITEM_GID 
FROM ORDER_RELEASE O INNER JOIN 
ORDER_RELEASE_LINE L ON L.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
WHERE O.ORDER_RELEASE_GID IN ( 
        SELECT  T.ORDER_RELEASE_GID
        FROM (
                SELECT 
                    ORE.ORDER_RELEASE_GID
                FROM ORDER_RELEASE ORE INNER JOIN
                    ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
                WHERE 1 = 1
                AND ORL.INSERT_DATE >= TO_DATE('2026-01-01','YYYY-MM-DD') 
                AND ORE.DOMAIN_NAME = 'NBL'
                AND ORE.ORDER_RELEASE_GID NOT LIKE '%TONU%'
                GROUP BY ORE.ORDER_RELEASE_GID, SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3)
                ORDER BY ORE.ORDER_RELEASE_GID
        ) T
        GROUP BY T.ORDER_RELEASE_GID
        HAVING COUNT(T.ORDER_RELEASE_GID) > 1
)
ORDER BY O.ORDER_RELEASE_GID DESC
;