SELECT S.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, RS.RATE_SERVICE_XID  
FROM SERVPROV S INNER JOIN
LOCATION L ON S.SERVPROV_GID = L.LOCATION_GID INNER JOIN
SCAC SC ON S.SCAC_GID = SC.SCAC_GID INNER JOIN
RATE_OFFERING RO ON RO.SERVPROV_GID = S.SERVPROV_GID INNER JOIN
RATE_GEO RG ON RG.RATE_OFFERING_GID = RO.RATE_OFFERING_GID INNER JOIN
RATE_SERVICE RS ON RS.RATE_SERVICE_GID = RG.RATE_SERVICE_GID
WHERE L.COUNTRY_CODE3_GID = 'MEX'
AND RO.DOMAIN_NAME = 'NBL/MX'
AND RG.IS_ACTIVE  = 'Y'
GROUP BY S.SERVPROV_XID, L.LOCATION_NAME, SC.SCAC_XID, RS.RATE_SERVICE_XID  
ORDER BY SC.SCAC_XID, RS.RATE_SERVICE_XID 