
SELECT * FROM
(
SELECT ORDL.ORDER_RELEASE_GID, ORDL.PACKAGED_ITEM_GID
FROM ORDER_RELEASE_LINE ORDL 
WHERE ORDL.ORDER_RELEASE_GID IN (

            SELECT ORE.ORDER_RELEASE_GID, COUNT(ORL.PACKAGED_ITEM_GID) AS COUNT_ITEM, ORL.PACKAGED_ITEM_GID, SUBSTR(ORL.PACKAGED_ITEM_GID, 6, 3) 
            FROM SHIPMENT SH INNER JOIN
            ORDER_MOVEMENT OM ON SH.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
            ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN
            ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
            WHERE 1 = 1
            AND SH.DOMAIN_NAME = 'NBL'
            AND SH.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD')
            --AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 6, 3), '^[[:digit:]]+$')
            --AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 6, 3), '^[A-Za-z]+$')
            --AND SH.SHIPMENT_GID = 'NBL/MX.MX5001000013'
            GROUP BY ORE.ORDER_RELEASE_GID, ORL.PACKAGED_ITEM_GID  
            HAVING COUNT(ORL.PACKAGED_ITEM_GID) > 1

        )  
) T
WHERE REGEXP_LIKE(SUBSTR(ORDL.PACKAGED_ITEM_GID, 6, 3), '^[[:digit:]]+$')
;



SELECT F.ORDER_RELEASE_GID, ORRRL.PACKAGED_ITEM_GID
FROM (


    SELECT T.ORDER_RELEASE_GID
    FROM (
        SELECT ORE.ORDER_RELEASE_GID, orl.PACKAGED_ITEM_GID, SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3)
        FROM ORDER_RELEASE ORE INNER JOIN
        ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
        WHERE 1 = 1
        AND ORE.DOMAIN_NAME = 'NBL'
        AND ORE.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD')
        --AND ORE.ORDER_RELEASE_GID = 'NBL.39848729'
        AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[a-zA-Z0-9]+$')
        GROUP BY ORE.ORDER_RELEASE_GID 
        HAVING COUNT(ORL.PACKAGED_ITEM_GID) >= 2
    ) T INNER JOIN
    ORDER_RELEASE_LINE ORRL ON T.ORDER_RELEASE_GID = ORRL.ORDER_RELEASE_GID
    WHERE 1 = 1
    AND REGEXP_LIKE(SUBSTR(ORRL.PACKAGED_ITEM_GID, 5, 3), '^[[:digit:]]+$')
    --AND REGEXP_LIKE(SUBSTR(ORRL.PACKAGED_ITEM_GID, 4, 3), '^[a-zA-Z0-9]+$')



) F INNER JOIN
ORDER_RELEASE_LINE ORRRL ON F.ORDER_RELEASE_GID = ORRRL.ORDER_RELEASE_GID
WHERE 1 = 1
AND REGEXP_LIKE(SUBSTR(ORRRL.PACKAGED_ITEM_GID, 5, 3), '^[[:digit:]]+$')
ORDER BY F.ORDER_RELEASE_GID
;



    --AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[A-Za-z]+$')
    --AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[[:digit:]]+$')

SELECT ORE.ORDER_RELEASE_GID, orl.PACKAGED_ITEM_GID, SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3)
FROM ORDER_RELEASE ORE INNER JOIN
ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
WHERE 1 = 1
AND ORE.DOMAIN_NAME = 'NBL'
AND ORE.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD')
--AND ORE.ORDER_RELEASE_GID = 'NBL.39848729'
AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[[:digit:]]+$')

SELECT ORE.ORDER_RELEASE_GID, ORL.PACKAGED_ITEM_GID, SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3)
FROM ORDER_RELEASE ORE INNER JOIN
ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
WHERE 1 = 1
AND ORE.DOMAIN_NAME = 'NBL'
AND ORE.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD')
--AND ORE.ORDER_RELEASE_GID = 'NBL.39848729'
AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[a-zA-Z0-9]+$')
AND ORE.ORDER_RELEASE_GID IN (

SELECT ORE.ORDER_RELEASE_GID
FROM ORDER_RELEASE ORE INNER JOIN
ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID
WHERE 1 = 1
AND ORE.DOMAIN_NAME = 'NBL'
AND ORE.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD')
--AND ORE.ORDER_RELEASE_GID = 'NBL.39848729'
AND REGEXP_LIKE(SUBSTR(ORL.PACKAGED_ITEM_GID, 5, 3), '^[[:digit:]]+$')

)
--------------------------------------------Final Item 1-----------------------------------------

SELECT 
SH.SHIPMENT_GID, 
SR.REMARK_SEQUENCE,   
SR.REMARK_QUAL_GID,  
SR.REMARK_TEXT,  
S.NEW_REMARK_TEXT,
SR.DOMAIN_NAME
FROM SHIPMENT SH INNER JOIN 
ORDER_MOVEMENT OM ON SH.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN 
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
( 
SELECT ODL.ORDER_RELEASE_LINE_GID, ODL.ORDER_RELEASE_GID, ODL.ITEM_PACKAGE_COUNT, ODL.PACKAGED_ITEM_GID, 
OK.REMARK_SEQUENCE, OK.REMARK_QUAL_GID, OK.REMARK_TEXT, PI.DESCRIPTION || '--' || ODL.ITEM_PACKAGE_COUNT AS NEW_REMARK_TEXT, OK.DOMAIN_NAME, PI.DESCRIPTION
FROM ORDER_RELEASE ORD INNER JOIN 
ORDER_RELEASE_LINE ODL ON ORD.ORDER_RELEASE_GID = ODL.ORDER_RELEASE_GID INNER JOIN 
    ( 
    SELECT O.ORDER_RELEASE_GID, OL.ORDER_RELEASE_LINE_GID 
    FROM ORDER_RELEASE O INNER JOIN 
    ORDER_RELEASE_LINE OL ON OL.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID 
    WHERE OL.ORDER_RELEASE_LINE_GID IN ( 
                SELECT ORL.ORDER_RELEASE_LINE_GID  
                FROM ORDER_RELEASE ORE INNER JOIN 
                ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
                WHERE 1 = 1 
                AND ORL.DOMAIN_NAME = 'NBL/MX' 
                AND ORL.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD') 
                AND ORL.ORDER_RELEASE_LINE_GID NOT IN ( 

                        SELECT SUL.ORDER_RELEASE_LINE_GID 
                        FROM SHIP_UNIT_LINE SUL INNER JOIN 
                        ORDER_RELEASE_LINE ORL ON SUL.ORDER_RELEASE_LINE_GID = ORL.ORDER_RELEASE_LINE_GID 
                        WHERE 1 = 1 
                        AND ORL.DOMAIN_NAME = 'NBL/MX' 
                        AND ORL.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD') 
                )  
        )  
    ) Z ON ORD.ORDER_RELEASE_GID = Z.ORDER_RELEASE_GID AND Z.ORDER_RELEASE_LINE_GID != ODL.ORDER_RELEASE_LINE_GID INNER JOIN 
    ORDER_RELEASE_REMARK OK ON OK.ORDER_RELEASE_GID = ORD.ORDER_RELEASE_GID AND REMARK_QUAL_GID LIKE 'NBL.ITEM_DESC_AND_COUNT%' INNER JOIN  
    PACKAGED_ITEM PI ON PI.PACKAGED_ITEM_GID = ODL.PACKAGED_ITEM_GID 
) S ON S.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
SHIPMENT_REMARK SR ON SH.SHIPMENT_GID = SR.SHIPMENT_GID AND SR.REMARK_QUAL_GID LIKE 'NBL.ITEM_DESC_AND_COUNT%' 
WHERE SH.NUM_STOPS <= 2 
AND SH.SHIPMENT_GID = 'NBL.NB54122954'


--20872663

--All Shipment = 2835
--Single Stop (3 or less) = 2022
--Multi Stop (more than 3) = 813

--------------------------------------------Final Item >2-----------------------------------------


SELECT ROW_NUMBER() OVER(PARTITION BY SK.SHIPMENT_GID ORDER BY SK.REMARK_SEQUENCE ASC) AS SK_ROW_ID,
    SK.SHIPMENT_GID,
    SK.REMARK_SEQUENCE,
    SK.REMARK_QUAL_GID,
    SK.REMARK_TEXT,
    SK.DOMAIN_NAME
FROM SHIPMENT_REMARK SK 
WHERE SK.SHIPMENT_GID = 'NBL.NB53976928'
AND REMARK_QUAL_GID LIKE 'NBL.ITEM_DESC_AND_COUNT%'


INNER JOIN
(


)
SELECT Z.SHIPMENT_GID, 
        ORD.ORDER_RELEASE_GID, 
        ROW_NUMBER() OVER(PARTITION BY Z.SHIPMENT_GID ORDER BY OK.REMARK_SEQUENCE ASC) AS ORE_ROW_ID,
        OK.REMARK_SEQUENCE, 
        OK.REMARK_QUAL_GID, 
        OK.REMARK_TEXT, 
        OK.DOMAIN_NAME,
        SUBSTR(REMARK_TEXT, 1, INSTR(REMARK_TEXT, '--') - 1) AS ITEM_DESC,
        SUBSTR(REMARK_TEXT, INSTR(REMARK_TEXT, '--') + 2) AS ITEM_COUNT
FROM ORDER_RELEASE ORD INNER JOIN
ORDER_MOVEMENT OM ON OM.ORDER_RELEASE_GID = ORD.ORDER_RELEASE_GID INNER JOIN 
    ( 

        SELECT SH.SHIPMENT_GID
        FROM ORDER_RELEASE O INNER JOIN 
        ORDER_MOVEMENT OM ON OM.ORDER_RELEASE_GID = O.ORDER_RELEASE_GID INNER JOIN 
        SHIPMENT SH ON SH.SHIPMENT_GID = OM.SHIPMENT_GID 
        WHERE O.ORDER_RELEASE_GID IN ( 
                    SELECT ORE.ORDER_RELEASE_GID  
                    FROM ORDER_RELEASE ORE INNER JOIN 
                    ORDER_RELEASE_LINE ORL ON ORE.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
                    WHERE 1 = 1 
                    AND ORL.DOMAIN_NAME = 'NBL' 
                    AND ORL.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD') 
                    AND ORL.ORDER_RELEASE_LINE_GID NOT IN ( 
                            SELECT SUL.ORDER_RELEASE_LINE_GID 
                            FROM SHIP_UNIT_LINE SUL INNER JOIN 
                            ORDER_RELEASE_LINE ORL ON SUL.ORDER_RELEASE_LINE_GID = ORL.ORDER_RELEASE_LINE_GID 
                            WHERE 1 = 1 
                            AND ORL.DOMAIN_NAME = 'NBL' 
                            AND ORL.UPDATE_DATE >= to_date('2026-01-01','YYYY-MM-DD') 
                    )  
            )
        AND SH.NUM_STOPS > 2 
        AND SH.SHIPMENT_GID = 'NBL.NB53976928'
        GROUP BY SH.SHIPMENT_GID

) Z ON Z.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
ORDER_RELEASE_REMARK OK ON OK.ORDER_RELEASE_GID = ORD.ORDER_RELEASE_GID AND REMARK_QUAL_GID LIKE 'NBL.ITEM_DESC_AND_COUNT%'
ORDER BY ORE_ROW_ID


--AND O.ORDER_RELEASE_GID IN ('NBL.39752982','NBL.39752981','NBL.39753053','NBL.39753058')

SELECT * 
FROM S_SHIP_UNIT_LINE SSUL INNER JOIN 
S_SHIP_UNIT SSU ON SSUL.S_SHIP_UNIT_GID = SSU.S_SHIP_UNIT_GID INNER JOIN
SHIP_UNIT SU ON SSU.SHIP_UNIT_GID = SU.SHIP_UNIT_GID INNER JOIN
SHIP_UNIT_LINE SUL ON SU.SHIP_UNIT_GID = SUL.SHIP_UNIT_GID INNER JOIN
SHIPMENT_STOP_D SSD ON SSUL.S_SHIP_UNIT_GID = SSD.S_SHIP_UNIT_GID
WHERE SSD.SHIPMENT_GID = 'NBL.NB54122954'  

SELECT * FROM SHIPMENT_STOP_D   
WHERE SHIPMENT_GID = 'NBL.NB54122954'  

SELECT SUBSTR(REMARK_TEXT, 1, INSTR(REMARK_TEXT, '--') - 1) AS ITEM_DESC,
SUBSTR(REMARK_TEXT, INSTR(REMARK_TEXT, '--') + 2) AS ITEM_COUNT
FROM SHIPMENT_REMARK
WHERE SHIPMENT_GID = 'NBL.NB54122954'
AND REMARK_QUAL_GID LIKE 'NBL.ITEM_DESC_AND_COUNT%'


/*

Get all the Remarks from Order Release where from Shipment

*/

39752982
39752981
39753053
39753058

39890117
39889666

/*
1. Delete remarks from shipment
2. Insert remarks into shipment from order release

Query
1. Get Order Release for Shipment
2. Get Order Release Remark's
*/