SELECT A.AGENT_GID, D.ACTION_SEQUENCE, D.AGENT_ACTION_GID, D.ACTION_PARAMETERS
FROM AGENT_ACTION_DETAILS D INNER JOIN
AGENT A ON A.AGENT_GID = D.AGENT_GID
WHERE D.ACTION_PARAMETERS LIKE '%PU_APPOINTMENT%'
--AND (D.ACTION_PARAMETERS LIKE '%DELETE%' OR D.ACTION_PARAMETERS LIKE '%INSERT%' OR D.ACTION_PARAMETERS LIKE '%UPDATE%')
AND A.IS_ACTIVE = 'Y'
--AND D.ACTION_PARAMETERS LIKE '%SHIPMENT_REFNUM%'
--GROUP BY A.AGENT_GID


SELECT *
FROM AGENT_ACTION_DETAILS D INNER JOIN
AGENT A ON A.AGENT_GID = D.AGENT_GID
WHERE ACTION_PARAMETERS LIKE '%REF_VALUE%'
AND A.IS_ACTIVE = 'Y'


SELECT *
FROM AGENT_ACTION_DETAILS D INNER JOIN
AGENT A ON A.AGENT_GID = D.AGENT_GID
WHERE ACTION_PARAMETERS LIKE '%RC_PLANNED_SHIPMENT_STATUS%'
AND AGENT_ACTION_GID LIKE 'SEND INTEGRATION%'
AND A.IS_ACTIVE = 'Y'