SELECT SHIPMENT_XID
, LISTAGG(Customer_PO, '|') WITHIN GROUP (ORDER BY Customer_PO) "Customer PO"
FROM SCREEN_BUY_SHPMENT
WHERE SHIPMENT_XID IN ('MX23056797', 'MX23058628')
GROUP BY SHIPMENT_XID
;