SELECT A.AGENT_GID, D.ACTION_SEQUENCE, D.AGENT_ACTION_GID, D.ACTION_PARAMETERS
FROM AGENT_ACTION_DETAILS D INNER JOIN
AGENT A ON A.AGENT_GID = D.AGENT_GID
WHERE D.ACTION_PARAMETERS LIKE '%PU_APPOINTMENT%'
--AND (D.ACTION_PARAMETERS LIKE '%DELETE%' OR D.ACTION_PARAMETERS LIKE '%INSERT%' OR D.ACTION_PARAMETERS LIKE '%UPDATE%')
AND A.IS_ACTIVE = 'Y'



Select 1 
from shipment s , location_profile_detail lpd 
where shipment_gid =$gid 
and ( s.source_location_gid=lpd.location_gid or s.dest_location_gid =lpd.location_gid) 
and lpd.location_profile_gid ='NBL.LOCATION_ELIGIBLE_FOR_FK_APPOINTMENTS'



SELECT SHIPMENT_GID 
FROM SHIPMENT 
WHERE SHIPMENT_GID = $GID 
AND PAYMENT_METHOD_CODE_GID IN ('NBL.PREPAID','NBL.DELIVERY','NBL.PAID')