--Get todos los items con embarque activo del 2025
SELECT IT.ITEM_XID, 
    IT.ITEM_NAME, 
    PI.PACKAGED_ITEM_XID, 
    PI.DESCRIPTION   
FROM ORDER_RELEASE ORR INNER JOIN  
ORDER_RELEASE_LINE ORL ON ORR.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID INNER JOIN 
PACKAGED_ITEM PI ON ORL.PACKAGED_ITEM_GID = PI.PACKAGED_ITEM_GID INNER JOIN 
ITEM IT ON PI.ITEM_GID = IT.ITEM_GID INNER JOIN 
ORDER_MOVEMENT OM ON ORR.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN  
SHIPMENT SH ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN  
SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID   
                    AND SS.STATUS_TYPE_GID = 'NBL/MX.PAYMENT'  
                    AND SS.STATUS_VALUE_GID = 'NBL/MX.PAYMENT_VOUCHERED'  
WHERE ORR.INSERT_DATE BETWEEN TO_DATE('2025-01-01','YYYY-MM-DD')  
AND TO_DATE('2025-11-07','YYYY-MM-DD')   
GROUP BY IT.ITEM_XID, 
        IT.ITEM_NAME, 
        PI.PACKAGED_ITEM_XID, 
        PI.DESCRIPTION  
ORDER BY IT.ITEM_XID;


--Get todos los CUS con embarque activo del 2025
SELECT ORL.DEST_LOCATION_GID, LOC.LOCATION_NAME 
FROM ORDER_RELEASE ORL INNER JOIN 
ORDER_MOVEMENT OM ON ORL.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN 
SHIPMENT SH ON OM.SHIPMENT_GID = SH.SHIPMENT_GID INNER JOIN 
SHIPMENT_STATUS SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID  
                    AND SS.STATUS_TYPE_GID = 'NBL/MX.PAYMENT' AND SS.STATUS_VALUE_GID = 'NBL/MX.PAYMENT_VOUCHERED' INNER JOIN 
LOCATION LOC ON ORL.DEST_LOCATION_GID = LOC.LOCATION_GID 
WHERE ORL.INSERT_DATE BETWEEN TO_DATE('2025-01-01','YYYY-MM-DD') AND TO_DATE('2025-11-07','YYYY-MM-DD')  
AND LOC.LOCATION_XID NOT LIKE 'ORG%' 
GROUP BY ORL.DEST_LOCATION_GID, LOC.LOCATION_NAME;