SELECT INV1.INVOICE_GID 
FROM INVOICE INV1,
INVOICE INV2, 
INVOICE_SHIPMENT INS1, 
INVOICE_SHIPMENT INS2 
WHERE INV1.INVOICE_NUMBER = INV2.INVOICE_NUMBER 
AND INV1.SERVPROV_GID = INV2.SERVPROV_GID 
AND ROUND(INV1.NET_AMOUNT_DUE,3) = ROUND(INV2.NET_AMOUNT_DUE,3) 
AND INV1.INVOICE_GID <> INV2.INVOICE_GID 
AND INV2.INVOICE_GID = 'NBL/MX.20241205-0009'
AND INS1.INVOICE_GID = INV1.INVOICE_GID 
AND INS2.INVOICE_GID = INV2.INVOICE_GID 
AND INS1.SHIPMENT_GID = INS2.SHIPMENT_GID




SELECT INV1.INVOICE_GID 
FROM INVOICE INV1,INVOICE INV2, 
INVOICE_SHIPMENT INS1, 
INVOICE_SHIPMENT INS2 
WHERE INV1.INVOICE_NUMBER = INV2.INVOICE_NUMBER 
AND INV1.SERVPROV_GID = INV2.SERVPROV_GID 
AND ROUND(INV1.NET_AMOUNT_DUE,3) = ROUND(INV2.NET_AMOUNT_DUE,3) 
AND INV1.INVOICE_GID <> INV2.INVOICE_GID 
AND INV2.INVOICE_GID = 'NBL/MX.20241205-0009' 
AND INS1.INVOICE_GID = INV1.INVOICE_GID 
AND INS2.INVOICE_GID = INV2.INVOICE_GID 
AND INS1.SHIPMENT_GID = INS2.SHIPMENT_GID



NBL/MX.20241205-0009



SELECT 1 
FROM INVOICE 
WHERE NOT EXISTS (
    SELECT SHIPMENT_GID 
    FROM SHIPMENT 
    WHERE SHIPMENT_GID = (
        select INVOICE_REFNUM_VALUE 
    from invoice_refnum 
    where invoice_gid = 'NBL/MX.20241205-0009' 
    AND INVOICE_REFNUM_QUAL_GID = 'NBL.LOAD_NO' 
    AND ROWNUM=1)
    ) 
    AND invoice_gid = 'NBL/MX.20241205-0009'


SELECT 1 
FROM INVOICE 
WHERE NOT EXISTS (
    SELECT SHIPMENT_REFNUM_VALUE 
    FROM SHIPMENT_REFNUM 
    WHERE SHIPMENT_GID = (
        select INVOICE_REFNUM_VALUE 
        from invoice_refnum 
        where invoice_gid = 'NBL/MX.20241205-0009' 
        AND INVOICE_REFNUM_QUAL_GID = 'NBL.LOAD_NO' AND ROWNUM=1
        ) 
        AND SHIPMENT_REFNUM_QUAL_GID = 'NBL.LOAD_NO'
        ) 
        AND INVOICE_GID = 'NBL/MX.20241205-0009'


SELECT INV1.INVOICE_GID 
FROM INVOICE INV1,INVOICE INV2, INVOICE_SHIPMENT INS1, INVOICE_SHIPMENT INS2 
WHERE INV1.INVOICE_NUMBER = INV2.INVOICE_NUMBER 
AND INV1.SERVPROV_GID = INV2.SERVPROV_GID 
AND ROUND(INV1.NET_AMOUNT_DUE,3) <> ROUND(INV2.NET_AMOUNT_DUE,3) 
AND INV1.INVOICE_GID <> INV2.INVOICE_GID 
AND INV2.INVOICE_GID = 'NBL/MX.20241205-0009' 
AND INS1.INVOICE_GID = INV1.INVOICE_GID 
AND INS2.INVOICE_GID = INV2.INVOICE_GID 
AND INS1.SHIPMENT_GID = INS2.SHIPMENT_GID

MATCH_NON_ORIGINAL_INVOICE

SELECT DISTINCT INVOICE_GID 
FROM INVOICE_STATUS 
WHERE INVOICE_GID = 'NBL/MX.20241205-0009' 
AND STATUS_TYPE_GID = 'NBL.MATCH' 
AND STATUS_VALUE_GID = 'NBL.MATCH_NON_ORIGINAL_INVOICE'

Agentes a modificar

INVOICE - MATCH SUCCEED_BKUP_12052024

INVOICE - POST AUTO MATCH
