---ASSIGN VAR
SELECT REPLACE(REPLACE(ORDER_RELEASE_REFNUM_VALUE, CHR(13), ''), CHR(10), '') AS REPLACED, ORDER_RELEASE_REFNUM_VALUE, 
REGEXP_REPLACE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]', '') AS CLEANSTRING
FROM order_release_refnum 
WHERE order_release_gid='NBL.39839672' AND ORDER_RELEASE_REFNUM_QUAL_GID='CUST_PO' and (ORDER_RELEASE_REFNUM_VALUE LIKE '%' || CHR(10) || '%' 
OR ORDER_RELEASE_REFNUM_VALUE LIKE '%' || CHR(13) || '%')



SELECT REGEXP_REPLACE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]', '') AS CLEANSTRING 
FROM order_release_refnum  
WHERE order_release_gid='NBL.39839672' 
AND ORDER_RELEASE_REFNUM_QUAL_GID='CUST_PO' 
AND REGEXP_LIKE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]') 


SELECT REGEXP_REPLACE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]', '') AS CLEANSTRING
FROM order_release_refnum 
WHERE 1 = 1
AND ORDER_RELEASE_REFNUM_QUAL_GID='CUST_PO' 
AND REGEXP_LIKE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]')



SELECT REGEXP_REPLACE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]', '') AS CLEANSTRING  
FROM ORDER_RELEASE_REFNUM   
WHERE ORDER_RELEASE_GID = 'NBL.39839672' 
AND ORDER_RELEASE_REFNUM_QUAL_GID = 'CUST_PO'   
AND REGEXP_LIKE(ORDER_RELEASE_REFNUM_VALUE, '[[:space:]]') 

--[NBL.39839672]