SELECT * --RATE_DISTANCE_GID
FROM DISTANCE_LOOKUP
--WHERE DOMAIN_NAME = 'NBL/MX';
--GROUP BY RATE_DISTANCE_GID;
WHERE RATE_DISTANCE_GID = 'NBL/MX.PCMILER_PRACTICAL_POSTAL_TO_POSTAL (MEX)'
ORDER BY INSERT_DATE DESC;

SELECT * --RATE_DISTANCE_GID
FROM DISTANCE_BY_ADDRESSES
;

SELECT RG.REGION_GID, RG.REGION_XID, RGD.LOCATION_GID, L.LOCATION_XID
FROM REGION RG INNER JOIN
REGION_DETAIL RGD ON RG.REGION_GID = RGD.REGION_GID INNER JOIN
LOCATION L ON RGD.LOCATION_GID = L.LOCATION_GID
WHERE RG.DOMAIN_NAME = 'NBL/MX'
AND RG.REGION_XID LIKE '%|%';


SELECT * 
FROM X_LANE
WHERE DOMAIN_NAME = 'NBL/MX'
AND X_LANE_XID LIKE '%|%';
AND INSERT_USER = 'NBL/MX.AROUGERIO';