-----Final con condiciones comentadas
SELECT * 
FROM ( 
    SELECT S.SHIPMENT_XID,   
    S.TOTAL_ITEM_PACKAGE_COUNT AS TOTAL_PACKAGE_COUNT, 
    SR.REMARK_TEXT AS SHIP_DATE, 
    --TO_DATE(SR.REMARK_TEXT, 'YYYY-MM-DD HH24:MI:SS') DATE_SHIP_DATE, 
    SUM(ORL.ITEM_PACKAGE_COUNT) AS TOTAL_LINE_SUM 
    FROM SHIPMENT S INNER JOIN 
    ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN 
    ORDER_RELEASE ORE ON ORE.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN 
    ORDER_RELEASE_LINE ORL ON ORL.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
    SHIPMENT_REMARK SR ON SR.SHIPMENT_GID = S.SHIPMENT_GID AND SR.REMARK_QUAL_GID = 'SHIP_DATE' 
    WHERE 1 = 1   
    AND S.START_TIME BETWEEN TO_DATE('2026-02-01', 'YYYY-MM-DD') AND TO_DATE('2026-02-28', 'YYYY-MM-DD') 
    /*AND TO_DATE(TO_CHAR(TO_DATE(SR.REMARK_TEXT, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD'), 'YYYY-MM-DD')  
    BETWEEN TO_DATE('2026-02-01', 'YYYY-MM-DD') AND TO_DATE('2026-02-28', 'YYYY-MM-DD')*/ 
    AND S.SHIPMENT_GID = 'NBL/MX.MX5001008360' 
    AND S.DOMAIN_NAME = 'NBL/MX' 
    GROUP BY S.SHIPMENT_XID,   
        S.TOTAL_ITEM_PACKAGE_COUNT, 
        SR.REMARK_TEXT 
    ORDER BY S.SHIPMENT_XID 
) 
--WHERE TOTAL_PACKAGE_COUNT != TOTAL_LINE_SUM
ORDER BY SHIP_DATE DESC


---Final
SELECT SHIPMENT_XID, SHIP_DATE, TOTAL_PACKAGE_COUNT, TOTAL_LINE_SUM 
FROM ( 
    SELECT S.SHIPMENT_XID,   
    S.TOTAL_ITEM_PACKAGE_COUNT AS TOTAL_PACKAGE_COUNT, 
    SR.REMARK_TEXT AS SHIP_DATE, 
    SUM(ORL.ITEM_PACKAGE_COUNT) AS TOTAL_LINE_SUM 
    FROM SHIPMENT S INNER JOIN 
    ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN  
    ORDER_RELEASE ORE ON ORE.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN 
    ORDER_RELEASE_LINE ORL ON ORL.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN 
    SHIPMENT_REMARK SR ON SR.SHIPMENT_GID = S.SHIPMENT_GID AND SR.REMARK_QUAL_GID = 'SHIP_DATE'  
    WHERE 1 = 1   
    AND S.START_TIME BETWEEN TO_DATE('2026-02-01', 'YYYY-MM-DD') AND TO_DATE('2026-02-28', 'YYYY-MM-DD') 
    AND S.DOMAIN_NAME = 'NBL/MX'  
    GROUP BY S.SHIPMENT_XID,   
        S.TOTAL_ITEM_PACKAGE_COUNT,  
        SR.REMARK_TEXT  
    ORDER BY S.SHIPMENT_XID  
)  
ORDER BY SHIP_DATE DESC 

;



SELECT S.SHIPMENT_XID,  
    S.TOTAL_ITEM_PACKAGE_COUNT AS TOTAL_PACKAGE_COUNT,
    SR.REMARK_TEXT AS SHIP_DATE,
    S.START_TIME, 
    --TO_DATE(SR.REMARK_TEXT, 'YYYY-MM-DD HH24:MI:SS') DATE_SHIP_DATE,
    SUM(ORL.ITEM_PACKAGE_COUNT) AS TOTAL_LINE_SUM
FROM SHIPMENT S INNER JOIN
ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
ORDER_RELEASE ORE ON ORE.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID INNER JOIN
ORDER_RELEASE_LINE ORL ON ORL.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN
SHIPMENT_REMARK SR ON SR.SHIPMENT_GID = S.SHIPMENT_GID AND SR.REMARK_QUAL_GID = 'SHIP_DATE'
WHERE 1 = 1  
AND S.SHIPMENT_GID = 'NBL/MX.MX5001016876'
AND S.DOMAIN_NAME = 'NBL/MX'
GROUP BY S.SHIPMENT_XID,  
    S.TOTAL_ITEM_PACKAGE_COUNT,
    SR.REMARK_TEXT, S.START_TIME
ORDER BY S.SHIPMENT_XID

/*
Embarcado
6,119
*/

/*
CUS - 9.1 millones
ALL - 11 millones
*/