SELECT ORR.ORDER_RELEASE_GID   
FROM ORDER_RELEASE ORR INNER JOIN        
ORDER_RELEASE_STATUS ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID   
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'   
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'   
AND ORR.DOMAIN_NAME = 'NBL/MX'   
AND ORR.DELIVERY_IS_APPT  = 'Y'   
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE   
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15   
AND ORR.DEST_LOCATION_GID IN (
                                SELECT LOCATION_GID
                                FROM REGION_DETAIL
                                WHERE REGION_GID IN ('NBL/MX.MXC CHALCO', 'NBL/MX.MXC CUAUTITLAN', 'NBL/MX.MXC CDMX ZONAMETRO')
                            )

SELECT ORR.ORDER_RELEASE_GID   
FROM ORDER_RELEASE ORR INNER JOIN        
ORDER_RELEASE_STATUS ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID   
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'   
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'   
AND ORR.DOMAIN_NAME = 'NBL/MX'   
AND ORR.DELIVERY_IS_APPT  = 'Y'   
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE   
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15   
AND ORR.DEST_LOCATION_GID IN (
                                SELECT LOCATION_GID 
                                FROM REGION_DETAIL 
                                WHERE REGION_GID IN ('NBL/MX.MXC|CANCUN','NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|PUEBLA','NBL/MX.MXC|VERACRUZ')
                            )

SELECT ORR.ORDER_RELEASE_GID
FROM ORDER_RELEASE ORR INNER JOIN
ORDER_RELEASE_STATUS ORS ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'
AND ORR.DOMAIN_NAME = 'NBL/MX'
AND ORR.DELIVERY_IS_APPT  = 'Y'
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE
AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE - 7 AND SYSDATE + 15
AND ORR.DEST_LOCATION_GID IN (
                                SELECT LOCATION_GID
                                FROM REGION_DETAIL
                                WHERE REGION_GID IN ('NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|CULIACAN','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|MONCLOVA','NBL/MX.MTY|TORREON')
                            )

SELECT * FROM REGION
WHERE REGION_GID IN ('NBL/MX.MXC|CANCUN','NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|PUEBLA','NBL/MX.MXC|VERACRUZ')

SELECT * FROM REGION
WHERE REGION_GID IN ('NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|CULIACAN','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|MONCLOVA','NBL/MX.MTY|TORREON')