SELECT RD.REGION_GID, R.REGION_XID, RD.LOCATION_GID, L.LOCATION_XID
FROM REGION_DETAIL RD INNER JOIN
    REGION R ON R.REGION_GID = RD.REGION_GID INNER JOIN
    LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RD.REGION_GID IN (
--'NBL/MX.MXC ALMARAZ CELAYA',
--'NBL/MX.MXC ALMARAZ TOLUCA',
--'NBL/MX.MXC ALMARAZ TULTITLAN',
'NBL/MX.MXC CDMX ZONAMETRO',
'NBL/MX.MXC CHALCO',
'NBL/MX.MXC CUAUTITLAN',
--'NBL/MX.MXC DEDICADOS SUPERTRACK',
'NBL/MX.MXC DEDICADOS TEM',
--'NBL/MX.MXC ELOLA GDL',
--'NBL/MX.MXC JJGC CANCUN',
--'NBL/MX.MXC JJGC MERIDA',
--'NBL/MX.MXC JJGC VILLAHERMOSA',
--'NBL/MX.MXC MEXAMERIK SAT�LITE',
--'NBL/MX.MXC MONTERREY',
--'NBL/MX.MXC TMS DEDICADOS',
--'NBL/MX.MXC TRANSALMAR CUAUTI',
--'NBL/MX.MXC TRANSALMAR QUERETARO',
'NBL/MX.MXC VERACRUZ')