SELECT 
LC.LOCATION_GID
,LC.LOCATION_NAME
,LC.CITY
,LC.PROVINCE_CODE 
,LC.PROVINCE
,REGEXP_SUBSTR(LC.LOCATION_NAME, '[^,]+', 1, 4) AS PROVINCE_CODE3
,LC.UPDATE_DATE
FROM LOCATION LC 
WHERE LC.LOCATION_GID LIKE 'NBL.CUS%%' 
AND LC.UPDATE_DATE > TO_DATE('2026-01-15', 'YYYY-MM-DD') 
AND LC.COUNTRY_CODE3_GID = 'MEX'
ORDER BY LC.UPDATE_DATE ASC
;




SELECT 'IMPULSORA ,GABRIELA RIVERA OSUNA SAH MORE,HUETAMO,MIC,MX' AS LOCATION_NAME, 
REGEXP_SUBSTR('IMPULSORA ,GABRIELA RIVERA OSUNA SAH MORE,HUETAMO,MIC,MX', '[^,]+', 1, 1) AS PROVINCE_CODE3
FROM DUAL;