SELECT DISTINCT RG.RATE_GEO_GID,RG.RATE_OFFERING_GID,RG.X_LANE_GID,RG.EFFECTIVE_DATE,RG.EXPIRATION_DATE,
RG.INSERT_USER,RG.INSERT_DATE,RG.IS_ACTIVE,

RO.SERVPROV_GID,ROSS.SPECIAL_SERVICE_CODE_GID,RO.TRANSPORT_MODE_GID,RO.MAX_WEIGHT_CONSTRAINT,

cl.CAPACITY_LIMIT_GID,cl.SUN_LIMIT,cl.MON_LIMIT,a.CAPACITY_COMMITMENT_ALLOC_GID,a.ALLOCATION_GROUP_GID,b.COMMIT_PERC,

t.ACCESSORIAL_CODE_GID

FROM rate_geo rg

LEFT JOIN RATE_OFFERING RO
ON RO.RATE_OFFERING_GID = rg.rate_offering_gid

LEFT JOIN RATE_GEO_ACCESSORIAL t
ON t.rate_geo_gid = rg.rate_geo_gid

LEFT JOIN ro_special_service ross
ON ross.rate_offering_gid = rg.rate_offering_gid

LEFT JOIN ACCESSORIAL_COST ACC
ON acc.accessorial_cost_gid = t.accessorial_cost_gid

LEFT JOIN RATE_GEO_COST RCC
ON RG.RATE_GEO_GID = RCC.RATE_GEO_COST_GROUP_GID

LEFT JOIN capacity_limit cl
ON cl.x_lane_gid=rg.x_lane_gid AND cl.capacity_group_gid = RG.RATE_OFFERING_GID AND CL.EXPIRATION_DATE > SYSDATE

LEFT JOIN CAPACITY_COMMITMENT_ALLOC a
ON a.x_lane_gid = rg.x_lane_gid AND ross.SPECIAL_SERVICE_CODE_GID = a.allocation_group_gid AND A.EXPIRATION_DATE > SYSDATE

LEFT JOIN CAPACITY_COMMITMENT_ALLOC_D b 
on b.CAPACITY_COMMITMENT_ALLOC_GID = a.CAPACITY_COMMITMENT_ALLOC_GID AND ro.servprov_gid = b.servprov_gid

WHERE rg.is_active = 'Y'
AND rg.domain_name = 'NBL'
AND rg.expiration_date > SYSDATE
AND ROSS.SPECIAL_SERVICE_CODE_GID NOT IN ('NBL.NON_FLEET','NBL.TIER-0-RATE')
AND b.COMMIT_PERC != 100
AND t.ACCESSORIAL_CODE_GID != 'NBL.FLAT_RATE'