ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

SELECT *
FROM RATE_GEO@OTMRO.NIAGARAWATER.COM
WHERE RATE_GEO_XID LIKE '%MXC%CHALCO%'
AND DOMAIN_NAME = 'NBL/MX'
AND IS_ACTIVE = 'Y';



--RATE_GEO_XID LIKE '%MXC%CHALCO%' AND DOMAIN_NAME = 'NBL/MX' AND IS_ACTIVE = 'Y'

--Correccion XLanes Foraneo Corto

SELECT RD.REGION_GID, L.LOCATION_GID, L.CITY
FROM REGION_DETAIL RD INNER JOIN
LOCATION L ON RD.LOCATION_GID = L.LOCATION_GID
WHERE RD.REGION_GID = 'NBL/MX.MTY|FORANEO_CORTO'
ORDER BY L.CITY


----Script to find X_LANE_GID that are numeric in RATE_GEO and their corresponding X_LANE_GID in X_LANE table
SELECT T.RATE_GEO_GID,T.RATE_GEO_XID, T.RATE_OFFERING_GID,  T.SOURCE_REGION_GID, T.DEST_REGION_GID, T.X_LANE_GID OLD_X_LANE_GID, XL1.X_LANE_GID NEW_X_LANE_GID
FROM (
        SELECT RG.RATE_GEO_GID, RG.RATE_GEO_XID, RG.RATE_OFFERING_GID, RG.X_LANE_GID, XL.X_LANE_XID, XL.SOURCE_REGION_GID, XL.DEST_REGION_GID
        FROM RATE_GEO RG INNER JOIN 
        X_LANE XL ON RG.X_LANE_GID = XL.X_LANE_GID
        WHERE REGEXP_LIKE(XL.X_LANE_XID, '^[[:digit:]]+$')
        AND RG.DOMAIN_NAME = 'NBL/MX'
        AND RG.IS_ACTIVE = 'Y'
) T INNER JOIN X_LANE XL1 ON T.SOURCE_REGION_GID  = XL1.SOURCE_REGION_GID AND T.DEST_REGION_GID = XL1.DEST_REGION_GID
WHERE NOT REGEXP_LIKE(XL1.X_LANE_XID, '^[[:digit:]]+$')
ORDER BY T.RATE_GEO_GID, XL1.X_LANE_GID