
SELECT L.PROVINCE_CODE
FROM REGION_DETAIL RD INNER JOIN 
LOCATION L ON RD.LOCATION_GID = L.LOCATION_GID 
WHERE RD.REGION_GID LIKE '%DEDICADOS%' 
GROUP BY L.PROVINCE_CODE

SELECT RATE_GEO_GID, X_LANE_GID, RATE_SERVICE_GID, SOURCE_REGION_GID, DEST_REGION_GID, PROVINCE_CODE
FROM (
SELECT RG.RATE_GEO_GID, RG.X_LANE_GID, RG.RATE_SERVICE_GID, LA.SOURCE_REGION_GID, LA.DEST_REGION_GID, L.PROVINCE_CODE
FROM RATE_GEO RG INNER JOIN
RATE_OFFERING RO ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
X_LANE LA ON LA.X_LANE_GID = RG.X_LANE_GID INNER JOIN
REGION_DETAIL RD ON RD.REGION_GID = LA.DEST_REGION_GID INNER JOIN
LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RO.DOMAIN_NAME = 'NBL/MX'
AND RO.IS_ACTIVE = 'Y'
AND RG.IS_ACTIVE = 'Y'
AND RO.RATE_OFFERING_XID LIKE '%DEDICADOS%'
) T
GROUP BY RATE_GEO_GID, X_LANE_GID, RATE_SERVICE_GID, SOURCE_REGION_GID, DEST_REGION_GID, PROVINCE_CODE
ORDER BY RATE_GEO_GID, PROVINCE_CODE

SELECT SOURCE_REGION_GID, PROVINCE_CODE, RATE_SERVICE_GID 
FROM (
SELECT RG.RATE_GEO_GID, RG.X_LANE_GID, RG.RATE_SERVICE_GID, LA.SOURCE_REGION_GID, LA.DEST_REGION_GID, L.PROVINCE_CODE
FROM RATE_GEO RG INNER JOIN
RATE_OFFERING RO ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
X_LANE LA ON LA.X_LANE_GID = RG.X_LANE_GID INNER JOIN
REGION_DETAIL RD ON RD.REGION_GID = LA.DEST_REGION_GID INNER JOIN
LOCATION L ON L.LOCATION_GID = RD.LOCATION_GID
WHERE RO.DOMAIN_NAME = 'NBL/MX'
AND RO.IS_ACTIVE = 'Y'
AND RG.IS_ACTIVE = 'Y'
AND RO.RATE_OFFERING_XID NOT LIKE '%DEDICADOS%'
) T
GROUP BY SOURCE_REGION_GID, PROVINCE_CODE, RATE_SERVICE_GID 
ORDER BY SOURCE_REGION_GID, PROVINCE_CODE

SELECT L.PROVINCE_CODE
FROM REGION_DETAIL RD INNER JOIN 
LOCATION L ON RD.LOCATION_GID = L.LOCATION_GID 
WHERE RD.REGION_GID LIKE 'NBL/MX.3MX|MEXICALI' 
GROUP BY L.PROVINCE_CODE
