----Rates

RATE_OFFERING  RATE_OFFERING_GID  
RATE_GEO  RATE_OFFERING_GID  RATE_SERVICE_GID  IS_ACTIVE
RATE_GEO_COST_GROUP   RATE_GEO_GID 
RATE_GEO_COST  CHARGE_AMOUNT

SELECT RATE_OFFERING_XID, RATE_GEO_XID,  RATE_SERVICE_GID, CHARGE_AMOUNT
FROM RATE_OFFERING RO INNER JOIN
RATE_GEO RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID
RATE_GEO_COST_GROUP RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID
RATE_GEO_COST RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID
WHERE RG.IS_ACTIVE = 'Y'
AND RO.DOMAIN_NAME = 'NBL/MX'


SELECT * FROM PACKAGED_ITEM
WHERE PACKAGED_ITEM_XID = '1894-7115585';

SELECT RO.RATE_OFFERING_XID, RG.RATE_GEO_XID, RG.RATE_SERVICE_GID, RG.X_LANE_GID, RTRIM(TO_CHAR(RGC.CHARGE_AMOUNT, '999,999,999.99')) CHARGE_AMOUNT
FROM RATE_OFFERING RO INNER JOIN
RATE_GEO RG ON RO.RATE_OFFERING_GID = RG.RATE_OFFERING_GID INNER JOIN
RATE_GEO_COST_GROUP RGCG ON RG.RATE_GEO_GID = RGCG.RATE_GEO_GID INNER JOIN
RATE_GEO_COST RGC ON RGCG.RATE_GEO_COST_GROUP_GID = RGC.RATE_GEO_COST_GROUP_GID INNER JOIN
X_LANE  XL ON XL.X_LANE_GID = RG.X_LANE_GID
WHERE RG.IS_ACTIVE = 'Y'
AND RO.DOMAIN_NAME = 'NBL/MX'
ORDER BY RO.RATE_OFFERING_XID, RG.RATE_GEO_XID, RG.X_LANE_GID, XL.SOURCE_REGION_GID;



-- Capacity Limit / Commitment Allocation
-----------------------------------------
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

-- Chalco
SELECT *
FROM (
    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE CU INNER JOIN
    CAPACITY_GROUP CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID = 'NBL/MX.MXC|MXC CHALCO'
    AND TRUNC(START_DATE) BETWEEN '01/12/2023' AND '27/12/2023'
    AND USAGE > 0
    ORDER BY LIMIT DESC
)
PIVOT
(
    SUM (LIMIT) LIMIT, 
    SUM (USAGE) USAGE
    FOR CAPACITY_GROUP_XID IN ('TMS_23' TMS,'ANDRADE_23' ANDRADE,'TEM_DEDICADOS_23' TEM_D,'CORONA_23' CORONA,'FEMSA_23' FEMSA)
)
ORDER BY START_DATE ASC;

-- Cuautitlan
SELECT *
FROM (
    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE CU INNER JOIN
    CAPACITY_GROUP CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID = 'NBL/MX.MXC|MXC CUAUTITLAN'
    AND TRUNC(START_DATE) BETWEEN '01/12/2023' AND '27/12/2023'
    AND USAGE > 0
    ORDER BY LIMIT DESC
)
PIVOT
(
    SUM (LIMIT) LIMIT, 
    SUM (USAGE) USAGE
    FOR CAPACITY_GROUP_XID IN ('TMS_23' TMS,'ANDRADE_23' ANDRADE,'TEM_DEDICADOS_23' TEM_D,'TEM_23' TEM, 'CORONA_23' CORONA,'FEMSA_23' FEMSA, 'MEXAMERIK_23' MEXAMERIK)
)
ORDER BY START_DATE ASC;


    SELECT X_LANE_GID, LIMIT, USAGE, CG.CAPACITY_GROUP_XID, TO_CHAR(CU.START_DATE, 'DD/MM/YYYY') START_DATE
    FROM CAPACITY_USAGE CU INNER JOIN
    CAPACITY_GROUP CG ON CU.CAPACITY_GROUP_GID = CG.CAPACITY_GROUP_GID INNER JOIN
    SERVPROV SP ON SP.SERVPROV_GID = CG.SERVPROV_GID INNER JOIN
    SCAC SC ON SC.SCAC_GID = SP.SCAC_GID INNER JOIN
    LOCATION L ON L.LOCATION_GID = SP.SERVPROV_GID
    WHERE CU.DOMAIN_NAME = 'NBL/MX'
    AND CU.X_LANE_GID = 'NBL/MX.MXC|MXC CDMX'
    --AND TO_CHAR(START_DATE, 'DD/MM/YYYY') BETWEEN '10/12/2023' AND '12/12/2023'
    AND TRUNC(START_DATE) BETWEEN '10/12/2023' AND '12/12/2023'
    ORDER BY LIMIT DESC;


SELECT CAU.COMMIT_ALLOC_USAGE_XID, CCA.CAPACITY_COMMITMENT_ALLOC_XID, START_DATE, PLANNED_TOTAL_COUNT, CCAD.COMMIT_PERC
FROM COMMIT_ALLOC_USAGE CAU INNER JOIN
CAPACITY_COMMITMENT_ALLOC  CCA ON CCA.CAPACITY_COMMITMENT_ALLOC_GID  = CAU.CAPACITY_COMMITMENT_ALLOC_GID INNER JOIN
CAPACITY_COMMITMENT_ALLOC_D CCAD ON CCA.CAPACITY_COMMITMENT_ALLOC_GID = CCAD.CAPACITY_COMMITMENT_ALLOC_GID
WHERE CCA.DOMAIN_NAME = 'NBL/MX'
AND CCA.X_LANE_GID = 'NBL/MX.MXC|MXC CHALCO'
AND TRUNC(START_DATE) BETWEEN '10/12/2023' AND '12/12/2023'
ORDER BY START_DATE ASC;

-- CAU.CAPACITY_COMMITMENT_ALLOC_XID, CAU.START_DATE, CAU.PLANNED_TOTAL_COUNT, CAUD.SERVPROV_GID, CAUD.COMMIT_PERC, CAUD.PLANNED_COUNT, CAUD.RATE_OFFERING_GID

SELECT CAU.CAPACITY_COMMITMENT_ALLOC_GID, CAU.START_DATE, CAU.PLANNED_TOTAL_COUNT, CAUD.SERVPROV_GID, CAUD.COMMIT_PERC, CAUD.PLANNED_COUNT, CAUD.RATE_OFFERING_GID 
FROM COMMIT_ALLOC_USAGE CAU INNER JOIN
COMMIT_ALLOC_USAGE_D CAUD ON CAU.COMMIT_ALLOC_USAGE_GID = CAUD.COMMIT_ALLOC_USAGE_GID
WHERE TRUNC(START_DATE) BETWEEN '10/12/2023' AND '12/12/2023'
AND CAU.DOMAIN_NAME = 'NBL/MX';

SELECT * FROM SHIP_COMMIT_ALLOC_JOIN;

SELECT * FROM REPORTOWNER.CAPACITY_COMMITMENT;

SELECT * FROM REPORTOWNER.CAPACITY_USAGE
WHERE TRUNC(START_DATE) BETWEEN '10/12/2023' AND '12/12/2023'
AND DOMAIN_NAME = 'NBL/MX';