SELECT BULK_PLAN_XID, QUERY_NAME, START_TIME, END_TIME, NUM_OF_ORDERS_SELECTED, NUM_OF_ORDERS_PLANNED
FROM BULK_PLAN
WHERE DOMAIN_NAME = 'NBL/MX'
AND BULK_PLAN_XID LIKE '%OR%'
AND TO_CHAR(START_TIME, 'YYYY-MM-DD') > '2025-01-01'
ORDER BY START_TIME DESC;

SELECT LOCATION_NAME, INSERT_DATE, SUM(NUM_OF_ORDERS)
FROM (
        SELECT L.LOCATION_NAME, TO_CHAR(O.INSERT_DATE, 'YYYY-MM-DD') INSERT_DATE, COUNT(*) NUM_OF_ORDERS
        FROM ORDER_RELEASE O INNER JOIN
        LOCATION L ON O.SOURCE_LOCATION_GID = L.LOCATION_GID
        WHERE O.DOMAIN_NAME = 'NBL/MX'
        AND TO_CHAR(O.INSERT_DATE, 'YYYY-MM-DD') > '2024-12-31'
        GROUP BY  L.LOCATION_NAME, O.INSERT_DATE
    ) T
GROUP BY LOCATION_NAME, INSERT_DATE
ORDER BY INSERT_DATE