--MTY_OR_BULKPLAN_EDM
SELECT ORR.ORDER_RELEASE_GID  
FROM ORDER_RELEASE ORR   INNER JOIN 
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'  
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')  
AND ORR.DEST_LOCATION_GID IN ( 
                                SELECT LOCATION_GID  
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|TORREON','NBL/MX.MTY|MONCLOVA',  
                                'NBL/MX.MTY|PIEDRAS NEGRAS','NBL/MX.MTY|REYNOSA','NBL/MX.MTY|NUEVO LAREDO','NBL/MX.MTY|TAMPICO','NBL/MX.MTY|DURANGO', 
                                'NBL/MX.MTY|GOMEZ PALACIO','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|DELICIAS',  'NBL/MX.MTY|PARRAL','NBL/MX.MTY|CD JUAREZ', 
                                'NBL/MX.MTY|CULIACAN','NBL/MX.MTY|MAZATLAN','NBL/MX.MTY|HERMOSILLO','NBL/MX.MTY|OBREGON','NBL/MX.MTY|MOCHIS','NBL/MX.MTY|SAN LUIS POTOSI',  
                                'NBL/MX.MTY|AGUASCALIENTES','NBL/MX.MTY|TLAJOMULCO','NBL/MX.MTY|LEON','NBL/MX.MTY|GUADALAJARA','NBL/MX.MTY|IRAPUATO','NBL/MX.MTY|TLAQUEPAQUE', 
                                'NBL/MX.MTY|VALLARTA','NBL/MX.MTY|TEPIC',  'NBL/MX.MTY|ZAPOPAN','NBL/MX.MTY|MORELIA','NBL/MX.MTY|ZACATECAS') 
                            ) 
GROUP BY ORR.ORDER_RELEASE_GID 

--3PL_OR_BULKPLAN_EDM
SELECT ORR.ORDER_RELEASE_GID  
FROM ORDER_RELEASE ORR   INNER JOIN 
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'  
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')      
AND ORR.DEST_LOCATION_GID IN ( 
                                SELECT LOCATION_GID  
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.3MX|CULIACAN','NBL/MX.3TJ|TIJUANA','NBL/MX.3TJ|CABOS','NBL/MX.3TJ|MEXICALI','NBL/MX.3TJ|ENSENADA') 
                            ) 
GROUP BY ORR.ORDER_RELEASE_GID 

--MXC_OR_BULKPLAN_EDM
SELECT ORR.ORDER_RELEASE_GID  
FROM ORDER_RELEASE ORR   INNER JOIN  
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'  
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')      
AND ORR.DEST_LOCATION_GID IN ( 
                                SELECT LOCATION_GID  
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN','NBL/MX.MXC|GUSTAVO A MADERO','NBL/MX.MTY|ECATEPEC',  
                                'NBL/MX.MXC|TULTITLAN','NBL/MX.MXC|YAUTEPEC','NBL/MX.MXC|LOS REYES LA PAZ','NBL/MX.MXC|TEPOTZOTLAN','NBL/MX.MXC|METEPEC', 
                                'NBL/MX.MXC|TLAHUAC','NBL/MX.MXC|TEZOYUCA',  'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|AGUASCALIENTES', 
                                'NBL/MX.MXC|CELAYA','NBL/MX.MXC|LEON','NBL/MX.MXC|QUERETARO','NBL/MX.MXC|MORELIA',  'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|ACAPULCO','NBL/MX.MXC|TULANCINGO') 
                            ) 
GROUP BY ORR.ORDER_RELEASE_GID 

--AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE +1 AND SYSDATE + 15      

-------WO_REG_OR_BULKPLAN_EDM
SELECT ORR.ORDER_RELEASE_GID 
FROM ORDER_RELEASE ORR   INNER JOIN 
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN 
LOCATION L ON L.LOCATION_GID = ORR.DEST_LOCATION_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER' 
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')  
AND ORR.DEST_LOCATION_GID NOT IN (  
                                SELECT LOCATION_GID 
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN','NBL/MX.MXC|GUSTAVO A MADERO','NBL/MX.MTY|ECATEPEC',  
                                'NBL/MX.MXC|TULTITLAN','NBL/MX.MXC|YAUTEPEC','NBL/MX.MXC|LOS REYES LA PAZ','NBL/MX.MXC|TEPOTZOTLAN','NBL/MX.MXC|METEPEC', 
                                'NBL/MX.MXC|TLAHUAC','NBL/MX.MXC|TEZOYUCA',  'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|AGUASCALIENTES', 
                                'NBL/MX.MXC|CELAYA','NBL/MX.MXC|LEON','NBL/MX.MXC|QUERETARO','NBL/MX.MXC|MORELIA',  'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|ACAPULCO','NBL/MX.MXC|TULANCINGO', 
                                'NBL/MX.3MX|CULIACAN','NBL/MX.3TJ|TIJUANA','NBL/MX.3TJ|CABOS','NBL/MX.3TJ|MEXICALI','NBL/MX.3TJ|ENSENADA', 
                                'NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|TORREON','NBL/MX.MTY|MONCLOVA',  
                                'NBL/MX.MTY|PIEDRAS NEGRAS','NBL/MX.MTY|REYNOSA','NBL/MX.MTY|NUEVO LAREDO','NBL/MX.MTY|TAMPICO','NBL/MX.MTY|DURANGO', 
                                'NBL/MX.MTY|GOMEZ PALACIO','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|DELICIAS',  'NBL/MX.MTY|PARRAL','NBL/MX.MTY|CD JUAREZ', 
                                'NBL/MX.MTY|CULIACAN','NBL/MX.MTY|MAZATLAN','NBL/MX.MTY|HERMOSILLO','NBL/MX.MTY|OBREGON','NBL/MX.MTY|MOCHIS','NBL/MX.MTY|SAN LUIS POTOSI',  
                                'NBL/MX.MTY|AGUASCALIENTES','NBL/MX.MTY|TLAJOMULCO','NBL/MX.MTY|LEON','NBL/MX.MTY|GUADALAJARA','NBL/MX.MTY|IRAPUATO','NBL/MX.MTY|TLAQUEPAQUE',
                                'NBL/MX.MTY|VALLARTA','NBL/MX.MTY|TEPIC',  'NBL/MX.MTY|ZAPOPAN','NBL/MX.MTY|MORELIA','NBL/MX.MTY|ZACATECAS' 
                                ) 
                            ) 
GROUP BY ORR.ORDER_RELEASE_GID 

--AND ORR.EARLY_DELIVERY_DATE BETWEEN SYSDATE +1 AND SYSDATE + 15    

--AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')  


--Ordenes candidatas dentro de las regiones

--SELECT SUM(ORDER_RELEASE_GID)
--FROM (
--SELECT COUNT(ORR.ORDER_RELEASE_GID) ORDER_RELEASE_GID--, ORR.SOURCE_LOCATION_GID, ORR.DEST_LOCATION_GID, L.LOCATION_NAME  
SELECT ORR.ORDER_RELEASE_GID
FROM ORDER_RELEASE ORR   INNER JOIN 
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN
LOCATION L ON L.LOCATION_GID = ORR.DEST_LOCATION_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')      
AND ORR.DEST_LOCATION_GID IN ( 
                                SELECT LOCATION_GID 
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN','NBL/MX.MXC|GUSTAVO A MADERO','NBL/MX.MTY|ECATEPEC',  
                                'NBL/MX.MXC|TULTITLAN','NBL/MX.MXC|YAUTEPEC','NBL/MX.MXC|LOS REYES LA PAZ','NBL/MX.MXC|TEPOTZOTLAN','NBL/MX.MXC|METEPEC',
                                'NBL/MX.MXC|TLAHUAC','NBL/MX.MXC|TEZOYUCA',  'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|AGUASCALIENTES',
                                'NBL/MX.MXC|CELAYA','NBL/MX.MXC|LEON','NBL/MX.MXC|QUERETARO','NBL/MX.MXC|MORELIA',  'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|ACAPULCO','NBL/MX.MXC|TULANCINGO',
                                'NBL/MX.3MX|CULIACAN','NBL/MX.3TJ|TIJUANA','NBL/MX.3TJ|CABOS','NBL/MX.3TJ|MEXICALI','NBL/MX.3TJ|ENSENADA',
                                'NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|TORREON','NBL/MX.MTY|MONCLOVA',  
                                'NBL/MX.MTY|PIEDRAS NEGRAS','NBL/MX.MTY|REYNOSA','NBL/MX.MTY|NUEVO LAREDO','NBL/MX.MTY|TAMPICO','NBL/MX.MTY|DURANGO',
                                'NBL/MX.MTY|GOMEZ PALACIO','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|DELICIAS',  'NBL/MX.MTY|PARRAL','NBL/MX.MTY|CD JUAREZ',
                                'NBL/MX.MTY|CULIACAN','NBL/MX.MTY|MAZATLAN','NBL/MX.MTY|HERMOSILLO','NBL/MX.MTY|OBREGON','NBL/MX.MTY|MOCHIS','NBL/MX.MTY|SAN LUIS POTOSI',  
                                'NBL/MX.MTY|AGUASCALIENTES','NBL/MX.MTY|TLAJOMULCO','NBL/MX.MTY|LEON','NBL/MX.MTY|GUADALAJARA','NBL/MX.MTY|IRAPUATO','NBL/MX.MTY|TLAQUEPAQUE',
                                'NBL/MX.MTY|VALLARTA','NBL/MX.MTY|TEPIC',  'NBL/MX.MTY|ZAPOPAN','NBL/MX.MTY|MORELIA','NBL/MX.MTY|ZACATECAS'
                                )
                            )
GROUP BY ORR.ORDER_RELEASE_GID
) T

--Ordenes candidatas fuera de las regiones
SELECT SUM(ORDER_RELEASE_GID)
FROM (
SELECT COUNT(ORR.ORDER_RELEASE_GID) ORDER_RELEASE_GID--, ORR.SOURCE_LOCATION_GID, ORR.DEST_LOCATION_GID, L.LOCATION_NAME  
FROM ORDER_RELEASE ORR   INNER JOIN 
ORDER_RELEASE_STATUS ORS   ON ORR.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN
LOCATION L ON L.LOCATION_GID = ORR.DEST_LOCATION_GID     
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'     
AND ORS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_NEW'     
AND ORR.DOMAIN_NAME = 'NBL/MX'     
AND ORR.DELIVERY_IS_APPT  = 'Y'     
AND ORR.ORDER_RELEASE_TYPE_GID = 'SALES_ORDER'
AND ORR.EARLY_DELIVERY_DATE = ORR.LATE_DELIVERY_DATE     
AND TO_CHAR(ORR.EARLY_DELIVERY_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE +1, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')       
AND ORR.DEST_LOCATION_GID NOT IN ( 
                                SELECT LOCATION_GID 
                                FROM REGION_DETAIL  
                                WHERE REGION_GID   IN ('NBL/MX.MXC CHALCO','NBL/MX.MXC CUAUTITLAN','NBL/MX.MXC|GUSTAVO A MADERO','NBL/MX.MTY|ECATEPEC',  
                                'NBL/MX.MXC|TULTITLAN','NBL/MX.MXC|YAUTEPEC','NBL/MX.MXC|LOS REYES LA PAZ','NBL/MX.MXC|TEPOTZOTLAN','NBL/MX.MXC|METEPEC',
                                'NBL/MX.MXC|TLAHUAC','NBL/MX.MXC|TEZOYUCA',  'NBL/MX.MXC|VILLAHERMOSA','NBL/MX.MXC|MERIDA','NBL/MX.MXC|AGUASCALIENTES',
                                'NBL/MX.MXC|CELAYA','NBL/MX.MXC|LEON','NBL/MX.MXC|QUERETARO','NBL/MX.MXC|MORELIA',  'NBL/MX.MXC|PUEBLA','NBL/MX.MXC|ACAPULCO','NBL/MX.MXC|TULANCINGO',
                                'NBL/MX.3MX|CULIACAN','NBL/MX.3TJ|TIJUANA','NBL/MX.3TJ|CABOS','NBL/MX.3TJ|MEXICALI','NBL/MX.3TJ|ENSENADA',
                                'NBL/MX.MTY NUEVO LEON','NBL/MX.MTY|SALTILLO','NBL/MX.MTY|TORREON','NBL/MX.MTY|MONCLOVA',  
                                'NBL/MX.MTY|PIEDRAS NEGRAS','NBL/MX.MTY|REYNOSA','NBL/MX.MTY|NUEVO LAREDO','NBL/MX.MTY|TAMPICO','NBL/MX.MTY|DURANGO',
                                'NBL/MX.MTY|GOMEZ PALACIO','NBL/MX.MTY|CHIHUAHUA','NBL/MX.MTY|DELICIAS',  'NBL/MX.MTY|PARRAL','NBL/MX.MTY|CD JUAREZ',
                                'NBL/MX.MTY|CULIACAN','NBL/MX.MTY|MAZATLAN','NBL/MX.MTY|HERMOSILLO','NBL/MX.MTY|OBREGON','NBL/MX.MTY|MOCHIS','NBL/MX.MTY|SAN LUIS POTOSI',  
                                'NBL/MX.MTY|AGUASCALIENTES','NBL/MX.MTY|TLAJOMULCO','NBL/MX.MTY|LEON','NBL/MX.MTY|GUADALAJARA','NBL/MX.MTY|IRAPUATO','NBL/MX.MTY|TLAQUEPAQUE',
                                'NBL/MX.MTY|VALLARTA','NBL/MX.MTY|TEPIC',  'NBL/MX.MTY|ZAPOPAN','NBL/MX.MTY|MORELIA','NBL/MX.MTY|ZACATECAS'
                                )
                            )
GROUP BY ORR.ORDER_RELEASE_GID
) T



SELECT DISTINCT ORDER_RELEASE_TYPE_GID
FROM ORDER_RELEASE
WHERE DOMAIN_NAME = 'NBL/MX'
AND EARLY_DELIVERY_DATE BETWEEN SYSDATE -30 AND SYSDATE + 15  


SELECT TO_CHAR(SYSDATE +1, 'YYYY-MM-DD'), TO_CHAR(SYSDATE + 15, 'YYYY-MM-DD')
FROM DUAL