SELECT ORE.ORDER_RELEASE_GID,
UTC.GET_LOCAL_DATE(ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) AS EARLY_DELIVERY_DATE,
TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 11:59:59', 'YYYY-MM-DD HH24:MI:SS') AS END_OF_DAY, --Usar este formato en Where
TO_DATE(TO_CHAR(CAST(FROM_TZ(CAST(SYSDATE AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE), 'YYYY-MM-DD') || ' 11:59:59', 'YYYY-MM-DD HH24:MI:SS') AS END_OF_DAY
FROM ORDER_RELEASE ORE INNER JOIN  
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN  
LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID INNER JOIN  
TIME_ZONE TZ ON TZ.time_zone_gid = LOC.time_zone_gid    
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'    
AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL')   
AND ORE.DOMAIN_NAME = 'NBL/MX'    
AND UTC.GET_LOCAL_DATE(ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID)
BETWEEN  TO_DATE(TO_CHAR(SYSDATE - 7, 'YYYY-MM-DD') || ' 00:00:00', 'YYYY-MM-DD HH24:MI:SS'  
AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 11:59:59', 'YYYY-MM-DD HH24:MI:SS' ;
--GROUP BY ORE.ORDER_RELEASE_GID


SELECT TO_TIMESTAMP(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS'), 
TO_CHAR(TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS START_OF_DAY
FROM dual;



SELECT ORE.ORDER_RELEASE_GID 
FROM ORDER_RELEASE ORE INNER JOIN  
ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN  
LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID 
WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'    
AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL')   
AND ORE.DOMAIN_NAME = 'NBL/MX'    
AND UTC.GET_LOCAL_DATE(ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) 
BETWEEN  TO_DATE(TO_CHAR(SYSDATE - 7, 'YYYY-MM-DD') || ' 00:00:00', 'YYYY-MM-DD HH24:MI:SS')  
AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 11:59:59', 'YYYY-MM-DD HH24:MI:SS') 
GROUP BY ORE.ORDER_RELEASE_GID


SELECT ORE.ORDER_RELEASE_GID FROM ORDER_RELEASE ORE INNER JOIN ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL') AND ORE.DOMAIN_NAME = 'NBL/MX' AND UTC.GET_LOCAL_DATE(ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) BETWEEN  TO_DATE(TO_CHAR(SYSDATE - 7, 'YYYY-MM-DD') || ' 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 11:59:59', 'YYYY-MM-DD HH24:MI:SS') GROUP BY ORE.ORDER_RELEASE_GID



SELECT ORE.ORDER_RELEASE_GID  FROM ORDER_RELEASE ORE INNER JOIN  ORDER_RELEASE_STATUS ORS ON ORE.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID INNER JOIN  LOCATION LOC ON LOC.LOCATION_GID = ORE.SOURCE_LOCATION_GID INNER JOIN  TIME_ZONE TZ ON TZ.time_zone_gid = LOC.time_zone_gid    WHERE ORS.STATUS_TYPE_GID = 'NBL/MX.PLANNING'    AND ORS.STATUS_VALUE_GID IN ('NBL/MX.PLANNING_EXECUTED - FINAL','NBL/MX.PLANNING_PLANNED - FINAL')    AND ORE.DOMAIN_NAME = 'NBL/MX'    AND UTC.GET_LOCAL_DATE (ORE.EARLY_DELIVERY_DATE, ORE.SOURCE_LOCATION_GID) BETWEEN  CAST(FROM_TZ(CAST(SYSDATE - 7 AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)  AND CAST(FROM_TZ(CAST(SYSDATE AS TIMESTAMP), 'UTC') AT TIME ZONE TZ.time_zone_XID AS DATE)  GROUP BY ORE.ORDER_RELEASE_GID