SELECT ORS.ORDER_RELEASE_GID 
FROM ORDER_RELEASE ORS INNER JOIN 
BULK_PLAN BP ON ORS.BULK_PLAN_GID = BP.BULK_PLAN_GID INNER JOIN 
ORDER_RELEASE_STATUS ORSS ON ORS.ORDER_RELEASE_GID = ORSS.ORDER_RELEASE_GID AND ORSS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' AND ORSS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_PLANNED - FAILED'
WHERE ORS.BULK_PLAN_GID = 'NBL/MX.20250618-0001'

SELECT ORDER_RELEASE_GID
FROM ORDER_RELEASE
WHERE ORDER_RELEASE_GID IN (
    SELECT ORS.ORDER_RELEASE_GID 
    FROM ORDER_RELEASE ORS INNER JOIN 
    BULK_PLAN BP ON ORS.BULK_PLAN_GID = BP.BULK_PLAN_GID INNER JOIN 
    ORDER_RELEASE_STATUS ORSS ON ORS.ORDER_RELEASE_GID = ORSS.ORDER_RELEASE_GID AND ORSS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' AND ORSS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_PLANNED - FAILED'
    WHERE ORS.BULK_PLAN_GID = 'NBL/MX.20250618-0001'
);


SELECT ORDER_RELEASE_GID 
FROM ORDER_RELEASE 
WHERE ORDER_RELEASE_GID IN ( 
    SELECT ORS.ORDER_RELEASE_GID 
    FROM ORDER_RELEASE ORS INNER JOIN 
    BULK_PLAN BP ON ORS.BULK_PLAN_GID = BP.BULK_PLAN_GID INNER JOIN 
    ORDER_RELEASE_STATUS ORSS ON ORS.ORDER_RELEASE_GID = ORSS.ORDER_RELEASE_GID AND ORSS.STATUS_TYPE_GID = 'NBL/MX.PLANNING' AND ORSS.STATUS_VALUE_GID = 'NBL/MX.PLANNING_PLANNED - FAILED' 
    WHERE ORS.BULK_PLAN_GID LIKE '%OR_BULKPLAN_EDM%'
    AND TO_CHAR(BP.INSERT_DATE, 'YYYY-MM-DD') = TO_CHAR(SYSDATE-1, 'YYYY-MM-DD')
) 

SELECT SHIPMENT_GID
FROM SHIPMENT
WHERE BULK_PLAN_GID = 'NBL/MX.20250618-0001'


SELECT SH.SHIPMENT_GID
FROM SHIPMENT SH INNER JOIN 
SHIPMENT_STATUS SSH ON SH.SHIPMENT_GID = SSH.SHIPMENT_GID
WHERE SH.BULK_PLAN_GID LIKE '%OR_BULKPLAN_EDM%' 
AND TO_CHAR(SH.INSERT_DATE, 'YYYY-MM-DD') = TO_CHAR(SYSDATE, 'YYYY-MM-DD')
AND SSH.STATUS_TYPE_GID = 'NBL/MX.SECURE RESOURCES'
AND SSH.STATUS_VALUE_GID = 'NBL/MX.SECURE RESOURCES_NOT STARTED'



SELECT SH.SHIPMENT_GID FROM SHIPMENT SH INNER JOIN SHIPMENT_STATUS SSH ON SH.SHIPMENT_GID = SSH.SHIPMENT_GID WHERE SH.BULK_PLAN_GID LIKE '%OR_BULKPLAN_EDM%' AND TO_CHAR(SH.INSERT_DATE, 'YYYY-MM-DD') BETWEEN TO_CHAR(SYSDATE-30, 'YYYY-MM-DD') AND TO_CHAR(SYSDATE, 'YYYY-MM-DD') AND SSH.STATUS_TYPE_GID = 'NBL/MX.SECURE RESOURCES' AND SSH.STATUS_VALUE_GID = 'NBL/MX.SECURE RESOURCES_NOT STARTED'