--Regiones

SELECT RG.X_LANE_GID
,XL.DEST_REGION_GID
,LC.LOCATION_GID
,LC.CITY
,LC.PROVINCE_CODE 
,REGEXP_SUBSTR(LC.LOCATION_NAME, '[^,]+', 1, 4) AS PROVINCE_CODE3 
FROM RATE_GEO RG INNER JOIN 
X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN 
REGION_DETAIL RD ON RD.REGION_GID = XL.DEST_REGION_GID INNER JOIN 
LOCATION LC ON LC.LOCATION_GID = RD.LOCATION_GID 
WHERE 1 = 1
--AND RG.IS_ACTIVE = 'Y' 
AND RG.DOMAIN_NAME = 'NBL/MX' 
AND LC.LOCATION_GID LIKE 'NBL.CUS%%' 
--AND LC.INSERT_DATE > TO_DATE('2025-12-01', 'YYYY-MM-DD') 
AND LC.CITY IN ('NUEVA ROSITA', 'OJINAGA', 'PALO BLANCO', 'SAN MARTIN OBISPO', 
'SANTA BARBARA', 'SANTA CRUZ JUXTLAHUACA', 'SATELITE', 'TLALCHAPA', 'ZACAPUATO', 
'PLAYA DEL CARMEN')
GROUP BY RG.X_LANE_GID, XL.DEST_REGION_GID,  
LC.CITY, LC.PROVINCE_CODE,LC.LOCATION_GID, LC.LOCATION_NAME 
ORDER BY RG.X_LANE_GID, XL.DEST_REGION_GID, LC.CITY,  
LC.PROVINCE_CODE,LC.LOCATION_GID, LC.LOCATION_NAME 
;