
SELECT RATE_GEO_XID,
SOURCE_REGION_GID,
CITY,
--PROVINCE_CODE3,
CHARGE_AMOUNT
FROM (
        SELECT RG.RATE_GEO_XID,
        --XL.X_LANE_XID,
        XL.SOURCE_REGION_GID,
        XL.DEST_REGION_GID,
        LC.CITY,
        RGC.CHARGE_AMOUNT,
        REGEXP_SUBSTR(LC.LOCATION_NAME, '[^,]+', 1, 4) AS PROVINCE_CODE3,
        LC.PROVINCE_CODE
        FROM RATE_GEO RG INNER JOIN
        X_LANE XL ON XL.X_LANE_GID = RG.X_LANE_GID INNER JOIN
        RATE_GEO_COST_GROUP RGCG ON RGCG.RATE_GEO_GID = RG.RATE_GEO_GID INNER JOIN
        RATE_GEO_COST RGC ON RGC.RATE_GEO_COST_GROUP_GID = RGCG.RATE_GEO_COST_GROUP_GID INNER JOIN
        REGION_DETAIL RD ON RD.REGION_GID = XL.DEST_REGION_GID INNER JOIN
        LOCATION LC ON LC.LOCATION_GID = RD.LOCATION_GID
        WHERE 1 = 1
        AND RG.IS_ACTIVE = 'Y'
        AND RG.DOMAIN_NAME = 'NBL/MX'
        AND (REGEXP_SUBSTR(LC.LOCATION_NAME, '[^,]+', 1, 4) IN ('CMX', 'CX') OR LC.PROVINCE_CODE IN ('CDMX', 'CX'))
        --ORDER BY XL.SOURCE_REGION_GID, LC.CITY
) T
GROUP BY RATE_GEO_XID, SOURCE_REGION_GID, CITY, CHARGE_AMOUNT
ORDER BY SOURCE_REGION_GID, RATE_GEO_XID, CITY, CHARGE_AMOUNT
;