-----EBS Database
SELECT TENDER_HEADER_ID, /*PURPOSE_CODE,*/ TRANSPORTATION_SHIPMENT_ID, ACCEPTANCE_RESPOND_BY, RESPONd_BY_TIME_ZONE, STATUS_NOTE, CREATION_DATE
FROM xxnig_tender_hdr_all H INNER JOIN
xxnig_tender_stops_all C ON H.TENDER_HEADER_ID = C.TENDER_HEADER_ID
WHERE CARRIER_ID = '2480207'
AND PURPOSE_CODE = '00'
ORDER BY CREATION_DATE,TRANSPORTATION_SHIPMENT_ID;

SELECT * 
FROM xxnig_tender_hdr_all
WHERE TRANSPORTATION_SHIPMENT_ID  LIKE '%MX%' --IN ('MX24042336')
ORDER BY CREATION_DATE DESC;
--TENDER_HEADER_ID = 18087966;

SELECT TH.TRANSPORTATION_SHIPMENT_ID, TS.* 
FROM xxnig_tender_stops_all TS INNER JOIN
xxnig_tender_hdr_all TH ON TS.TENDER_HEADER_ID = TH.TENDER_HEADER_ID
WHERE TRANSPORTATION_SHIPMENT_ID LIKE '%MX%'
ORDER BY STOP_DATE_1 DESC;
WHERE TRANSPORTATION_SHIPMENT_ID IN (
'MX24042336',
'MX24042337',
'MX24042270');
--AND STOP_SEQ = 2;


SELECT * 
FROM xxnig_tender_deliveries_all
WHERE TENDER_HEADER_ID = 18087966;

--Revision Diaria
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

SELECT TENDER_HEADER_ID, PURPOSE_CODE, TRANSPORTATION_SHIPMENT_ID, ACCEPTANCE_RESPOND_BY, RESPONd_BY_TIME_ZONE, STATUS_NOTE, CREATION_DATE 
FROM xxnig_tender_hdr_all
WHERE TRANSPORTATION_SHIPMENT_ID LIKE '%MX%' 
AND CREATION_DATE >= TRUNC(SYSDATE) - 7
ORDER BY CREATION_DATE DESC;


|