select S.SHIPMENT_XID,
        S.START_TIME, 
        WMS.STATUS_VALUE_GID, 
        ACC.STATUS_VALUE_GID, 
        S.SHIPMENT_TYPE_GID, 
        S.RATE_OFFERING_GID,
        S.SERVPROV_GID
from shipment_STATUS acc, shipment_STATUS wms, shipment s 
where s.shipment_gid = acc.shipment_gid 
and s.shipment_gid = wms.shipment_gid 
and s.DEST_LOCATION_GID LIKE 'NBL.CUS%'
AND ACC.STATUS_TYPE_GID = 'NBL/MX.SECURE RESOURCES'
AND ACC.STATUS_VALUE_GID = 'NBL/MX.SECURE RESOURCES_ACCEPTED'
AND WMS.STATUS_TYPE_GID = 'NBL/MX.WMS_STATUS'
--AND WMS.STATUS_VALUE_GID != 'NBL.WMS_SH_LOCKED'
AND S.DOMAIN_NAME = 'NBL/MX'
AND S.USER_DEFINED1_ICON_GID IS NULL
AND S.SHIPMENT_GID LIKE 'NBL/MX.MX%'
and s.start_time >= to_date('2025-01-06','YYYY-MM-DD')
order by S.START_TIME


select S.SHIPMENT_XID,
        S.START_TIME, 
        S.SHIPMENT_TYPE_GID, 
        S.RATE_OFFERING_GID,
        S.SERVPROV_GID
from shipment_STATUS acc, shipment_STATUS wms, shipment s 
where s.shipment_gid = acc.shipment_gid 
and s.shipment_gid = wms.shipment_gid 
--and s.DEST_LOCATION_GID LIKE 'NBL.CUS%'
AND ACC.STATUS_TYPE_GID = 'NBL/MX.SECURE RESOURCES'
AND ACC.STATUS_VALUE_GID = 'NBL/MX.SECURE RESOURCES_ACCEPTED'
AND S.DOMAIN_NAME = 'NBL/MX'
AND S.USER_DEFINED1_ICON_GID IS NULL
AND S.SHIPMENT_GID LIKE 'NBL/MX.MX%'
and s.start_time >= to_date('2026-01-06','YYYY-MM-DD')
group by S.SHIPMENT_XID,
        S.START_TIME, 
        S.SHIPMENT_TYPE_GID, 
        S.RATE_OFFERING_GID,
        S.SERVPROV_GID
order by S.START_TIME

---------Completo
SELECT S.SHIPMENT_GID, OM.SOURCE_LOCATION_GID AS OM_SOURCE_LOCATION_GID, 
ORE.SOURCE_LOCATION_GID AS OR_SOURCE_LOCATION_GID, 
SS1.LOCATION_GID AS SS1_LOCATION_GID, 
OM.DEST_LOCATION_GID AS OM_DEST_LOCATION_GID,
ORE.DEST_LOCATION_GID AS OR_DEST_LOCATION_GID,
SS2.LOCATION_GID AS SS2_LOCATION_GID,
SR1.SHIPMENT_REFNUM_VALUE AS ORIG_SOURCE,
SR2.SHIPMENT_REFNUM_VALUE AS CURRENT_SOURCE,
S.SOURCE_LOCATION_GID AS SOURCE_LOCATION_GID, 
S.DEST_LOCATION_GID  AS DEST_LOCATION_GID
FROM (
        SELECT SH.SHIPMENT_GID, MAX(SS.STOP_NUM) AS MAX_STOP_NUM, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
        FROM SHIPMENT SH INNER JOIN 
        SHIPMENT_STOP SS ON SH.SHIPMENT_GID = SS.SHIPMENT_GID
        WHERE SH.START_TIME >= TO_DATE('2025-01-05','YYYY-MM-DD')
        GROUP BY SH.SHIPMENT_GID, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
        HAVING MAX(SS.STOP_NUM) = 2
) S INNER JOIN
SHIPMENT_REFNUM SR1 ON S.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID IN ('NBL.ORIGINAL_SOURCE', 'NBL/MX.ORIGINAL_SOURCE') INNER JOIN
SHIPMENT_REFNUM SR2 ON S.SHIPMENT_GID = SR2.SHIPMENT_GID AND SR2.SHIPMENT_REFNUM_QUAL_GID IN ('NBL.CURRENT_SOURCE', 'NBL/MX.CURRENT_SOURCE') INNER JOIN
ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
SHIPMENT_STOP SS1 ON S.SHIPMENT_GID = SS1.SHIPMENT_GID AND SS1.STOP_NUM = 1 INNER JOIN
SHIPMENT_STOP SS2 ON S.SHIPMENT_GID = SS2.SHIPMENT_GID AND SS2.STOP_NUM = 2 INNER JOIN
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID 
WHERE 1 = 1
AND (
        (OM.SOURCE_LOCATION_GID != ORE.SOURCE_LOCATION_GID OR SS1.LOCATION_GID != ORE.SOURCE_LOCATION_GID OR SS1.LOCATION_GID != OM.SOURCE_LOCATION_GID ) 
        OR (OM.DEST_LOCATION_GID != ORE.DEST_LOCATION_GID OR SS2.LOCATION_GID != ORE.DEST_LOCATION_GID OR SS2.LOCATION_GID != OM.DEST_LOCATION_GID)
 )
 AND S.SHIPMENT_GID = 'NBL.NB53974328'
 AND S.ATTRIBUTE_NUMBER14 = 6
ORDER BY S.SHIPMENT_GID
;

NBL.ORIGINAL_SOURCE
NBL.CURRENT_SOURCE

SELECT * FROM SHIPMENT_REFNUM  
WHERE SHIPMENT_GID = 'NBL.NB53974328'

/*
select * from t1 as of timestamp to_timestamp('02-MAY-17 11:00','DD-MON-RR HH24:MI');
 
 select * from shipment as of timestamp to_timestamp('2026-01-01 11:00','YYYY-MM-DD HH24:MI')
 where shipment_gid = 'NBL.NB53974328'
 ;

 SELECT * FROM shipment AS OF TIMESTAMP 
     TO_TIMESTAMP('2003-04-04 09:30:00', 'YYYY-MM-DD HH:MI:SS')
     WHERE shipment_gid = 'NBL.NB53974328'
*/

SELECT S.SHIPMENT_GID, MAX(SS.STOP_NUM) AS MAX_STOP_NUM
FROM SHIPMENT S INNER JOIN 
SHIPMENT_STOP SS ON S.SHIPMENT_GID = SS.SHIPMENT_GID
WHERE S.START_TIME >= TO_DATE('2025-01-05','YYYY-MM-DD')
GROUP BY S.SHIPMENT_GID
HAVING MAX(SS.STOP_NUM) = 2


SELECT department, MAX(salary) AS "Highest salary"
FROM employees
GROUP BY department
HAVING MAX(salary) > 45000;


--------------------------------------Final

SELECT S.SHIPMENT_GID, 
SR1.SHIPMENT_REFNUM_VALUE AS ORIG_SOURCE,
SR2.SHIPMENT_REFNUM_VALUE AS CURRENT_SOURCE,
S.SOURCE_LOCATION_GID AS SOURCE_LOCATION_GID
FROM (
        SELECT SH.SHIPMENT_GID, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
        FROM SHIPMENT SH
        WHERE SH.START_TIME >= TO_DATE('2025-01-05','YYYY-MM-DD')
        GROUP BY SH.SHIPMENT_GID, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
) S INNER JOIN
SHIPMENT_REFNUM SR1 ON S.SHIPMENT_GID = SR1.SHIPMENT_GID AND SR1.SHIPMENT_REFNUM_QUAL_GID IN ('NBL.ORIGINAL_SOURCE', 'NBL/MX.ORIGINAL_SOURCE') INNER JOIN
SHIPMENT_REFNUM SR2 ON S.SHIPMENT_GID = SR2.SHIPMENT_GID AND SR2.SHIPMENT_REFNUM_QUAL_GID IN ('NBL.CURRENT_SOURCE', 'NBL/MX.CURRENT_SOURCE') 
WHERE 1 = 1
AND S.ATTRIBUTE_NUMBER14 = 6
ORDER BY S.SHIPMENT_GID;


-----------ORGS
SELECT CORRE.SHIPMENT_GID, CORRE.ORIG_SOURCE, CORRE.CURRENT_SOURCE, NEWORGS.NEW_LOCATION_ID, CORRE.SOURCE_LOCATION_GID
FROM OTM_DATA_CORRECT CORRE LEFT JOIN
OTM_DATA_ORGS_OLD_NEW NEWORGS ON CORRE.CURRENT_SOURCE = NEWORGS.OLD_LOCATION_ID
WHERE CURRENT_SOURCE LIKE '%ORG%'
--AND CORRE.SHIPMENT_GID = 'NBL.NB53974328'
;

------------Sups
SELECT CORRE.SHIPMENT_GID, CORRE.ORIG_SOURCE, CORRE.CURRENT_SOURCE, NEWSUPP.NEW_SUPPLIER__LOCTION_ID, CORRE.SOURCE_LOCATION_GID
FROM OTM_DATA_CORRECT CORRE LEFT JOIN
OTM_DATA_SUPP_OLD_NEW NEWSUPP ON CORRE.CURRENT_SOURCE = NEWSUPP.OLD_SUPPLIET_LOCATION_ID
WHERE CURRENT_SOURCE LIKE '%SUP%'
;
--AND CORRE.SHIPMENT_GID = 'NBL.NB53974328'


--------Order Release

---------Completo
SELECT ORE.ORDER_RELEASE_GID, 
S.SHIPMENT_GID, 
ORE.SOURCE_LOCATION_GID AS OR_SOURCE_LOCATION_GID, 
OR1.ORDER_RELEASE_REFNUM_VALUE AS ORIG_SOURCE, 
OR2.ORDER_RELEASE_REFNUM_VALUE AS CURRENT_SOURCE, 
OR2.INSERT_USER, OR2.INSERT_DATE,
OR2.UPDATE_USER, OR2.UPDATE_DATE
FROM (
        SELECT SH.SHIPMENT_GID, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
        FROM SHIPMENT SH 
        --WHERE SH.START_TIME >= TO_DATE('2025-01-05','YYYY-MM-DD')
        GROUP BY SH.SHIPMENT_GID, SH.SOURCE_LOCATION_GID, SH.DEST_LOCATION_GID, SH.ATTRIBUTE_NUMBER14
) S INNER JOIN
ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID INNER JOIN
ORDER_RELEASE_REFNUM OR1 ON ORE.ORDER_RELEASE_GID = OR1.ORDER_RELEASE_GID AND OR1.ORDER_RELEASE_REFNUM_QUAL_GID IN ('NBL.ORIGINAL_SOURCE', 'NBL/MX.ORIGINAL_SOURCE') INNER JOIN
ORDER_RELEASE_REFNUM OR2 ON ORE.ORDER_RELEASE_GID = OR2.ORDER_RELEASE_GID AND OR2.ORDER_RELEASE_REFNUM_QUAL_GID IN ('NBL.CURRENT_SOURCE', 'NBL/MX.CURRENT_SOURCE') 
WHERE 1 = 1
AND S.ATTRIBUTE_NUMBER14 = 6
AND ORE.ORDER_RELEASE_GID = 'NBL.39765115'
ORDER BY ORE.ORDER_RELEASE_GID
;

select shipment_gid,
source_location_gid,
dest_location_gid,
SERVPROV,
UPDATE_USER,
DOMAIN_NAME
from shipment 
where shipment_gid in (
        select shipment_gid from order_movement 
        where order_release_gid in (
                                        SELECT order_release_gid FROM ORDER_RELEASE where ATTRIBUTE19 in ('CLOUD_ERP_CONVERSION_RECEIVED','CLOUD_ERP_CONVERSION_SENT')
                                ))
AND LENGTH(SOURCE_LOCATION_GID) > 11
 


SELECT COUNT(*) /*ORE.ORDER_RELEASE_GID, 
S.SHIPMENT_GID, 
ORE.SOURCE_LOCATION_GID AS OR_SOURCE_LOCATION_GID,
ORE.DEST_LOCATION_GID AS OR_DEST_LOCATION_GID,
ORE.SERVPROV_GID*/
FROM (
        select shipment_gid
        from shipment 
        where shipment_gid in (
                        select shipment_gid from order_movement 
                        where order_release_gid in (
                                        SELECT order_release_gid FROM ORDER_RELEASE where ATTRIBUTE19 in ('CLOUD_ERP_CONVERSION_RECEIVED','CLOUD_ERP_CONVERSION_SENT')
                                ))
) S INNER JOIN
ORDER_MOVEMENT OM ON S.SHIPMENT_GID = OM.SHIPMENT_GID INNER JOIN
ORDER_RELEASE ORE ON OM.ORDER_RELEASE_GID = ORE.ORDER_RELEASE_GID 
WHERE 1 = 1
AND LENGTH(ORE.SOURCE_LOCATION_GID) > 11
ORDER BY ORE.ORDER_RELEASE_GID;


SELECT ORE.ORDER_RELEASE_GID, 
        ORE.SHIPMENT_GID,
        ORE.OR_SOURCE_LOCATION_GID, 
        NVL(ORGSNEW.NEW_LOCATION_ID, ORE.OR_SOURCE_LOCATION_GID) NEW_LOCATION_ID,
        ORE.OR_DEST_LOCATION_GID,
        NVL(CUSNEW.NEW_CUS_LOC_ID, ORE.OR_DEST_LOCATION_GID) NEW_CUS_LOC_ID,
        ORE.SERVPROV_GID,
        NVL(CARNEW.NEW_ID, ORE.SERVPROV_GID) SERVPROV_NEW
FROM ORDER_RELEASE_KRISH ORE LEFT JOIN
OTM_DATA_ORGS_OLD_NEW ORGSNEW ON ORE.OR_SOURCE_LOCATION_GID = ORGSNEW.OLD_LOCATION_ID LEFT JOIN
OTM_DATA_CUS_OLD_NEW CUSNEW ON ORE.OR_DEST_LOCATION_GID = CUSNEW.OLD_CUS_LOC_ID LEFT JOIN
OTM_DATA_CARRIER_OLD_NEW CARNEW ON ORE.SERVPROV_GID = CARNEW.OLD_ID
--WHERE  (ORGSNEW.NEW_LOCATION_ID IS NULL OR CUSNEW.NEW_CUS_LOC_ID IS NULL)
;


SELECT ORE.OR_DEST_LOCATION_GID
FROM ORDER_RELEASE_KRISH ORE LEFT JOIN
OTM_DATA_ORGS_OLD_NEW ORGSNEW ON ORE.OR_SOURCE_LOCATION_GID = ORGSNEW.OLD_LOCATION_ID LEFT JOIN
OTM_DATA_CUS_OLD_NEW CUSNEW ON ORE.OR_DEST_LOCATION_GID = CUSNEW.OLD_CUS_LOC_ID LEFT JOIN
OTM_DATA_CARRIER_OLD_NEW CARNEW ON ORE.SERVPROV_GID = CARNEW.OLD_ID
WHERE  (ORGSNEW.NEW_LOCATION_ID IS NULL OR CUSNEW.NEW_CUS_LOC_ID IS NULL)
GROUP BY ORE.OR_DEST_LOCATION_GID
;