SELECT * FROM ALL_TAB_COLUMNS 
--WHERE COLUMN_NAME LIKE '%I_TRANSACTION_NO%'
WHERE COLUMN_NAME LIKE '%STOP_N%'
ORDER BY TABLE_NAME DESC

SELECT * FROM ALL_TAB_COLUMNS 
--WHERE COLUMN_NAME LIKE '%I_TRANSACTION_NO%'
WHERE TABLE_NAME LIKE '%BOV%'
ORDER BY TABLE_NAME DESC
