SELECT distinct ORH.ORDER_RELEASE_GID, ORL.ORDER_RELEASE_LINE_GID,
       SUBSTR (ORH.ORDER_RELEASE_GID, -8) AS DELIVERY_NUMBER,
       ORH.INDICATOR,
       SHP.INDICATOR AS SHIPMENT_INDICATOR,
       ORH.USER_DEFINED2_ICON_GID AS SHIP_CONFIRMED,
       ORH.ATTRIBUTE2  AS PENDING_REASON,
       ORH.PAYMENT_METHOD_CODE_GID AS PAYMENT_METHOD,
       ORH.USER_DEFINED5_ICON_GID  AS SPOT,
       ORH.USER_DEFINED1_ICON_GID AS SCHEDULED,
       (CASE
            WHEN (   ORH.USER_DEFINED1_ICON_GID = 'NBL.NBL_SCHEDULED_APPT'
                  OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_SCHEDULED_APPT'
                  OR ORH.USER_DEFINED1_ICON_GID = 'NBL.APPT_SCHEDULED'
                  OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_PENDING_APPT'
                  OR ORH.USER_DEFINED1_ICON_GID = 'ITEM')
            THEN 'Scheduled'
            ELSE 'Not Scheduled'
        END) AS SCHEDULE_FLAG,
       ORH.SOURCE_LOCATION_GID,
       ORH.DEST_LOCATION_GID,
       (CASE
            WHEN ORH.LATE_PICKUP_DATE IS NULL
            THEN  TO_CHAR(utc.get_local_date (ORH.LATE_DELIVERY_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS')
            ELSE  TO_CHAR(utc.get_local_date (ORH.LATE_PICKUP_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS')
        END) AS REQUEST_DATE,
        TO_CHAR(utc.get_local_date (ORH.INSERT_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS INSERT_DATE,
       ORH.TRANSPORT_MODE_GID,
       ORH.RATE_OFFERING_GID,
       --OREF.ORDER_RELEASE_REFNUM_VALUE as ORIGINAL_REQUEST_DATE,
       OREF2.ORDER_RELEASE_REFNUM_VALUE   AS SCHEDULER,
       OREF3.ORDER_RELEASE_REFNUM_VALUE   AS ORDER_NUMBER,
       OREF4.INSERT_USER AS SCHEDULE_INSERT_USER,
       OREF5.ORDER_RELEASE_REFNUM_VALUE   AS CUST_PO,
       OREF6.ORDER_RELEASE_REFNUM_VALUE   AS CUSTOMER_REGION,
       OREM.REMARK_TEXT AS SHIP_DATE,
       TO_CHAR(utc.get_local_date (OREF4.INSERT_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS SCHEDULE_INSERT_DATE,
       SHP.SHIPMENT_GID,
       TO_CHAR(utc.get_local_date (SHP.START_TIME, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS START_TIME,
       --SHP.SERVPROV_GID,
       TO_CHAR(utc.get_local_date (STP.APPOINTMENT_PICKUP, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_PICKUP,
       --SS.STATUS_VALUE_GID as TENDER_STATUS,
       (CASE
            WHEN SS.STATUS_VALUE_GID IS NULL THEN 'Not Tendered'
            ELSE 'Tendered'
        END)  AS TENDER_STATUS,
       (CASE
            WHEN SS.STATUS_VALUE_GID IS NOT NULL
            THEN 'Tendered'
            WHEN     (   ORH.USER_DEFINED1_ICON_GID =
                         'NBL.NBL_SCHEDULED_APPT'
                      OR ORH.USER_DEFINED1_ICON_GID =
                         'NBL.CAR_SCHEDULED_APPT'
                      OR ORH.USER_DEFINED1_ICON_GID = 'NBL.APPT_SCHEDULED'
                      OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_PENDING_APPT'
                      OR ORH.USER_DEFINED1_ICON_GID = 'ITEM')
                 AND SS.STATUS_VALUE_GID IS NULL
            THEN 'Scheduled Not Tendered'
            ELSE 'Not Scheduled'
        END) AS ORDER_STATUS,
       SS2.STATUS_VALUE_GID  AS WMS_STATUS,
       --SLO.LOCATION_NAME as SOURCE,
       --DLO.LOCATION_NAME as DESTINATION,
       CLO.LOCATION_NAME  AS CARRIER_NAME,
       --SRINI CODE STARTS--
       IT.ITEM_NAME,IT.DESCRIPTION,IT.COMMODITY_GID,
       sum(ORH.TOTAL_WEIGHT) TOTAL_WEIGHT ,
	   DLO.LOCATION_NAME,DLO.CITY,DLO.PROVINCE_CODE,
	   sum(ORL.ITEM_PACKAGE_COUNT) TOTAL_ITEM_PACKAGE_COUNT ,
       SHR.SHIPMENT_REFNUM_VALUE AS IS_PRELOAD,
       OREF7.ORDER_RELEASE_REFNUM_VALUE  AS SCHEDULE_UPDATE_USER,
       LR.LOCATION_REFNUM_VALUE AS CUSTOMER_NAME,
       SLO.ZONE1 AS "Supply Chain Region",
       OREF8.ORDER_RELEASE_REFNUM_VALUE  AS CSR_TEAM,
       OREF9.ORDER_RELEASE_REFNUM_VALUE  AS CSR,
       SLO.LOCATION_NAME AS SOURCE_LOCATION_NAME,
       OREF10.ORDER_RELEASE_REFNUM_VALUE  AS CPU_CONTACT,
       SHR1.SHIPMENT_REFNUM_VALUE AS APPT_TYPE,
       DLO.LOCATION_NAME AS DESTINATION_LOCATION_NAME,
       SHP.ATTRIBUTE3 AS TRAILER_NUMBER,
       LR1.LOCATION_REFNUM_VALUE AS PARTY_SITE_NUMBER,
       ORH.SHIP_WITH_GROUP,
       --
       TO_CHAR(utc.get_local_date (ORH.early_pickup_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') as EARLY_PICKUP_DATE,
       TO_CHAR(utc.get_local_date (ORH.late_pickup_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') as LATE_PICKUP_DATE,
       TO_CHAR(utc.get_local_date (ORH.EARLY_DELIVERY_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') as EARLY_DELIVERY_DATE,
       TO_CHAR(utc.get_local_date (ORH.LATE_DELIVERY_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS') as LATE_DELIVERY_DATE
       --
  FROM ORDER_RELEASE  ORH
       --left join ORDER_RELEASE_REFNUM OREF on (ORH.ORDER_RELEASE_GID = OREF.ORDER_RELEASE_GID and OREF.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.ORIGINAL_REQUEST_DATE')
       LEFT JOIN ORDER_RELEASE_REFNUM OREF2
           ON (    ORH.ORDER_RELEASE_GID = OREF2.ORDER_RELEASE_GID
               AND OREF2.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.SCHEDULER')
       LEFT JOIN ORDER_RELEASE_REFNUM OREF3
           ON (    ORH.ORDER_RELEASE_GID = OREF3.ORDER_RELEASE_GID
               AND OREF3.ORDER_RELEASE_REFNUM_QUAL_GID = 'SO_NUM')
       LEFT JOIN ORDER_RELEASE_REFNUM OREF4
           ON (    ORH.ORDER_RELEASE_GID = OREF4.ORDER_RELEASE_GID
               AND OREF4.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.SCHEDULE_UPDATE_USER')
       LEFT JOIN ORDER_RELEASE_REFNUM OREF5
           ON (    ORH.ORDER_RELEASE_GID = OREF5.ORDER_RELEASE_GID
               AND OREF5.ORDER_RELEASE_REFNUM_QUAL_GID = 'CUST_PO')
		LEFT JOIN ORDER_RELEASE_REFNUM OREF6
           ON (    ORH.ORDER_RELEASE_GID = OREF6.ORDER_RELEASE_GID
               AND OREF6.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.CUSTOMER_REGION')
		LEFT JOIN ORDER_RELEASE_REFNUM OREF7
           ON (    ORH.ORDER_RELEASE_GID = OREF7.ORDER_RELEASE_GID
               AND OREF7.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.SCHEDULE_UPDATE_USER')
		LEFT JOIN ORDER_RELEASE_REFNUM OREF8
           ON (    ORH.ORDER_RELEASE_GID = OREF8.ORDER_RELEASE_GID
               AND OREF8.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.CSR_TEAM')
		LEFT JOIN ORDER_RELEASE_REFNUM OREF9
           ON (    ORH.ORDER_RELEASE_GID = OREF9.ORDER_RELEASE_GID
               AND OREF9.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.CSR')
		LEFT JOIN ORDER_RELEASE_REFNUM OREF10
           ON (    ORH.ORDER_RELEASE_GID = OREF10.ORDER_RELEASE_GID
               AND OREF10.ORDER_RELEASE_REFNUM_QUAL_GID = 'NBL.CPU_CONTACT')
		--LEFT JOIN ORDER_RELEASE_STATUS ORS ON (ORH.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID = 'NBL.APPT_TYPE')
        LEFT JOIN ORDER_RELEASE_STATUS ORS ON (ORH.ORDER_RELEASE_GID = ORS.ORDER_RELEASE_GID AND ORS.STATUS_TYPE_GID IN ('NBL.APPT_TYPE','NBL/MX.APPT_TYPE'))			
       --LEFT JOIN ORDER_MOVEMENT OM ON ORH.ORDER_RELEASE_GID = OM.ORDER_RELEASE_GID			   
	   --LEFT JOIN VIEW_SHIPMENT_ORDER_RELEASE V ON ORH.ORDER_RELEASE_GID = V.ORDER_RELEASE_GID
       --LEFT JOIN SHIPMENT SHP ON V.SHIPMENT_GID = SHP.SHIPMENT_GID
	   		LEFT JOIN (SELECT DISTINCT SSUL.ORDER_RELEASE_GID,SSEJ.SHIPMENT_GID FROM S_SHIP_UNIT_LINE SSUL, S_EQUIPMENT_S_SHIP_UNIT_JOIN SESSUJ, SHIPMENT_S_EQUIPMENT_JOIN SSEJ
WHERE SSUL.S_SHIP_UNIT_GID = SESSUJ.S_SHIP_UNIT_GID
AND SESSUJ.S_EQUIPMENT_GID = SSEJ.S_EQUIPMENT_GID

)V ON ORH.ORDER_RELEASE_GID = V.ORDER_RELEASE_GID
       LEFT JOIN SHIPMENT SHP ON V.SHIPMENT_GID = SHP.SHIPMENT_GID
	   LEFT JOIN SHIPMENT_REFNUM SHR ON (SHP.SHIPMENT_GID = SHR.SHIPMENT_GID AND SHR.SHIPMENT_REFNUM_QUAL_GID = 'NBL.IS_PRELOAD')
       LEFT JOIN SHIPMENT_REFNUM SHR1 ON (SHP.SHIPMENT_GID = SHR1.SHIPMENT_GID AND SHR1.SHIPMENT_REFNUM_QUAL_GID = 'NBL.APPT_TYPE')
	   LEFT JOIN SHIPMENT_STOP STP
           ON (SHP.SHIPMENT_GID = STP.SHIPMENT_GID AND STP.STOP_NUM = '1')
       --LEFT JOIN SHIPMENT_STATUS SS ON (SHP.SHIPMENT_GID = SS.SHIPMENT_GID AND SS.STATUS_TYPE_GID = 'NBL.SECURE RESOURCES')
	   LEFT JOIN SHIPMENT_STATUS SS ON (SHP.SHIPMENT_GID = SS.SHIPMENT_GID AND SS.STATUS_TYPE_GID IN ('NBL.SECURE RESOURCES','NBL/MX.SECURE RESOURCES'))
       --LEFT JOIN SHIPMENT_STATUS SS2 ON (SHP.SHIPMENT_GID = SS2.SHIPMENT_GID AND SS2.STATUS_TYPE_GID = 'NBL.WMS_STATUS')
	   LEFT JOIN SHIPMENT_STATUS SS2 ON (SHP.SHIPMENT_GID = SS2.SHIPMENT_GID AND SS2.STATUS_TYPE_GID IN ('NBL.WMS_STATUS','NBL/MX.WMS_STATUS'))
        LEFT JOIN ORDER_RELEASE_REMARK OREM
           ON (    ORH.ORDER_RELEASE_GID = OREM.ORDER_RELEASE_GID
               AND OREM.REMARK_QUAL_GID = 'SHIP_DATE')  
       left join LOCATION SLO on ORH.SOURCE_LOCATION_GID = SLO.LOCATION_GID
       left join LOCATION DLO on ORH.DEST_LOCATION_GID = DLO.LOCATION_GID
	   LEFT JOIN LOCATION CLO ON SHP.SERVPROV_GID = CLO.LOCATION_GID
	   LEFT JOIN LOCATION_REFNUM LR ON (ORH.DEST_LOCATION_GID = LR.LOCATION_GID AND LR.LOCATION_REFNUM_QUAL_GID = 'CUSNM')
	   LEFT JOIN LOCATION_REFNUM LR1 ON (ORH.DEST_LOCATION_GID = LR1.LOCATION_GID AND LR1.LOCATION_REFNUM_QUAL_GID = 'NBL.PARTY_SITE_NUMBER')
       ,ORDER_RELEASE_LINE ORL
       ,PACKAGED_ITEM PKG
       ,ITEM IT
       WHERE 1 = 1
--and ORH.ORDER_RELEASE_GID ='NBL.37845558'
AND TO_CHAR(ORH.INSERT_DATE, 'DD/MM/YYYY') BETWEEN '01/04/2025' AND '20/05/2025'
AND ORH.DOMAIN_NAME = 'NBL/MX'

       AND (   (    ORH.LATE_PICKUP_DATE IS NULL 
                  AND ORH.LATE_DELIVERY_DATE >= TRUNC(SYSDATE -10) 
                  AND ORH.LATE_DELIVERY_DATE < TRUNC(SYSDATE + 16))
              OR (    ORH.LATE_PICKUP_DATE IS NOT NULL 
                  AND ORH.LATE_PICKUP_DATE >= TRUNC(SYSDATE-10) 
                  AND ORH.LATE_PICKUP_DATE < TRUNC(SYSDATE+16)))
         AND ORH.SOURCE_LOCATION_GID IS NOT NULL
                  AND (    ORH.ORDER_RELEASE_GID = ORL.ORDER_RELEASE_GID 
              AND ORL.PACKAGED_ITEM_GID = PKG.PACKAGED_ITEM_GID
	      AND PKG.ITEM_GID          = IT.ITEM_GID)
		  /*and (SHP.SHIPMENT_GID not like '%WSH%' OR SHP.SHIPMENT_GID IS NULL)*/
AND (
    ( 
        -- Case 1: If the order has only 1 shipment and it's NB, MX, or WSH, show the shipment
        (SELECT COUNT(DISTINCT V.SHIPMENT_GID) 
         FROM (SELECT DISTINCT SSUL.ORDER_RELEASE_GID, SSEJ.SHIPMENT_GID 
               FROM S_SHIP_UNIT_LINE SSUL, 
                    S_EQUIPMENT_S_SHIP_UNIT_JOIN SESSUJ, 
                    SHIPMENT_S_EQUIPMENT_JOIN SSEJ
               WHERE SSUL.S_SHIP_UNIT_GID = SESSUJ.S_SHIP_UNIT_GID
                 AND SESSUJ.S_EQUIPMENT_GID = SSEJ.S_EQUIPMENT_GID) V
         WHERE V.ORDER_RELEASE_GID = ORH.ORDER_RELEASE_GID) = 1 
        AND (SHP.SHIPMENT_GID LIKE '%NB%' 
             OR SHP.SHIPMENT_GID LIKE '%MX%' 
             OR SHP.SHIPMENT_GID LIKE '%WSH%'
             )
    )
    OR 
    ( 
        -- Case 2: If the order has multiple shipments, show only NB/MX shipments but exclude WSH
        (SELECT COUNT(DISTINCT V.SHIPMENT_GID) 
         FROM (SELECT DISTINCT SSUL.ORDER_RELEASE_GID, SSEJ.SHIPMENT_GID 
               FROM S_SHIP_UNIT_LINE SSUL, 
                    S_EQUIPMENT_S_SHIP_UNIT_JOIN SESSUJ, 
                    SHIPMENT_S_EQUIPMENT_JOIN SSEJ
               WHERE SSUL.S_SHIP_UNIT_GID = SESSUJ.S_SHIP_UNIT_GID
                 AND SESSUJ.S_EQUIPMENT_GID = SSEJ.S_EQUIPMENT_GID) V
         WHERE V.ORDER_RELEASE_GID = ORH.ORDER_RELEASE_GID) > 1 
        AND (SHP.SHIPMENT_GID LIKE '%NB%' 
             OR SHP.SHIPMENT_GID LIKE '%MX%'
            )
        AND SHP.SHIPMENT_GID NOT LIKE '%WSH%'
    )
OR SHP.SHIPMENT_GID IS NULL
)
group by
		  ORH.ORDER_RELEASE_GID,ORL.ORDER_RELEASE_LINE_GID,
SUBSTR (ORH.ORDER_RELEASE_GID, -8),
ORH.INDICATOR,
SHP.INDICATOR,
ORH.USER_DEFINED2_ICON_GID,
ORH.ATTRIBUTE2,
ORH.PAYMENT_METHOD_CODE_GID,
ORH.USER_DEFINED5_ICON_GID,
ORH.USER_DEFINED1_ICON_GID,
(CASE
     WHEN (   ORH.USER_DEFINED1_ICON_GID = 'NBL.NBL_SCHEDULED_APPT'
           OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_SCHEDULED_APPT'
           OR ORH.USER_DEFINED1_ICON_GID = 'NBL.APPT_SCHEDULED'
           OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_PENDING_APPT'
           OR ORH.USER_DEFINED1_ICON_GID = 'ITEM')
     THEN 'Scheduled'
     ELSE 'Not Scheduled'
 END),
ORH.SOURCE_LOCATION_GID,
ORH.DEST_LOCATION_GID,
(CASE
     WHEN ORH.LATE_PICKUP_DATE IS NULL
     THEN  TO_CHAR(utc.get_local_date (ORH.LATE_DELIVERY_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS')
     ELSE  TO_CHAR(utc.get_local_date (ORH.LATE_PICKUP_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS')
 END),
TO_CHAR(utc.get_local_date (ORH.INSERT_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
ORH.TRANSPORT_MODE_GID,
ORH.RATE_OFFERING_GID,
OREF2.ORDER_RELEASE_REFNUM_VALUE,
OREF3.ORDER_RELEASE_REFNUM_VALUE,
OREF4.INSERT_USER,
OREF5.ORDER_RELEASE_REFNUM_VALUE,
OREF6.ORDER_RELEASE_REFNUM_VALUE,
OREM.REMARK_TEXT,
TO_CHAR(utc.get_local_date (OREF4.INSERT_DATE, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
SHP.SHIPMENT_GID,
TO_CHAR(utc.get_local_date (SHP.START_TIME, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
TO_CHAR(utc.get_local_date (STP.APPOINTMENT_PICKUP, ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
(CASE
     WHEN SS.STATUS_VALUE_GID IS NULL THEN 'Not Tendered'
     ELSE 'Tendered'
 END),
(CASE
     WHEN SS.STATUS_VALUE_GID IS NOT NULL
     THEN 'Tendered'
     WHEN     (   ORH.USER_DEFINED1_ICON_GID =
                  'NBL.NBL_SCHEDULED_APPT'
               OR ORH.USER_DEFINED1_ICON_GID =
                  'NBL.CAR_SCHEDULED_APPT'
               OR ORH.USER_DEFINED1_ICON_GID = 'NBL.APPT_SCHEDULED'
               OR ORH.USER_DEFINED1_ICON_GID = 'NBL.CAR_PENDING_APPT'
               OR ORH.USER_DEFINED1_ICON_GID = 'ITEM')
            AND SS.STATUS_VALUE_GID IS NULL
     THEN 'Scheduled Not Tendered'
     ELSE 'Not Scheduled'
 END),
SS2.STATUS_VALUE_GID,
CLO.LOCATION_NAME,
IT.ITEM_NAME,IT.DESCRIPTION,IT.COMMODITY_GID,
DLO.LOCATION_NAME,DLO.CITY,DLO.PROVINCE_CODE,
SHR.SHIPMENT_REFNUM_VALUE,
OREF7.ORDER_RELEASE_REFNUM_VALUE,
LR.LOCATION_REFNUM_VALUE,
SLO.ZONE1,
OREF8.ORDER_RELEASE_REFNUM_VALUE,
OREF9.ORDER_RELEASE_REFNUM_VALUE,
SLO.LOCATION_NAME,
OREF10.ORDER_RELEASE_REFNUM_VALUE,
SHR1.SHIPMENT_REFNUM_VALUE,
DLO.LOCATION_NAME,
SHP.ATTRIBUTE3,
LR1.LOCATION_REFNUM_VALUE,
ORH.SHIP_WITH_GROUP,
TO_CHAR(utc.get_local_date (ORH.early_pickup_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
TO_CHAR(utc.get_local_date (ORH.late_pickup_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
TO_CHAR(utc.get_local_date (ORH.EARLY_DELIVERY_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS'),
TO_CHAR(utc.get_local_date (ORH.LATE_DELIVERY_DATE,ORH.SOURCE_LOCATION_GID), 'YYYY-MM-DD HH24:MI:SS')